### ISSUE TITLE
Custom Registration Fields

### ISSUE THREAD

**Issue by brad-decker** [auth0/wp-auth0#100]
Not sure where to get help with this at. 

My issue is how would I handle adding custom fields to the registration form for authenticating with wordpress? Are there any examples of this having been done? we obviously have to use redirect mode in order to tie into the wordpress plugin, but i don't know how to attach custom fields into the request and documentation on the website for popup mode custom fields just says "then you'll handle sending the api." without giving examples.

**Comment by glena** [comment]
As I tolk you via email, Right now, you have two options:

- Hook to the `auth0_user_login` action (https://github.com/auth0/wp-auth0#integrating-with-the-plugin) so you can check if the user has the requires fields and, if not, show a second step where you ask for the required fields.

- Override the login page with your own login page and do what the custom signup doc says (https://auth0.com/docs/custom-signup). This doc is updated and it exactly what you need to do:

1. show your custom form
2. on submit do an ajax request to the backend where you will create the user
3. on the ajax callback log the user in. In this step you will need to change the parameters to make it work with the redirect flow with code (add the `"callbackURL"` attribute and "responseType":"code" to the signup parameters).


I will ahead and close this issue to continue discussing in the ticket.
