### ISSUE TITLE
Install_db being called all the time...

### ISSUE THREAD

**Issue by gkeane** [auth0/wp-auth0#104]
Install_db is being called every time.  This is in a multisite install

I believe it's
        update_option( "auth0_db_version", AUTH0_DB_VERSION );
and
get_site_option( 'auth0_db_version' ) 

not being the same thing...

should it be 
 update_site_option( "auth0_db_version", AUTH0_DB_VERSION );

Causing tons of mysql io...

**Comment by glena** [comment]
I think you are right, I will change `update_option` to `update_site_option` and run some tests.

It should be fixed for the next release, in the meantime, is too much trouble if you just comment this code https://github.com/auth0/wp-auth0/blob/master/WP_Auth0.php#L699-L737 since I will not be able to release a fix until the next release (it is near to be released but cant give you an ETA yet)

**Comment by gkeane** [comment]
Thanks, I just changed the function, tested it, it seems to work fine.

It also looks like the settings are only happening at the blog level, not sitewide.  I'm having to enable and configure Auth0 on each blog.  Typically in multisite you can set options globally, and each blog uses the global settings...  Not as sure how to fix that one..

**Comment by glena** [comment]
In the Vnext, we are working in a way to export/import settings.

I dont think we are going to add a global setup in the near future, but this feature could be a nice workaround, what do you think?

The only issue is if you are generating new sites dinamically.

**Comment by beatelite** [comment]
I just started using this (love the idea) but am generating sites dynamically.  Going to be tough! Any plans to allow settings at the network level?

**Comment by glena** [comment]
Hi @beatelite no, but as I said, a new couple of new features will make this easier. One is the import/export settings and the other is a new wizard for auto-setup.

**Comment by beatelite** [comment]
Awesome! Also, had a thought that might help someone else: We're just cloning a site on the network that has all the settings pre-done. This way the new site will have everything it needs - including the wp-auth0 info. 

It won't help with existing sites but at least it's something.

**Comment by glena** [comment]
@beatelite can you point me to some hook on the cloning process? if there is any it shouldnt be hard

**Comment by beatelite** [comment]
We're using this for it: https://premium.wpmudev.org/project/new-blog-template/
