### ISSUE TITLE
Not redirecting to admin path after SSO login

### ISSUE THREAD

**Issue by jakuub** [auth0/wp-auth0#106]
The use case:

1. I am logged to other part of the page with my admin e-mail
2. from this other part of my application, I am redirected to create post
3. I am not loged in the wordpress, so wordpress redirects me to wp-login page with appropriet recirect_to url
4. auth0 will automaticly logged in me (I have SSO checbox checked in settings)
5. after this login, i was redirected to homepage instead of creating the post (I have appropriate role to create post)

When i place link to the browser like this: http://mypage.me/wp-admin/post-new.php  when i am not logged in WP but logged in other part of the app, it will logg me in, but redirect not to creating of the post, but to homepage.

It don't happend, when SSO is off and only Remember last login	is checked. 

I also tried fresh install of wordpress and wp-auth0 and this there were also this bug.

**Comment by glena** [comment]
Thanks for reporting, I will review and target to fix for the next release

**Comment by jakuub** [comment]
Thank you  very much. Can I have a question, when approximetly it will be?

**Comment by jakuub** [comment]
Hello, is there som ETA on next release please?

**Comment by glena** [comment]
Sorry no ETA, BUT can you replace this lines 

https://github.com/auth0/wp-auth0/blob/1940d7de2ad4bcfb4ffba5c05e39a86339827eb7/templates/auth0-login-form.php#L49-L51

with this:

```
$extraOptions = array(
    "state" => $state,
    "authParams"    => array("state" => $state),
);
```

This should do the trick and when you update the plugin for the next release, it should continue working as expected.

**Comment by jakuub** [comment]
Perfect, thank you very much. It works :-).

**Comment by glena** [comment]
cool :) sorry for the delay.
