### ISSUE TITLE
SSO state and lock exception.

### ISSUE THREAD

**Issue by jakuub** [auth0/wp-auth0#109]
Hello, some time ago, we had a problem with SSO state #106. We fixed it with quickfix from the issue (added the `$extraOptions`). But this created the prolem with lock.min.js in login form, when we get `Uncaught TypeError: this.state` error. 
![pasted image at 2016_01_07 01_50 pm](https://cloud.githubusercontent.com/assets/1863153/12172272/352c29c4-b550-11e5-853d-40798ab8e073.png)

We fixed it by the quickfix from german:
can you add `delete options.state;` before this lines?

https://github.com/auth0/wp-auth0/blob/master/templates/auth0-login-form.php#L173
https://github.com/auth0/wp-auth0/blob/master/templates/auth0-login-form.php#L207

GitHub
auth0/wp-auth0
wp-auth0 - Wordpress Plugin for Auth0

​[2:03] 
between the `var options = …` and the `lock.show…`

It work fine, but it is little bit messy. @glena asked me to add this issue, so here it is. You can find our conversation in slack started aproximetly here: https://auth0-chat.slack.com/archives/general/p1452171090000015

**Comment by glena** [comment]
Hey, IDK if you realise a new version was released.
It should be fixed [here](https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_Lock_Options.php#L175-L176) so can you try it out and let me know? (you can upload this new version manually -you can download it from [here](https://github.com/auth0/wp-auth0/archive/master.zip) - so you don't override your changes in the previous version, remember to disable the other one).
