### ISSUE TITLE
Redirect to default domain also from aditional domain for different language

### ISSUE THREAD

**Issue by jakuub** [auth0/wp-auth0#110]
Hello. We use multidomain install of wp with different domains for languages by WPML. 

The problem here is, that when we want someone to login on different(www.mysite.sk) than default(www.mysite.com) domain, this will happen:
1. user try to login on other domain (eg www.mysite.sk)
2. the login form is showned
3. user enter credentials
4. user login successful
5. user redirect to default domain (www.mysite.com)

This can be fixed by replacing `site_url` with `home_url` to stay on actual "domain" rather then change to default here:
https://github.com/auth0/wp-auth0/blob/master/templates/auth0-login-form.php#L52

This is other custom bugfix we needed, but I think, only needed edit is one described above and I hope it will not break something, but I think it shouldnt.

**Comment by jakuub** [comment]
I want to admit, that the same problem ocures with SSO, but I think it is becouse `$callbackURL` is used in both.

**Comment by glena** [comment]
yes, it is due to how `$callbackURL` is created as you said.

I think it make sense o user `home_url` but help me trying to figure out why it shouldnt...

I think it should work fine in every case right?

**Comment by jakuub** [comment]
Yues, I think so. I don't see any problem with using `home_url`, I just didn't read the whole code, so I don't know all occurences.

**Comment by glena** [comment]
I think just there. can you change it in your code for now? I will push the change for V.next in a couple of minutes

**Comment by jakuub** [comment]
Thank you, I already changed it in my code, I just wanted to let you know, to idealy get it in to next release :-).

**Comment by glena** [comment]
done! :point_up: 

thank you

**Comment by jakuub** [comment]
Thank you too :-).
