### ISSUE TITLE
Wordpress Auth0 plugin + 3rd party app (Thinkific)

### ISSUE THREAD

**Issue by juliagreig** [auth0/wp-auth0#114]
I am having troubles connecting the Thinkific SSO to my wordpress site.

Goal: I want the user to log in or sign up on the wordpress site, and stay on the wordpress site after logging in. Then, when they click on a link to the thinkific site, they are redirected and already logged in on the thinkific side.

I have a wordpress site hosted by godaddy and I installed and configured the auth0 plugin to work with an app I created in the auth0 dashboard. I can log in and sign up fine on the Wordpress side, and my users are stored in the Auth0 dashboard. 

I have created a rule for the Thinkific site, similar to that of the zendesk SSO rule. Here is my code (I removed my thinkific subdomain for privacy): 
```
function (user, context, callback) {

 var THINKIFIC_SUBDOMAIN = 'subdomain_here';

  // Generate a random UUID: http://en.wikipedia.org/wiki/Universally_unique_identifier
  // Used in the token's jti claim to avoid replay attacks
  var uuid = require('uuid');

  // Create the JWT as required by Thinkific
  var payload = {
    iat: new Date().getTime() / 1000,
    jti: uuid.v4(),
    first_name: user.name,
    last_name: user.name,
    email: user.email
  };
  
  context.redirect = {
        url: "https://" + THINKIFIC_SUBDOMAIN + ".thinkific.com"
    };

  // Sign the token and add it to the profile
  var thinkific_token = jwt.sign(payload, configuration.thinkific_secret);
  user.thinkific_jwt_url = 'https://' + THINKIFIC_SUBDOMAIN + 'thinkific.com/sso/jwt?jwt=' + thinkific_token;

  callback(null, user, context);
}
```

I set it to redirect directly to my thinkific site just so I can immediately see if the login/sso works. So after logging in on the wordpress side I get redirected to my thinkific site but I am not logged in there.

I am not sure if I should be doing any extra configuration on the auth0 side for my thinkific site, or if this rule should be enough.

For your reference, here is the SSO documentation for Thinkific: http://support.thinkific.com/knowledgebase/articles/462305-sso-automatically-sign-in-from-your-own-website

Thanks in advance for your help!

Julia

**Comment by glena** [comment]
Hi @juliagreig I think we worked it out the other day on slack.

I will go ahead and close this issue, but feel free to pingme me here or on slack if something comes up.

**Comment by isaacsavage** [comment]
Hi @glena and @juliagreig, 
I am also interested in this functionality. Did you come up with a solution that works well? Is this available via WP plugin?
Thanks!
Isaac
