### ISSUE TITLE
No Buttons to Activate Social Login when Installing

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#116]
When following the quickstart to install the plugin the social login activate buttons only appear at the end of the list, so it lets me enable-disable just the last two social providers
![noactivatebutton1](https://cloud.githubusercontent.com/assets/5016479/12727054/2d56ec74-c8ed-11e5-9f56-ddd9dcba7028.JPG)
![noactivatebutton2](https://cloud.githubusercontent.com/assets/5016479/12727055/2e2216c4-c8ed-11e5-8e4a-f7224b25839c.JPG)

**Comment by glena** [comment]
which browser and viewport size?

**Comment by Annyv2** [comment]
Firefox  1280 × 689

**Comment by glena** [comment]
couldn't reproduce it
