### ISSUE TITLE
No Token in Settings

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#117]
When installating I added  the token but it doesn't appear in the settings
I updated the client secret and token but when settings are saved they dissapear. Is this the expected behavior? 

![notoken](https://cloud.githubusercontent.com/assets/5016479/12727125/98affdd0-c8ed-11e5-93bc-22dbf95624a1.JPG)
![updatedbutmissing](https://cloud.githubusercontent.com/assets/5016479/12727126/99d2ac80-c8ed-11e5-8e0a-3941b42b68bd.JPG)

**Comment by glena** [comment]
the secret and the token will not be visible there (nor hidden as password). What do you suggest in terms of copy to make it understandable?

**Comment by Annyv2** [comment]
Maybe a "not visible" or something similar in the box could be put. When I was installing it, I thought I had to put them again because the Client ID does appear

**Comment by glena** [comment]
mm yes, a placeholder sounds good

**Comment by glena** [comment]
![image](https://cloud.githubusercontent.com/assets/5647310/12752802/f369a7b6-c9a2-11e5-93e8-c67f07cb0e53.png)
