### ISSUE TITLE
Advanced Tab -  Remember Users Session:

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#118]
Users session by default lives for two days. Enabling this setting will make the sessions live longer.
Questions: How much longer? Can the days be customized? Where can I find more information?

**Comment by glena** [comment]
```The $remember parameter increases the time that the cookie will be kept. The default the cookie is kept without remembering is two days. When $remember is set, the cookies will be kept for 14 days or two weeks.```

from https://codex.wordpress.org/Function_Reference/wp_set_auth_cookie

**Comment by glena** [comment]
updated the copy to:

![image](https://cloud.githubusercontent.com/assets/5647310/12752900/49dda282-c9a3-11e5-9d3b-4f00ab85262a.png)

what do you think?

**Comment by Annyv2** [comment]
Great!
