### ISSUE TITLE
Advanced Tab - Social

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#120]
Facebook and Twitter Consumer ID and Secret appear but on my auth0 account I also have Google +, Linkedin and Yahoo.
Question: is it the expected behaviour that only Facebook and Twitter Appear?
![twitter and facebook](https://cloud.githubusercontent.com/assets/5016479/12727263/5af07424-c8ee-11e5-8633-465548dcf547.JPG)

**Comment by glena** [comment]
Yes, it is related to a widget called `social amplificator` that allows you to share the page using and it uses your social credentials from auth0. only works with facebook and twitter for now

**Comment by Annyv2** [comment]
Ok, Closing this issue
