### ISSUE TITLE
Advanced Tab - User Migration

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#121]
> Users migration is disabled. Enabling it will expose the migration webservices but the connection need to be updated manually on the Auth0 dashboard.

Typo: needs to be

Question: How can I do that? Does it refer to "Import Users to Auth0"? The option is blocked when I try to activate it in Auth0.com

**Comment by glena** [comment]
Good point, it should point to that doc, and the reason it has to be manual is exactly that, you need to create a new db connection, we want this to be explicit to avoid issues with existing users since they will not be able to access anymore.

**Comment by glena** [comment]
Added the reference

![image](https://cloud.githubusercontent.com/assets/5647310/12753007/d22c1650-c9a3-11e5-9204-02a7343c476b.png)

**Comment by Annyv2** [comment]
Great!
