### ISSUE TITLE
Users Export

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#127]
> This action will export all your WordPress users that has an Auth0 account.
Do you want to continue?

Typo: that have
Suggested: This action will export all your WordPress users in your Auth0 account.

This is because users don't have an "Auth0 account" per se (like example.auth0.com), but i'm unsure of how to state it better. On zendesk we have received some questions regarding "do we have to create an Auth0 account for each user" so this aspect could be better explained

**Comment by glena** [comment]
No, this feature will export a CSV file with the wordpress users that has Auth0 info linked in their profile.

**Comment by glena** [comment]
No, this will export all your users in your wordpress database that had login at least once with auth0.

**Comment by glena** [comment]
refrased as `This action will export all your WordPress users that has logged in using Auth0`, does it sound better?

**Comment by Annyv2** [comment]
It sounds so much better! but I think it should be "that have logged in", what do you think?

**Comment by glena** [comment]
yes, d'oh

thanks
