### ISSUE TITLE
Implicit Flow Bug

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#128]
When using Implicit Flow, wordpress say "Sorry. There was a problem loggin you in", when trying to log in with a username/password user.

On the error Logs in Auth0 a "cannot handle token prior to " error can be seen. Firefox, Windows 7 and XAMP

![problemlogginyouin](https://cloud.githubusercontent.com/assets/5016479/12727617/e9b1c658-c8ef-11e5-8f2e-d073b7efa081.JPG)
![errorlog](https://cloud.githubusercontent.com/assets/5016479/12727621/eae425de-c8ef-11e5-904d-be3e3b6e371a.JPG)

**Comment by glena** [comment]
This is because your local time might be off for a couple of minutes. Try updating your clock

**Comment by Annyv2** [comment]
But is it normal that I was able to log in using a social provider with the same settings and clock but not with a username-password?

**Comment by glena** [comment]
shouldnt but it is posible.

**Comment by Annyv2** [comment]
Oh, ok. Then I'll close the issue since it's related to my machine
