### ISSUE TITLE
Bad Link - Appearance Tab

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#131]
Bad link on the gravatar section:

https://github.com/auth0/lock/wiki/Auth0Lock-customization#gravatar-boolean This page doesnt exist
Instead it redirects to https://github.com/auth0/lock#gravatar-boolean

Correct link would be https://auth0.com/docs/libraries/lock/customization#gravatar-boolean- 
Or on github https://github.com/auth0/docs/blob/master/articles/libraries/lock/customization.md#gravatar-boolean

**Comment by glena** [comment]
fixed
