### ISSUE TITLE
Bad Link - Appearance Tab - Custom JS

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#132]
Bad Link on "Customize the login widget with custom JS" section:

It redirects to https://auth0.com/docs/hrd#3
Which is a link about using email domains with lock on a tutorial about "Selecting the connection in Auth0 for multiple login options". 

Is it related to custom JS?

**Comment by glena** [comment]
This is right. This is an example on how to add custom buttons to Lock. Anyway, seems the anchor changed and the link should be `https://auth0.com/docs/hrd#option-3-adding-custom-buttons-to-lock`

**Comment by glena** [comment]
fixed
