### ISSUE TITLE
Bad link - Appearance Tab - Username

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#133]
https://github.com/auth0/lock/wiki/Auth0Lock-customization#usernamestyle-string Doesn't exist
it redirects to https://github.com/auth0/lock#usernamestyle-string

It should be  https://auth0.com/docs/libraries/lock/customization#usernamestyle-string-
or on github  https://github.com/auth0/docs/blob/master/articles/libraries/lock/customization.md#usernamestyle-string

**Comment by glena** [comment]
fixed
