### ISSUE TITLE
Bad Link - Appearance Tab - Remember Last Login

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#134]
https://github.com/auth0/lock/wiki/Auth0Lock-customization#rememberlastlogin-boolean Doesn't exist
it redirects to https://github.com/auth0/lock#rememberlastlogin-boolean

Should be https://auth0.com/docs/libraries/lock/customization#rememberlastlogin-boolean-
or on gihtub https://github.com/auth0/docs/blob/master/articles/libraries/lock/customization.md#rememberlastlogin-boolean

**Comment by glena** [comment]
fixed
