### ISSUE TITLE
Social connections 

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#135]
When activating a Social Connection in the Connections Tab of the Plugin, it doesn't let me edit the Client ID and Secret for that particular connection right there, so it has to be done in Auth0.com dashboard. Also, it should be stated somewhere in the plugin that these settings need to be changed  (or else users could use Auth0 dev keys permanently or could receive errors)

**Comment by glena** [comment]
Yes, you should do that in the auth0 dashboard and agree we need to add some text. What do you think about something like this?

![image](https://cloud.githubusercontent.com/assets/5647310/12783890/ba213058-ca62-11e5-85f1-4a0898f3591f.png)

**Comment by Annyv2** [comment]
That looks great! But I think that  "access the Auth0 Dashboard" would be better, what do you think?

**Comment by glena** [comment]
sure
