### ISSUE TITLE
Bug - Domain not set up

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#137]
Unsure of what caused this. I tried to set up the plugin to use Enterprise Connection, then I configured IP connection in the Dashboard. After that I tried to log in using a hotmail mail but this error appears (I was able to login using hotmail previously)

![thedomainhotmail](https://cloud.githubusercontent.com/assets/5016479/12729537/802a2fcc-c8f9-11e5-866e-bb4aa43afd82.JPG)

**Comment by glena** [comment]
This has to be some misconfiguration in auth0 since the plugin does not mess with this stuff. are you able to use this same connection in other site?

**Comment by Annyv2** [comment]
I tested a Jquery app using hotmail and it worked (same Auth0 account). It just happens in the plugin

**Comment by glena** [comment]
Couldnt repro
