### ISSUE TITLE
word order for App token required scopes very confusing

### ISSUE THREAD

**Issue by Catografix** [auth0/wp-auth0#140]
The word order for the required scopes for the App token on the basic settings page of v2 Wordpress Auth0 plugin is very confusing. 
![scopes-wordpress](https://cloud.githubusercontent.com/assets/12396567/13434845/63c4f4da-dfa5-11e5-8030-a0f319181292.png)

I suggest "**users**: read, update, create - **clients**: update, create - **connections**: read, update, create - **rules**: delete, create"

This way the order matches the order these items appear in the dropdown of the token generator.

**Comment by glena** [comment]
what do you think about this?

![image](https://cloud.githubusercontent.com/assets/5647310/13527847/f57f3f0a-e1f0-11e5-98d6-6cad82608573.png)

**Comment by Catografix** [comment]
Much better :+1:
