### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#141]
When using Auth0 to login to wordpress, and then going to Profile -  Account Management, it gives me the opportunity to change the password. Now, if I do, I am changing the Wordpress Password, not Auth0's so if I try to login again using Lock, my password was clearly not changed.

![accountmanagement](https://cloud.githubusercontent.com/assets/5016479/13464936/83207438-e065-11e5-9f92-51a6c8f81193.JPG)

From the end-user point of view this can be missleading, since most of them probably wouldn't know the difference between login in using Auth0 or login in using Wordpress, for them they are simply login in to the website. So, if they encounter this situation, they could start e-mailing the website owner asking why their password wasn't changed or something similar.

Is it possible to add a comment on the profile of the user about this matter? 
Maybe let the developer know that this could be a possible case for them to do something about the profile or for them to be aware?

**Comment by glena** [comment]
ready for next release
