### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#142]
This can be tested here https://wplive-annytechaidwp.c9users.io/wp-login.php?action=register

When using the Register function, it opens Lock in log in form and it also opens the wordpress register function. This can be seen in the next two images (same screen, scrolling down)

![register1](https://cloud.githubusercontent.com/assets/5016479/13465548/6254ba22-e068-11e5-81b8-695d20354b24.JPG)
![register2](https://cloud.githubusercontent.com/assets/5016479/13465552/6405f570-e068-11e5-8b7f-b5f96a9ed13b.JPG)

This can be missleading to the end user of the website, since the wordpress registration appears and lock is started in log in form, not sign up.

**Comment by glena** [comment]
ready for next release
