### ISSUE TITLE
Site login broken after updating the plugin to version 2

### ISSUE THREAD

**Issue by lots0logs** [auth0/wp-auth0#143]
It appears that version 2 is completely backwards incompatible with previous version. It would have been nice if some sort of warning was presented. After installing the update my login process is completely broken. It took me a month to finally get it configured and working how I need it to and now I can't even make the plugin use my existing Connection. It creates a new connection and database and any attempts to change it in the settings silently fails.  

Please tell me there is a way to use the plugin with my existing connection and database like it was working prior to the update :worried:

**Comment by glena** [comment]
hi @lots0logs it is backwards compatible. Which version did you installed (I assume it was 2.0.3)?

Did you go through the wizard?
This wizard creates a new db connection and an application to enable users migration but it shouldnt if you already configured it with a previous version.

You should be able to set the same domain, client_id and secret you were using before in the basic settings tab. if it fails, check the errors tab and copy it here to see what happened.

**Comment by glena** [comment]
Also, you can check if there was a new application and db connection created by the plugin, you can disable the new connection and enable the other one, you should be able to login using the same users that before

**Comment by lots0logs** [comment]
@glena Hi, thanks for the fast response. I did go through the quick start process and it created a new connection and database in my auth0 account. I've tried several times to input my existing Client ID/Secret/etc but each time I press Save it tells me that the settings were saved successfully but the client ID/Secret etc are returned to their previous values. The same thing happens when I try to adjust any settings from other tabs. It does not save any changed I make though it shows a saved successfully message. 

I checked my debug log and there's nothing being output to the log after trying to save the settings like I described above. There is only one error in the plugin's error page:

```
03/05/2016 04:18:51	WP_Auth0_Api_Client::create_rule	-	{"statusCode":409,"error":"Conflict","message":"A rule with the same name already exists","errorCode":"rule_conflict"}
```

Please let me know what else I can do to help identify and resolve the issue. Thanks in advance for taking time to assist :relieved:

**Comment by glena** [comment]
@lots0logs check your rules, and delete the ones you didn't create (there is one called `Store-Geo-Location-Do-Not-Rename` that might be created by the plugin - it shouldnt unless you enabled the setting- ).

After that you should be able to update the settings (it might create the rule again based on the error).

If this doesnt work, you can always continue using the app created by the plugin and, on the auth0 dashboard, disable the new connection and enable the old one (you can do this on the connections tab on the application config page) and we can check what is happening later (sounds like some inconsistency in the stored settings and the actual state of your application).

**Comment by lots0logs** [comment]
Okay, so it still wouldnt let me save settings after deleting that rule. I tried starting completely over by uninstalling the plugin and removing the saved settings from the database. Now when I try to run the Quick Setup steps I get this screen after inputting my password:

![2016-03- 5_06-57-22-pm](https://cloud.githubusercontent.com/assets/4675662/13551588/ab64e70c-e304-11e5-8d2b-a9d245511794.png)

Here is the tracking ID from that error in case its useful:
```
TRACKING ID: 9bea7120e4936328605f
```

Any ideas?

**Comment by glena** [comment]
did you try changing the database as I told you? this should make it work in the meantime instead of doing again what it seems to not work in your site.

After deleting the settings, does it let you set the client_id, secret and domain manually? do not run the wizard again!

This error seems was caused because auth0 wasnt able to reach the federated oauth2 endpoint, for some reason the plugin wasnt able to add the new routes.

**Comment by lots0logs** [comment]
> did you try changing the database as I told you?

No, I could not try it because I had already deleted the connection and database that the plugin created in my auth0 dashboard. I tried to allow it to create new ones through the setup wizard but that's when I got the error shown in the screenshot included with my last comment.

> After deleting the settings, does it let you set the client_id, secret and domain manually?

No, the settings still will not save. The only new message in the logs is the following:

```
03/06/2016 00:54:30	WP_Auth0_Api_Client::create_rule	http_request_failed	A valid URL was not provided.
```

**Comment by lots0logs** [comment]
@glena So, just a quick update. I finally made some progress. I went in to the database and manually added the client id, secret, and app token. Though it still fails to change many of the settings when I save them. Here are the errors:

```
03/06/2016 10:55:17	WP_Auth0_Api_Client::update_connection	-	{"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type object,null but found type array' on property options (The connection's options (depend on the connection strategy)).","errorCode":"invalid_body"}
03/06/2016 10:54:57	WP_Auth0_Api_Client::update_connection	-	{"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type object,null but found type array' on property options (The connection's options (depend on the connection strategy)).","errorCode":"invalid_body"}
03/06/2016 10:54:53	WP_Auth0_Api_Client::update_connection	-	{"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type object,null but found type array' on property options (The connection's options (depend on the connection strategy)).","errorCode":"invalid_body"}
```

**Comment by glena** [comment]
I sent you an email, lets continue there so (I cant sent private account info here).

**Comment by glena** [comment]
@lots0logs check email pls
