### ISSUE TITLE
Errors in configuring plugin, with no clear path to fixing them...

### ISSUE THREAD

**Issue by jgelsey** [auth0/wp-auth0#145]
These errors occurred when I turn on a few features of the plugin (ones that seem to have failed - although there's no indication these are the ones - are income zipcode and geolocation, but not sure why I have 3 errors for 2 failures).  (1) These shouldn't happen, need to be fixed. (2) Refers to the 'Auth0 dashboard' when there's a plugin "Dashboard" hyperlink just below, easy to confuse.  (3) There is no clue as to what each error is in the error message.  (4) Nor is there any advice of how to fix the errors in the Auth0 dashboard.  Going to the Auth0 dashboard shows no errors.  (5) There's reference to a "Auth0 rule" - not sure WP users will know what that means.  

![image](https://cloud.githubusercontent.com/assets/548826/13556445/c2f55d9a-e38e-11e5-8a23-216bb66e36ec.png)

![image](https://cloud.githubusercontent.com/assets/548826/13556467/2f1cbc8e-e38f-11e5-9ef2-0fd8351856f9.png)

**Comment by jgelsey** [comment]
Note that this happens only after an upgrade from the old Auth0 plugin.  A new WP site and an install of the new plugin works fine.  I can give you access to the site where the error occurs for debugging if that would be helpful.

**Comment by jgelsey** [comment]
Hmm.  This appears to be contention with rules left over from an earlier WP experiment in this account - can't create two rules with the same name.  Can you delete the rule when the feature is turned off in the WP dashboard, or when the WP instance is deleted?  As a temporary fix, perhaps the error message could be changed to be more informative with "look at the logs for the WP plugin for more details."

**Comment by glena** [comment]
It should delete the rule (it stores the rule id to later be able to remove it). I will go through this and check if I can find what happens.

**Comment by glena** [comment]
@jgelsey (you wen through the on boarding process right? or you generated the api token manually?)

**Comment by glena** [comment]
couldnt reproduce but changed the way it create the rules so there is no collision with other rules.
