### ISSUE TITLE
New plugin breaks due to callback URL mismatch?

### ISSUE THREAD

**Issue by jgelsey** [auth0/wp-auth0#146]
Not sure if this is a Pantheon API change or something in the new plugin, if it's not ours marked this "resolved". :)

![image](https://cloud.githubusercontent.com/assets/548826/13560705/4a5eef38-e3d7-11e5-891d-e7aba12939f6.png)

**Comment by glena** [comment]
mm this is weird, seems you are using two sets of urls. one is `pantheonsite.io` and the other `pantheon.io`.

How did you set this app? Was it using the on-boarding wizard or manually on the auth0 dashboard? (if it is the first option, check under `settings->general` if the `WordPress Address` and `Site Address` are using the correct url).
