### ISSUE TITLE
Google Authenticator integration problems

### ISSUE THREAD

**Issue by jgelsey** [auth0/wp-auth0#148]
First time I turned on authenticator, I wasn't stepped through GA setup - instead I was asked for an OTP.  Turned the rule off, and then on again (appears that turning off GA in the WP plugin dashboard does not turn off the rule, so I did so at manage.auth0.com) and was stepped through setup - except that I got this when I entered the OTP generated:

![image](https://cloud.githubusercontent.com/assets/548826/13561324/8d96b1ba-e3e0-11e5-8ab6-f1826252e34d.png)

But now the plugin thinks GA is active, and gives me the above error each time I try to login with Google as IdP.

**Comment by glena** [comment]
> First time I turned on authenticator, I wasn't stepped through GA setup

Is posible that you'd already used GA in this auth0 account for that user? if you already went through the enrollment you need to reset the user setup this on the auth0 dashboard.

About this message, if registrations is turned off in WordPress, you need to enable it (`Settings-> General -> Membership (Anyone can register)`). Anyway, does you already have this user created on WordPress or was this the first login?

**Comment by jgelsey** [comment]
First login

**Comment by glena** [comment]
So yes, you will need to enable signup in the wordpress setup, otherwise the plugin will not be able to create new users.

**Comment by jgelsey** [comment]
I have, but that didn’t make a difference - I am still not being asked for the GA setup on first use.  If you have a few minutes I can show you on Zoom (and give you access to my Pantheon test account so you can replicate).

**Comment by glena** [comment]
solved
