### ISSUE TITLE
sso is loosing `redirect_to`

### ISSUE THREAD

**Issue by glena** [auth0/wp-auth0#150]
When you access to a secure route, it redirects to the login where it does SSO. It is ignoring the `redirect_to` so the user gets redirected to the login instead to the previous url

**Comment by glena** [comment]
solved for next release

**Comment by dleeward** [comment]
This doesn't seem to have been fixed in v.2.1.11

**Comment by glena** [comment]
@dleeward can you check is `implicit mode` is enabled under `advanced` tab in the plugin settings?

This is meant to be used when the server does not have internet access. If this is your case, I found the issue and it is ready for the next release. If your sever has internet access, you can turn this off and it should work out of the box

**Comment by dleeward** [comment]
`implicit` is already off and my server has internet access.

**Comment by glena** [comment]
@dleeward could not reproduce the issue. Can you share a har file with the entire interaction? (https://auth0.com/docs/har)

**Comment by dleeward** [comment]
Here's another user having the same issue at WPEngine.
https://auth0.com/forum/t/redirect-to-specific-wordpress-page-after-login/2855 

Before I spend the time on that though, I need to resolve an issue in ticket 11146.

**Comment by glena** [comment]
@dleeward This post does not have any information, and in fact seems to be working fine based on what it says.

Can you provide the HAR file to be able to see what is happening in your case? I am not able to reproduce.

**Comment by glena** [comment]
@dleeward about sploggers, maybe you can find a way to make with plugin and WangGuard work together with something like this https://github.com/auth0/wp-auth0/pull/209 (I am not familiar on how to integrate with this plugin).

You can also use they API (https://www.wangguard.com/getapikey) and write a rule to check if the use is an splogger. In this case, you can block the user an reject the login
