### ISSUE TITLE
Plugin description text

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#155]
The plugin text, on the plugin page, is currently "Implements the Auth0 Single Sign On solution into Wordpress"

Should be something like:

"Let your users login with any social provider from Twitter to Facebook as well as many others like Github. Enterprise? We've got you covered - <a href="http://auth0.com">Auth0</a> is a full enterprise solution and will work with your Active Directory or any other environment to take control of your wordpress sites."

**Comment by glena** [comment]
Do yo mean this text?

![image](https://cloud.githubusercontent.com/assets/5647310/13918805/43acac80-ef48-11e5-95dd-a54fef65fc31.png)

**Comment by SteveC** [comment]
this one...

<img width="1434" alt="screen shot 2016-03-21 at 8 55 44 am" src="https://cloud.githubusercontent.com/assets/123912/13924781/d33e2abe-ef42-11e5-8219-2a34d062d35e.png">

**Comment by glena** [comment]
ready for the next release
