### ISSUE TITLE
Set up process online / offline

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#156]
Can we skip the question about online or offline to access servers at auth0 by running some javascript to test?

Then if you're online it can give both options, if you're offline it can say "hey we can't contact auth0". Presumably we have to test both the browser can connect and the WP instance can connect too?

What I'm trying to achieve is a reduction in complexity / steps here by not asking the user something complicated unless we can avoid it..

**Comment by glena** [comment]
I thought about this but we would need to host some app to `ping` the plugin, so I went the simpler way. I will keep this in the backlog and check on this later

**Comment by SteveC** [comment]
Hm. Can we not just have a snippet of XML on auth.com or something to grab? like auth0.com/test.xml ?

Or do we really need an actual endpoint? And if so, can we just ping some existing API, anything at all, just to see if it's there or not?

**Comment by glena** [comment]
What we need to test is if auth0 can reach the wordpress site, this is because:

1- Auth0 needs to fetch the client info during the federated oauth2 flow to get the api token
2- Auth0 needs to call the migrations endpoints if custom db + import mode enabled.

When the users selects the `offline` flow, besides skipping the oauth2 flow, it disables the migration mode.

**Comment by SteveC** [comment]
Ok - I think it's important if possible that we try this automatically and only if it fails show the user the offline scary options.

Steve

**Comment by SteveC** [comment]
Since the online/offline screen is only one part of the install process - to be clear I think we should automate everything else too so the process has no user interaction required

**Comment by glena** [comment]
we will close this issue until we figure out how to improve the onboarding flow.
