### ISSUE TITLE
deleting plugin doesn't delete all data

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#158]
If I deactivate and then delete the plugin, then install again... it's kept all my auth0 details and doesn't put me through the on-boarding screens...

I'd say the behavior should be to wipe the auth0 info (server, client ID and so on...) when I delete the plugin?

**Comment by glena** [comment]
only for plugin settings, not sure if it is a good idea delete users information (profiles linked)

ready for the next release
