### ISSUE TITLE
setting text

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#163]
ok so on the main panel

<img width="1422" alt="screen shot 2016-03-21 at 9 09 59 am" src="https://cloud.githubusercontent.com/assets/123912/13925243/de417d92-ef44-11e5-8931-6aae9ea40b1a.png">

Can we make the text

"Auth0 Settings" -> "Auth0 WordPress Plugin Settings"

Then, smaller, beneath that, something saying "For your Auth0 dashboard with more settings click here" so it's clear that the WP settings are different and a quick way to get to the dashboard?

**Comment by glena** [comment]
ready for the next release
