### ISSUE TITLE
Settings / Features / Password policy

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#164]
* Can we default to "fair" or something better than 1-char passwords? 
* Can we change the help text?

Currently it is "For more info about the password policies check HERE"

Let's change that to "The difficulty of the user password where 'none' requires a single character, 'low' requires six characters and so on. For more details see our <a href="https://auth0.com/docs/password-strength">help page on password difficulty</a>"

**Comment by SteveC** [comment]
(FYI mine defaulted to "none" which seems sub-optimal?)

**Comment by glena** [comment]
the auth0 default is `none`. This is why. Anyway makes sense to move to `fair`.
ready for the next release
