### ISSUE TITLE
settings / features / sso

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#165]
Let's turn the text from "Mark this if you want to enable SSO. More info HERE" to:

"Single Sign On (SSO) allows users to signing once to multiple services. For more details, see our <a href="https://auth0.com/docs/sso/single-sign-on">help page on SSO</a>.

**Comment by SteveC** [comment]
And for single logout let's turn "Mark this if you want to enable Single Logout. More info HERE"

in to:

"Single Logout is the opposite of the above SSO, it logs users out of everything at once. For more details, see our <a href="https://auth0.com/docs/sso/single-sign-on">help page on SSO</a>."

**Comment by glena** [comment]
ready for the next release
