### ISSUE TITLE
Add a help tab

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#168]
Add a tab to the settings off to the right called "Help"

Fill it with basic text about the plugin. What the plugin does, and that there is the auth0 settings dashboard too.

Make sure to link to the Auth0 help channels like chat, the website, blog and so on.

Do we have a technical writer to draft this page?

**Comment by SteveC** [comment]
We should include a feedback section in the help tab too, pretty prominent.

I'm not sure what system(s) Auth0 already uses, but some very simple way for the user to submit feedback like "What one thing would you change about this plugin?" or something like that.

**Comment by glena** [comment]
@mgonto who can work on the copy for this page? also, we can add the uservoice widget right? (I think we dont use deligted anymore)

**Comment by mgonto** [comment]
We can add a widget. For copy, if @SteveC can help with it, perfect, otherwise ping Rich about it!

**Comment by mgonto** [comment]
@glena :point_up:

**Comment by glena** [comment]
@SteveC can you?

**Comment by glena** [comment]
Fill it with: 
- basic text about the plugin
- What the plugin does
- there is the auth0 dashboard (manage), what you can do with it and that the rest of the configurations should be done there
- add support channels, website and blog
- add uservoice widget

**Comment by SteveC** [comment]
text:

Thank you for installing the Auth0 WordPress Plugin[link to plugin page].

This plugin allows you to connect your WP instance to many login solutions. If you have many users commenting or buying products from you, then our social connectors will help. They will let users log in using things like Twitter, Google or Facebook. We also support many enterprise login systems like Active Directory.

Auth0 is a powerful solution and besides the options you see here on your WordPress instance, there are many more things you can do on your Auth0 dashboard[link to dashboard]. The dashboard allows you to enable more authentication providers and activate advanced features like running javascript snippets on a login event to do things like record activity or send an email. But don't worry, if you just want to enable social logins for your site, you can safely stay within the options here.

If you're having any issues - please contact us. We have a variety of channels to help you:

* Our chat room[link to chat room] is great for online support
* We have a lot of documentation at our help website[link to docs]
* For more information on Auth0, see our blog[link to blog]

[uservoice widget]

**Comment by SteveC** [comment]
Let's see how that looks (screenshot please german?) and iterate. In particular, I have no idea what the UserVoice widget looks like, so it may be better to integrate it with the text differently.

**Comment by glena** [comment]
Sure

**Comment by glena** [comment]
Checking on the feedback widget

![image](https://cloud.githubusercontent.com/assets/5647310/14000745/52b855aa-f121-11e5-8e67-cd7d9240e0a7.png)

**Comment by glena** [comment]
![image](https://cloud.githubusercontent.com/assets/5647310/14182416/777c4894-f741-11e5-8dc8-9760d0f65a4b.png)
