### ISSUE TITLE
Quick Start Guide

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#169]
I'm worried about the naming here. Calling it "quick start guide" implies that it's a help manual when it's really the setup wizard. Can we rename it to "Setup Wizard" ?

<img width="197" alt="screen shot 2016-03-21 at 9 27 41 am" src="https://cloud.githubusercontent.com/assets/123912/13925852/32db6208-ef47-11e5-87e3-c26e6b2d93f7.png">

**Comment by glena** [comment]
ready for the next release
