### ISSUE TITLE
help

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#170]
So in another bug I asked for a help tab. But the user may also look down here for it on the left:

<img width="197" alt="screen shot 2016-03-21 at 9 27 41 am" src="https://cloud.githubusercontent.com/assets/123912/13925884/5140e7fe-ef47-11e5-8381-d8eb7dd4caf7.png">

Can we put a "Help" link there too that goes to the same tab, when it's done?

**Comment by glena** [comment]
![image](https://cloud.githubusercontent.com/assets/5647310/14000716/397c0758-f121-11e5-9724-19ee0e49bc28.png)
