### ISSUE TITLE
quick start guide screen 1

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#171]
<img width="1433" alt="screen shot 2016-03-21 at 9 30 02 am" src="https://cloud.githubusercontent.com/assets/123912/13925940/8991623c-ef47-11e5-8612-ce7f8140b88b.png">

* change "simple end-user logins" to "Social Login"
* and the text underneath to "Let your users login with their social accounts. For example; Google, Facebook, Twitter and many more along with traditional username and password. Don't worry - if you have existing users they will still be able to login."
* "Effortless employee access" -> "Enterprise Login"
* and the text underneath to "Secure this WordPress instance with your organizations login system so that users can login with their work account information. For example, you can connect to your existing ActiveDirectory infrastructure."

**Comment by glena** [comment]
ready for the next release
