### ISSUE TITLE
online setup popup

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#172]
In the dialog there's the text in bold:

"This plug-in replaces the standard WordPress login screen. The experience is improved of course, but different. By default, there is a link to the regular WordPress login screen should you need it."

This feels scary. Let's change it to:

"Don't worry, you can still use your existing WordPress login. Auth0 adds many features to make login easier and better for your users but the old system will still be there too."

**Comment by glena** [comment]
ready for the next release
