### ISSUE TITLE
auth0 logo on the quick start guide

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#173]
can we change the big logo to a link to auth0.com?

Also, can we include some help? So under this text "Users can log in within their own credentials - social like Google or Facebook, or name/password - or use their employee credentials through an enterprise connection. Use either or both, and you'll increase your WordPress site's security and gather data about your visitors." 

Can we have another line saying "For more information and help on the Auth0 WordPress plugin please visit our help documentation." ... and link to the appropriate page at auth0.com with info? Maybe this page - https://wordpress.org/plugins/auth0/   ?

<img width="1355" alt="screen shot 2016-03-21 at 9 48 57 am" src="https://cloud.githubusercontent.com/assets/123912/13926621/69552fc8-ef4a-11e5-8e23-e00ad562998e.png">

**Comment by glena** [comment]
Pointed to this docs https://auth0.com/docs/cms
The logo points to manage
ready for the next release
