### ISSUE TITLE
import-export settings

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#175]
<img width="1428" alt="screen shot 2016-03-21 at 9 54 44 am" src="https://cloud.githubusercontent.com/assets/123912/13926756/fc7b340a-ef4a-11e5-8ac7-d8f889a51cb6.png">

This needs some paragraph text and some help links on what this does and how to use it. And links to the format of the JSON file and maybe link to the place in my dashboard where I would import or export data?

**Comment by glena** [comment]
> This needs some paragraph text and some help links on what this does and how to use it

there is any, since it is specific to this plugin

> And links to the format of the JSON file 

it is not supposed to be used to import info from the dashboard, this is just to export the plugin settings for backup or replication purposes

Anyway, agree that some paragraph would be helpful.

**Comment by SteveC** [comment]
Ok let's add this text (is it settings and some user data?):

You can import and export your Auth0 WordPress plugin settings and users here. This allows you to either backup the data, or to move your settings to a new WordPress instance.

**Comment by glena** [comment]
Just settings, so `You can import and export your Auth0 WordPress plugin settings here. This allows you to either backup the data, or to move your settings to a new WordPress instance.`

**Comment by SteveC** [comment]
Ok great

**Comment by glena** [comment]
![image](https://cloud.githubusercontent.com/assets/5647310/14078903/f0197d7c-f4cf-11e5-8e80-941f154f5605.png)
