### ISSUE TITLE
login box

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#177]
* Can we change the title Auth0 star at the top to a link?
* Can we change "Log in" to add some text just below like "Powered by Auth0 login plugin for wordpress" and link to the wordpress plugin URL?

<img width="438" alt="screen shot 2016-03-21 at 10 05 05 am" src="https://cloud.githubusercontent.com/assets/123912/13927149/bd9601be-ef4c-11e5-8b2f-8a33c4d54edb.png">

**Comment by SteveC** [comment]
we should do this text for free users - paid users it should go away

**Comment by glena** [comment]
I am not sure about this since:

1- this can be customized from the settings
2- users need to add attribution if they have an open source plan. Standard free users don't.
3- The auth0 logo is handled by Lock

**Comment by glena** [comment]
BTW, the star you mention here (css login issue #176) is shown only for free users

**Comment by SteveC** [comment]
so when I talked to Gonto he seemed pro on the idea of putting text there?

**Comment by glena** [comment]
@SteveC we discussed with gonto, and we are not going to change lock, but show a badge (http://auth0.github.io/auth0-oss-badges/) under it only for free users which will link to auth0.com

**Comment by glena** [comment]
Will check with design to change the text of the badge

![image](https://cloud.githubusercontent.com/assets/5647310/13956607/32586920-f028-11e5-8a72-bd18f32f9e49.png)

**Comment by SteveC** [comment]
ok closing... assuming we have it tracked somewhere that we're adding a badge instead...

**Comment by glena** [comment]
![image](https://cloud.githubusercontent.com/assets/5647310/13999539/7a892934-f11b-11e5-9e38-2a8d70da5838.png)

**Comment by SteveC** [comment]
This is awesome - where does the link go to? Is it something we can track? (on the "login powered by.." image)
