### ISSUE TITLE
Maybe trim CSS on feedback 

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#182]
To use less vertical space. Ticket here for tracking issue...

**Comment by glena** [comment]
what about this 

![image](https://cloud.githubusercontent.com/assets/5647310/14186878/e9342438-f756-11e5-8f54-fe26867473c5.png)

**Comment by SteveC** [comment]
Awesome thanks, I think it looks better but hard to see without side by side so let's just go with it
