### ISSUE TITLE
Windows Live logo

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#190]
What is Windows Live called now for login? The logo etc is from the windows 7 era on the dashboard in the plugin. Maybe auth0.com dashboard has updated...

yes it has - we should upgrade

<img width="322" alt="screen shot 2016-04-05 at 9 36 28 am" src="https://cloud.githubusercontent.com/assets/123912/14289927/e6c93d5a-fb11-11e5-8eae-51989f436596.png">

**Comment by glena** [comment]
ready for next release
