### ISSUE TITLE
Configured dict Auth0 for lock type emailcode ?

### ISSUE THREAD

**Issue by igormoura** [auth0/wp-auth0#199]
I would like to change the name of the instruction text to email. But to no avail.

```
var dict = {
  title: "Pontuali",
  headerText: "Please enter your email and password password. We will send you an email to confirm."
```

...

**Comment by glena** [comment]
there was an issue with lock not allowing you to do this, of it is not taking any text?

**Comment by joshcanhelp** [comment]
For anyone else having this issue ... the **Lock Language Dictionary** setting in **wp-admin > Auth0 > Settings > Appearance** accepts a valid JSON object so to change, say, the title, we'd use:

```js
{"title":"Pontuali"}
```

[See here](https://github.com/auth0/lock#language-dictionary-specification) for more general information about this Lock feature and [here](https://github.com/auth0/lock/blob/master/src/i18n/en.js) for all the overrides possible.
