### ISSUE TITLE
Social Login toggles are not showing on the setup page

### ISSUE THREAD

**Issue by dleeward** [auth0/wp-auth0#200]
Social Login toggles are not showing on the setup page. I'm using Firefox 45.0.2

![auth0](https://cloud.githubusercontent.com/assets/10263723/14946617/e0483710-0ff2-11e6-8115-79cfc081c6e8.PNG)

**Comment by glena** [comment]
Hi,

I am trying to repdoduce the issue but I am not able to (using ffx 46).

Is it the latest plugin version (`2.1.11`)?
Can you try cleaning your browser cache and reloading?

![image](https://cloud.githubusercontent.com/assets/5647310/14953696/761f1bc4-1042-11e6-8d2b-819d27dac35b.png)

**Comment by dleeward** [comment]
I'm on Windows, maybe that's the difference. I am using v2.1.11

**Comment by glena** [comment]
do you still have this issue with the latest release?

**Comment by joshcanhelp** [comment]
Connection configuration was removed in 3.4.0, see #357
