### ISSUE TITLE
Installer should chck to see if there are custom page templates for login and register

### ISSUE THREAD

**Issue by dleeward** [auth0/wp-auth0#201]
Installer should check to see if there are custom page templates for login and register. If there are, it should warn the admin or set them to the default.

**Comment by glena** [comment]
any idea on how to do that?

**Comment by dleeward** [comment]
I'm not a developer. Maybe something here will help? https://codex.wordpress.org/Function_Reference/get_template_directory

**Comment by joshcanhelp** [comment]
So ... wp-login.php does not use page templates at all. You can enqueue CSS or JS and use actions and filters to move things around but there isn't a "template" for it that uses `get_template_part()` or anything.
