### ISSUE TITLE
Connection doesn't require username

### ISSUE THREAD

**Issue by dleeward** [auth0/wp-auth0#202]
The "Requires Username" setting should be turned on when the database connection is created.

**Comment by dleeward** [comment]
Also, when a user enters an illegal username (containing a space), Lock highlights the field but does not give an error message indicating that you cannot use a space.

**Comment by dleeward** [comment]
Actually, spaces are not illegal in the WordPress username (login name) but the Lock widget seems to think so.

**Comment by glena** [comment]
hi @dleeward 

> The "Requires Username" setting should be turned on when the database connection is created.
if you complete the initial setup wizard, the database connection is created with `requires username` enabled.

> Also, when a user enters an illegal username (containing a space), Lock highlights the field but does not give an error message indicating that you cannot use a space.

This is not handled by the plugin, this depends on Auth0 and Lock, I am checking with the team.

**Comment by glena** [comment]
About the username validation, it is in the backlog of the team working on the lock widget, I don't have an ETA tho.

**Comment by dleeward** [comment]
> if you complete the initial setup wizard, the database connection is created with requires username enabled.

It didn't for me, but maybe I did something wrong.

**Comment by dleeward** [comment]
In https://github.com/auth0/lock/issues/375#issuecomment-217265631 @hzalaz says 

> @dleeward we are going to fix the missing message error soon (#374).
About allowing spaces in usernames, currently the Auth0 API has the following restrictions regarding usernames:

    Username can only contain alphanumeric characters and '_'.
    Username cannot have more than 15 characters.

So even if we allow spaces the server, the request to signup will fail because of this.

How are usernames with spaces imported into Auth0? Although the first 15 characters of the "nicename" might be legal in Auth0, we are still going to have issues with usernames being different between the WordPress database and the Auth0 database and the potential for duplicate usernames if only the first 15 characters are used. It appears that the native limit is 60 characters.

**Comment by dleeward** [comment]
I received an answer from @hzalaz at https://github.com/auth0/lock/issues/375 regarding this. They will not be modifying the Auth0 API to allow spaces in the username. This will definitely break the migration functionality for a subset of users since the WP API doesn't allow changing the username (although we have done it in mySQL without any issues). Using a truncated version of nicename with the hyphens converted to underscores could be an option, but the usernames will be different in WP and Auth0 and will likely cause user confusion.

Maybe you need to add code to check for duplicate usernames and illegal characters (from Auth0 standpoint) in the username and allow us to display custom messages to the user on how to resolve the issue.

**Comment by dleeward** [comment]
I also just realized that all of the WP user accounts we have generated from importing users from Facebook will fail as well. Facebook uses a 16 digit GUID and we add FB to the beginning which totals 18 digits.

**Comment by glena** [comment]
You are right about how the usernames are imported into Auth0. Is not common to have spaced in the username so we never bump into this issue.

I will check it and see how I can make it work (probably I will need to convert it into a slug) but still the length should be cut off. As hzalaz said, the Auth0 API will not be changed since we need to assure backward compatibility to our customers.

The idea of this issue was to add an error message to lock to explain what is wrong with the username.

About your specific use case, I guess you might need to update the usernames on the database or move to use just emails for login.

**Comment by dleeward** [comment]
The problem with just using emails for login is that WordPress requires a username to signup. Is there an option for Lock to display the username field for signup but not ask for it at login?

**Comment by glena** [comment]
There is a setting for that in the appearance tab:

![image](https://cloud.githubusercontent.com/assets/5647310/15081386/2f13d4fe-1399-11e6-8f04-ca9a953b1376.png)

that changes this attribute in the lock config https://auth0.com/docs/libraries/lock/customization#usernamestyle-string-

**Comment by dleeward** [comment]
It is already set for email. The issue is that Lock allows a user to enter the username which won't work for users that have illegal usernames:
![username](https://cloud.githubusercontent.com/assets/10263723/15083740/fb48d71a-139c-11e6-95ee-10700b4f02a3.PNG)
