### ISSUE TITLE
Callback URL's not working

### ISSUE THREAD

**Issue by dleeward** [auth0/wp-auth0#203]
When a logged out user tries to post, The Lock widget is called, but the user is taken back to the home page after he logs in. I've added the URL to the Allowed Callback list.

**Comment by glena** [comment]
Hi @dleeward, help me understand the scenario

> When a logged out user tries to post
how? where?

is the user redirected to `wp-login`?
if so, is the redirect_to param in the query string present?

**Comment by dleeward** [comment]
Yes, here is the string:
`http://example.com/wp-login.php?redirect_to=http%3A%2F%2Fexample.com%2Fcreate-listing%2F`

**Comment by glena** [comment]
I think it should be related to the coment I sent you on #150

**Comment by LukeAbell** [comment]
I'm having the same problem. When someone logs in or signs up from the woocommerce checkout page, they get redirected to the home page instead of the cart page.

**Comment by glena** [comment]
@LukeAbell it is not the same problem, I need to check the woocommerce integration, thx for reporting

**Comment by LukeAbell** [comment]
Thanks! Trying to get a large site launched and this is one of the last bugs unfortunately.

**Comment by dleeward** [comment]
#150 needs to be reopened unless it has been replaced by another issue.

**Comment by LukeAbell** [comment]
@glena @dleeward Any time estimate on this? Really need to get this fixed so we can launch.

**Comment by glena** [comment]
@LukeAbell it will be ready on version `3.0.0` that will be release EOW
