### ISSUE TITLE
Bug - Twitter authentication fails when user's Twitter name has non-ASCII characters

### ISSUE THREAD

**Issue by thameera** [auth0/wp-auth0#207]
Steps to reproduce:
1. Create a dummy Twitter account with a non-ASCII character(s) in the name (eg: Василь)
2. Try to sign in to WordPress using the above account.

Expected result:
User should be signed in to WP successfully.

Actual result:
Authentication fails with WordPress error "Cannot create a user with an empty login name".

**Comment by glena** [comment]
![image](https://cloud.githubusercontent.com/assets/5647310/15440851/165099b4-1eae-11e6-9326-03e049fdadc4.png)
![image](https://cloud.githubusercontent.com/assets/5647310/15440856/206184d6-1eae-11e6-8a5d-1885b7d37361.png)

could not reproduce the issue, which php version are you using?
