### ISSUE TITLE
Lock blank after signup

### ISSUE THREAD

**Issue by schamp** [auth0/wp-auth0#216]
I have signup enabled, and it works correctly, however, after the user submits the built-in email/password signup form, the widget goes blank -- there's no message about whether signup was successful or not, or instructions about what to do next:
<img width="325" alt="screen shot 2016-06-21 at 6 17 14 am" src="https://cloud.githubusercontent.com/assets/351548/16228332/051e6b08-377c-11e6-81f6-3b1731d3ffca.png">

Looking at the document elements, it appears that the entire auth0-login-form element is empty:  
<img width="1052" alt="screen shot 2016-06-21 at 6 50 40 am" src="https://cloud.githubusercontent.com/assets/351548/16228421/86863a40-377c-11e6-8929-93a2d3e56db7.png">

Is there something I must set to show a message after signup?  It is not clear to me yet whether it is a problem with the WP plugin or Lock itself.  In my perfect world, I can customize the text of that message by a parameter to the lock widget.  But I was unable to find anything about this issue in the documentation.

**Comment by glena** [comment]
mm That is weird.

Is there any js error in the console?
If you go to the logs section in the dashboard, does it shows any error? does it shows a successfull signup + login? (it shoulid be two different logs).

can you attach a har file of the whole interaction? (start capturing before you go to the signup page ultil you get the empty signup box).
Follow this to create the har file http://auth0.com/docs/har

Thx

**Comment by schamp** [comment]
No I do have a successful signup action in the log.  There is no successful login, but that is expected: I have lock configured with { loginAfterSignup: false } in the Advanced plugin Lock config setting.  If I disable that, after signup and autologin, I see:
<img width="789" alt="screen shot 2016-06-21 at 7 04 17 am" src="https://cloud.githubusercontent.com/assets/351548/16228742/683142a4-377e-11e6-9f8c-bf21f7b8c5c5.png">

I can make this work for me, but see the attached har exemplifying the problem for me:
[local.wordpress.dev-full.har.txt](https://github.com/auth0/wp-auth0/files/325814/local.wordpress.dev-full.har.txt)

**Comment by glena** [comment]
ohh makes sense now.

This is because of the `{ loginAfterSignup: false }`.

You should be able to hook to the `signup success` event (check https://auth0.com/docs/libraries/lock/events).

You can add the needed js to the `Customize the Login Widget with custom JS` field under the appearance tab.

**Comment by schamp** [comment]
Gotcha, I'll try that, thanks.

**Comment by schamp** [comment]
In case anyone is interested, I settled on this custom CSS in the 'Customize the Login Widget CSS' setting:

```css
#auth0-login-form {
  position: relative;
}

#signup-msg {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  padding: 0px 24px;
}
```

and this custom JS in the 'Customize the Login Widget with custom JS' setting:

```javascript
// called every time triggered
lock.on('signup success', function() {
   var msg = jQuery('<div id="signup-msg">You have signed up successfully.  ' +
      'Once you have verified your email address ' +
      'and an admin has activated your account, ' +
      'you will be able to log in.</div>');

  jQuery('#auth0-login-form')
    .append(msg);
});
```

**Comment by glena** [comment]
good :)
