### ISSUE TITLE
default behavior traps in verify email loop

### ISSUE THREAD

**Issue by schamp** [auth0/wp-auth0#217]
If SSO is configured and new signups are configured to require a verified email, after signup if I attempt to log into the wordpress with lock, I see the following message:
<img width="789" alt="screen shot 2016-06-21 at 7 04 17 am" src="https://cloud.githubusercontent.com/assets/351548/16233035/8a41a82a-3792-11e6-9643-0e7523fe01aa.png">

However, I am not sure that the 'login' link is correct here -- the user is already logged in to Auth0, but is prevented from continuing to the wordpress site.  However, if I select 'login', I am sent back to lock, which notices I am logged in to Auth0, and then sends me back to this screen in a loop.

If a logout link were presented instead of a login link, it would allow the user to log out of Auth0 instead of getting trapped in a loop.  There is no other obvious way to log out of the Auth0  I have a patch for this ready to go, but I saw the filter mechanism set up to allow customization of this error message.  I could implement it that way, but it seemed to me like a more sensible default might be a better solution.  Shall I submit a pull request?

**Comment by glena** [comment]
I will tackle this. The correct behaviour is to redirect to the logout endpoint before showing this message. This needs a couple of redirection, I will take care as soon as I can.

**Comment by schamp** [comment]
Excellent, thank you.

**Comment by Slapbox** [comment]
Same issue here without SSO.

**Comment by joshcanhelp** [comment]
I'm not seeing this issue occurring anymore so I'm going to close it. 

@schamp - Very belated reply here but if you're still seeing this issue, ping me here and I'll take another look.
