### ISSUE TITLE
Login Only Not Allowed

### ISSUE THREAD

**Issue by rcampbell22** [auth0/wp-auth0#234]
When using the plugin, I am unable to make it perform a 'login only' function. I have looked at a few other issues related to this (#4 and #48) but it still doesn't appear to be resolved even though these issues are closed.

When I enable the WordPress setting 'Anyone can register' then the plugin allows users who have never logged into WordPress via Auth0 to login successfully, but when this is disabled then I get the error reported in #48 (Error: Could not create user. The registration process is not available.)

What I want is to allow only users who already exist in Auth0 (their accounts were created elsewhere) to be able to log in to the site. Is this possible? I have already tried changing the 'Auto Provisioning' setting (which IMO should allow what I want) but it doesn't help.

Thanks

**Comment by glena** [comment]
I changed the behavious of the `auto provisioning` toggle to handle this use case. When `anyone can register` is disabled, `auto provisioning` will allow to create new users only on `login`.

I will be releasing the new version with this by EOW

**Comment by rcampbell22** [comment]
Great, thanks. Look forward to testing it.

**Comment by glena** [comment]
I will release `3.2.5` in a couple of hours. I am closing this one but reopen after the update if you need.

**Comment by rcampbell22** [comment]
Not sure whether this is a separate issue or not but here's my scenario.

The fix worked perfectly - now if I disable registrations and an existing Auth0 user logs in, the 'WordPress' user is created automatically.

However, I'm using another plugin on the site called 'WP Full Stripe Members' which integrates with Stripe (for payments) but also creates/uses the users in WordPress to associate to customers in Stripe. The issue is that if a WordPress user exists in the site with the same email address as a user in Auth0, when that user logs in I would like them to be 'merged' (i.e. the WordPress user 'becomes' the Auth0 user) rather than what happens currently (they get a message saying email address in use).

Is this possible? Thanks

**Comment by glena** [comment]
The users get merged only if the user is flagged as verified on Auth0. I think your used did not verified the email so the plugin by default will reject the merge since it can not trust the user. You can disable this on the plugin settings, under advanced disable `require verified emails`.

**Comment by rcampbell22** [comment]
OK, so that led me to the solution, but it wasn't quite as you describe. The user wasn't email verified, but changing the `require verified emails` setting still didn't allow them to log in (still got the message saying email address is in use). When I set `require verified emails` on, it gave the correct message (you need to verify your email).

I then verified the email in Auth0, and the user can then login immediately. It never seems to allow users to be merged if their email is not verified (which I agree with) but the message is misleading (saying the email is in use when really they need to verify so the merge can happen).

I think the workaround in my scenario is to always require verified emails (so that if they're either new or merging, it will work) but just wanted to flag the message as being a little confusing.

Thanks for the quick fix on the REAL issue though...that was a deal-breaker and we can make it work now! :)

**Comment by glena** [comment]
I wait, I mixed stuff. This happens when the user is already merged. Check if there is a button in the user profile to delete the auth0 info.

You can merge a wp user with more than one auth0 users. For example, if you use user/password and facebook this could happen
