### ISSUE TITLE
Profile data not returned in get_auth0userinfo()

### ISSUE THREAD

**Issue by terryw707** [auth0/wp-auth0#236]
It appears that wp_get_current_user() returns a WP_User object which is then passed to get_auth0userinfo() expecting an integer user_id.  This causes the get_user_meta call to fail to return $profile data.  https://github.com/auth0/wp-auth0/blob/master/WP_Auth0.php#L376

~~~~
if ( ! function_exists( 'get_auth0userinfo' ) ) {
	function get_auth0userinfo( $user_id ) {
		global $wpdb;
		$profile = get_user_meta( $user_id, $wpdb->prefix.'auth0_obj', true);
		if ($profile) {
			return WP_Auth0_Serializer::unserialize( $profile );
		}
		return false;
	}
}
if ( ! function_exists( 'get_currentauth0userinfo' ) ) {
	function get_currentauth0userinfo() {
		global $currentauth0_user;
		$current_user = wp_get_current_user();
		$currentauth0_user = get_auth0userinfo($current_user);
		
		return $currentauth0_user;
	}
}

~~~~

**Comment by glena** [comment]
Yes it is fixed on `dev`. The fix will be released by EOW

**Comment by glena** [comment]
I will release `3.2.5` in a couple of hours. I am closing this one but reopen after the update if you need.
