### ISSUE TITLE
Passwordless 

### ISSUE THREAD

**Issue by benplum** [auth0/wp-auth0#238]
When using the password-less option, `.on` is not a function of the Auth0LockPasswordless object, leading to front-end errors: 

https://github.com/auth0/wp-auth0/blob/master/templates/auth0-login-form.php#L182-L207

Not sure if this should be addressed here or in the [passwordless repo](https://github.com/auth0/lock-passwordless)?

**Comment by glena** [comment]
@benplum here is ok. Thanks for reporting, I will try to address this fix by next week

**Comment by glena** [comment]
@benplum I just pushed `3.2.6` which should fix the issue. Let me know how this works

**Comment by benplum** [comment]
Looks good to me, thanks!
