### ISSUE TITLE
Support for non-federated logout

### ISSUE THREAD

**Issue by thameera** [auth0/wp-auth0#239]
Currently the plugin supports only the federated logout using `/v2/logout?federated`.

Some social providers do not redirect the user back after logging out, so it's sometimes desirable to skip federated logout.

**Comment by joshcanhelp** [comment]
@thameera - Reviving this old one as we're refactoring both login and log out in the latest release. 

In my mind, `federated` is rarely desired and I'm not even sure if it's necessary as an option. My thoughts are to leave `federated` out completely. 

What do you think?

**Comment by thameera** [comment]
This was added after a customer request some time back. I've not seen any further requests afterwards, so maybe safe to close this.
