### ISSUE TITLE
Prompt users for email when logging in with IdP that doesn't provide one

### ISSUE THREAD

**Issue by rolodato** [auth0/wp-auth0#25]
WordPress requires all users to have both username and email, as can be seen here:

![screen shot 2014-10-10 at 10 43 21 am](https://cloud.githubusercontent.com/assets/829698/4593160/8d6a119c-5083-11e4-9d8c-c5750036250f.png)

When logging in with an identity provider that does not provide an email such as Instagram or Twitter, user creation fails with `Error: could not create user`.

A solution for this would be to prompt users for an email when signing up if the identity provider hasn't provided one.

**Comment by dleeward** [comment]
Is there a workaround yet for this issue? The link provided by @woloski no longer works.

**Comment by glena** [comment]
The plugin attempts to generate an email for those users. You might need to disable `require verified emails` in that case.

**Comment by dleeward** [comment]
Wouldn't that present a problem for matching on social logins that do use an email address?

**Comment by joshcanhelp** [comment]
Backlogged internally for the next major
