### ISSUE TITLE
Signup with email verification works oddly. How can I make this more graceful?

### ISSUE THREAD

**Issue by Slapbox** [auth0/wp-auth0#257]
![image](https://cloud.githubusercontent.com/assets/6835891/21066595/6045e18e-be34-11e6-8237-7f110531948b.png)

In the end if I verify the email and go back, I can login, but this is one of those barriers that might lose users. Is there a fix? Did I make a mistake?

Thanks for your help.

**Comment by glena** [comment]
You can disable the email verification in the plugin settings if you think this is not needed. You can also override the email verification page using this filter https://github.com/auth0/wp-auth0#render-verify-email-page
