### ISSUE TITLE
Javascript error with Auth0 lock 10 in auth0-singlelogout-handler.php

### ISSUE THREAD

**Issue by jlyon** [auth0/wp-auth0#262]
In line 8 of `auth0-singlelogout-handler.php`, `lock.$auth0` is undefined. This results in a Javascript error on all pages when logged in:
```
Uncaught TypeError: Cannot read property 'getSSOData' of undefined at HTMLDocument...
```

I believe this has something to do with a refactoring in Auth0 lock 10.x.

**Comment by joshcanhelp** [comment]
Closing as we've upgraded Lock a few times and not seeing this error.
