### ISSUE TITLE
Form not being displayed in Chrome

### ISSUE THREAD

**Issue by camilodelvasto** [auth0/wp-auth0#265]
Hey!

After configuring the plugin, I realized the form is not being displayed in Chrome. It works in Firefox and Safari, though.
See here for more details: https://auth0.com/forum/t/wp-plugin-displaying-nothing/4824

**Comment by glena** [comment]
is it public somewhere to check?
do you see any js error?

**Comment by camilodelvasto** [comment]
No, it's on my localhost. There's no js error in the console

**Comment by glena** [comment]
Can you try using a incognito session?

**Comment by camilodelvasto** [comment]
@glena wow, it worked! what's the matter?

**Comment by glena** [comment]
if you are logged in, it does not show the widget.

**Comment by camilodelvasto** [comment]
Ok, that explains a lot of things! Thanks!
