### ISSUE TITLE
Different redirection URL if login/signUp

### ISSUE THREAD

**Issue by camilodelvasto** [auth0/wp-auth0#266]
Hi, I was wondering if it would be possible to have a different redirection URL for users who are signing up and for returning users that are logging in...

I tried to use two different pop-up widgets, one for signup and one for login, but only the first widget button trigger will be displayed, so I couldn't go this route. Any other ideas? Thanks

**Comment by glena** [comment]
You can use this action https://github.com/auth0/wp-auth0#user-login-action
and use the `$is_new` parameter to take de decision to redirect to a particular page.
