### ISSUE TITLE
Errors while editing profile

### ISSUE THREAD

**Issue by camilodelvasto** [auth0/wp-auth0#267]
I'm getting this error while trying to update the user profile:
```
Notice: Undefined property: stdClass::$ID in /Users/camilodelvasto/Documents/nolte/proposal/wp-content/plugins/auth0/lib/WP_Auth0_EditProfile.php on line 280

Warning: Cannot modify header information - headers already sent by (output started at /Users/camilodelvasto/Documents/nolte/proposal/wp-content/plugins/auth0/lib/WP_Auth0_EditProfile.php:280) in /Users/camilodelvasto/Documents/nolte/proposal/wp-includes/pluggable.php on line 1179
```
Is this something anybody else is experiencing?

**Comment by camilodelvasto** [comment]
Hey there, just wondering if somebody could help me figure out the problem...

Here's the code for the relevant WP_Auth0_EditProfile.php part:
```
	public function override_email_update() {
		global $wpdb;
		global $errors;

		if ( ! is_object( $errors ) ) {
			$errors = new WP_Error();
		}

		$current_user = get_currentauth0user();
		$user_profile = $current_user->auth0_obj;

		$app_token = $this->a0_options->get( 'auth0_app_token' );;

		if ( !$app_token ) {
			return;
		}

		// Line 280 comes next, which is failing
		if ( $current_user->ID != $_POST['user_id'] ) {
			return false;
		}
```
What I'm seeing is that the returned object for $current_user doesn't have an `ID` property, hence, the error is being thrown.

Is this something specific to my plugin configuration? Or is this a bug? Here's a link to the returned $current_user object: https://d17oy1vhnax1f7.cloudfront.net/items/1H3T0C17320g3z3P0I0M/%5B40a70158b035201c91d8df8e661af760%5D_Image%25202017-01-24%2520at%252012.15.22%2520PM.png?v=c8a1484c

I really appreciate if you guys could have a look at it, thanks!

**Comment by glena** [comment]
Sorry for the delay, I lost track of this issue.

can you do a quick change?

replaces this two lines
```php
		$current_user = get_currentauth0user();
		$user_profile = $current_user->auth0_obj;
``` 

by

```php
$current_user = wp_get_current_user();
$user_profile =  get_currentauth0userinfo();
```

**Comment by camilodelvasto** [comment]
That worked! @glena 

Now, what's next? :)

**Comment by glena** [comment]
if that is working fine, I will do the change and release a patch this week as soon as I have some free time.

Works for you?

**Comment by camilodelvasto** [comment]
Sounds great, thanks a lot! @glena

**Comment by glena** [comment]
Relesed as `3.2.15`
