### ISSUE TITLE
oauth2-client-configuration error

### ISSUE THREAD

**Issue by hilalh** [auth0/wp-auth0#276]
Hello, I have my WordPress setup on Heroku using https://github.com/xyu/heroku-wp as my template. I've been getting this error whenever I am trying to go through the social setup wizard
![image](https://cloud.githubusercontent.com/assets/3894104/22180883/c4fef6b8-e032-11e6-9965-e1255a72fbcb.png)

**Comment by glena** [comment]
Hi @hilalh 

are permalinks working properly?
can you try to go to the permalinks configuration and use one that is not the default with GET params, this way wordpress will push the rewrite configurations.

**Comment by glena** [comment]
Also, I see this template is using Nginx. It might be something related to that. The plugin declares some custom routes, `/.well-known/oauth2-client-configuration` is one of them.

**Comment by glena** [comment]
I tried to repro but I cannot installe it, I am having this error `wp: command not found`.

**Comment by hilalh** [comment]
I suspect Nginx as well but I couldn't get to the settings of it through the repo I used.
I changed the permalinks to one of the other options, but I get the same error.

**Comment by hilalh** [comment]
When I try to setup it manually (no internet connection) everything goes well until the migration stage of the admin user. When I am asked to choose a password I get the following error (top one only)

**Comment by hilalh** [comment]
![image](https://cloud.githubusercontent.com/assets/3894104/22309449/2482dd96-e300-11e6-87ac-8c8b7fdf15c0.png)

**Comment by glena** [comment]
That is a real bug :P

I will try to take a look tomorrow.

In the meantime, can you check if there is any connection created by the plugin (it should be named `DB-` + your site name)

Also, can you share your account name?

**Comment by hilalh** [comment]
I don't have that type of connection. I only have the default "User-Password-Authentication"

**Comment by glena** [comment]
do the following, go to the configuration under the basic tab, and make sure there is no client_id configured. if there is one, delete and save and try again

**Comment by hilalh** [comment]
That worked out! Make sure to include this in the documentation as it could be confusing. I deleted both the client secret and client id and went through the manual wizard again.

**Comment by glena** [comment]
The thing is that when the client_id is configures, it assumes you are trying to update the api token, but I agree it should be more explicit. 

Thank you for the feedback and sorry for the trouble.
