### ISSUE TITLE
We need to update the ips authorized to call the migration endpoint for US region

### ISSUE THREAD

**Issue by glena** [auth0/wp-auth0#284]
```38.91.154.99, 54.221.228.15, 54.183.64.135, 54.67.77.38, 54.67.15.170, 54.183.204.205, 54.173.21.107, 54.85.173.28, 35.167.74.121, 35.160.3.103, 35.166.202.113, 35.165.143.35, 35.167.53.126, 35.167.33.107, 52.14.40.253, 52.14.38.78, 52.14.17.114, 52.71.209.77, 34.195.142.251, 52.200.94.42.```

https://github.com/auth0/wp-auth0/blob/7f6c43dad23e3703d63555febbc309c49a53c4b8/lib/WP_Auth0_Ip_Check.php#L5

**Comment by joshcanhelp** [comment]
@glena - Still relevant? Current list is here:

https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_Ip_Check.php#L5

Looks like `54.221.228.15` is on the list above but not in `WP_Auth0_Ip_Check`
