### ISSUE TITLE
3.2.16 throws errors if Error Log is empty

### ISSUE THREAD

**Issue by mostekcm** [auth0/wp-auth0#285]
Two things need to be fixed for this.

1) wp-content/plugins/auth0/lib/WP_Auth0_ErrorManager.php
Add: 
$log = get_option('auth0_error_log', array());
         if (!is_array($log)) {
             $log = array();
          }

For some reason the $log is returning false instead of array().

2) auth0/templates/auth0-error-log.php
Add else condition after check for empty around the foreach.  Same reason.  Returning boolean instead of array when empty.

**Comment by cocojoe** [comment]
@mostekcm this still relevant?
