### ISSUE TITLE
Direct POST to http(s)://site.com/wp-login.php?action=register bypasses Auth0

### ISSUE THREAD

**Issue by mostekcm** [auth0/wp-auth0#286]
If you are using auth0 to manage registration, you get the login widget if you go to site/wp-login.php?action=register (as expected).  However if someone just does a POST to site/wp-login.php?action=register with a body of user_name and user_password set, it will actually register those users.  Bypassing auth0 entirely.  To shut this down, I turned off "allow users to register" in my Settings->General for the whole site, but then had to manually go to my database connection and turn it on.  I remember this not working in the past, but I was actually able to signup a new user doing this (perhaps because I am migrating users to my auth0 database?).  Anyway seems like something we should handle one way or another.

**Comment by joshcanhelp** [comment]
Workaround: 

https://wordpress.org/support/topic/creating-registration-restriction/
