### ISSUE TITLE
Make base64 encoding for secret false by default

### ISSUE THREAD

**Issue by dafortune** [auth0/wp-auth0#288]
This is also the default in auth0, they should match

**Comment by mostekcm** [comment]
We are actually looking at pulling the information from the tenant instead.  We made it true by default to not break legacy, but it should be false by default for new stuff, so the best answer is to just query the management API to get the right value and not have it be settable.  Or at least set it up correctly the first time.

**Comment by joshcanhelp** [comment]
Looks like this has been the case since 3.2.21:

https://github.com/auth0/wp-auth0/commit/d69a3fa85f57b27ab330ff7ebb8c5c2dd32d1961#diff-894052ccee58b2c7d7f46aca8335a672
