### ISSUE TITLE
redirect_login should still work if base64 encoded secret is wrong, it should just log a warning

### ISSUE THREAD

**Issue by mostekcm** [auth0/wp-auth0#291]
We should be able to catch the bad decode and just grab the information from user_info.  This will cause https://github.com/auth0/wp-auth0/issues/271 to resurface, but that is less of a concern than total failed logins.

**Comment by glena** [comment]
we should not do this. We should in fact strongly validate this (mostly for implicit flow but for code too)

**Comment by mostekcm** [comment]
We should talk this through.  I'm not recommending we don't validate the token, I think there are better ways to do this that don't break people who have that setting wrong.  It used to work for login to have it wrong because we weren't trying to decode it.  We were using the user info endpoint so we didn't need to.

The other option is for us to have some sort of wizard or warning when you update so that people know to go and check.  

Or we need to back out the change and do a major rev since it is not truly backward compatible.

**Comment by glena** [comment]
Management API returns a property with that, we should be able to create a migration to check that and should do the trick

**Comment by joshcanhelp** [comment]
I don't think this is still and issue but please re-open if so.
