### ISSUE TITLE
Is there a way to use Refresh Tokens and Wordpress?

### ISSUE THREAD

**Issue by cwhittl** [auth0/wp-auth0#296]
Right now I'm using a users JWT Token to call my custom APIs and it's working nice.  The only issue is that when the token expires I have to kick the user out of the site and have them login again.   Which is not the best user experience.

I've looked at options to use the refresh token but it doesn't look like there is a vehicle or documentation of it for Wordpress.

Any help?
Thanks

**Comment by glena** [comment]
The best way to do that is to use the `user-login-action` hook. We can add the refresh token there if it comes from auth0 so you can store it and use it when you need it.  https://github.com/auth0/wp-auth0#user-login-action

**Comment by cwhittl** [comment]
That would be great, I'm using that action now to store the JWT Token.

**Comment by kostenickj** [comment]
any update on this?

**Comment by joshcanhelp** [comment]
Sorry for the delay folks. I can squeeze this into the upcoming release, will have a PR tomorrow.

**Comment by joshcanhelp** [comment]
Fixed in #456, merged into `dev` and ready for release 👍
