### ISSUE TITLE
Flexibility in the connection used for auto login?

### ISSUE THREAD

**Issue by waded** [auth0/wp-auth0#298]
We are using WordPress as a CMS in integration with a 2nd system that has already authenticated a user through Auth0. When the 2nd system sends users to WordPress we ideally want users to sign into WordPress using the connection previously used. The system knows what that connection is, and could use that to build an appropriate Wordpress URL... for example it could pass ?connection=whateverConnectionIsIntended to wp_login.php as a hint if such a parameter was supported.

It appears wp-auth0 settings auto_login:0 and auto_login_method:someConnectionName can be used to force a single connection but there is no way the connection can be forced otherwise. Correct?

If correct, what can we do to make a dynamic connection set by URL possible? Is such work planned, or would a PR be accepted to add such a thing?

I previously asked this question at https://auth0.com/forum/t/triggering-forcing-connection-for-wordpress-by-url/5518 and Auth0 employee jmangelo sent me here.

**Comment by glena** [comment]
why dont you enable SSO in wordpress? that should do the trick

**Comment by waded** [comment]
@glena We do have SSO enabled on the WordPress SP side (I presume you mean the "sso" exported setting; this value is "1") but enabling the Auth0 side of this ("Use Auth0 instead of the IdP to do Single Sign On" on the client representing WordPress) is not palatable for our connections, as moves control of authorization timeout/revocation from the actual IdP to Auth0. We prefer being able to specify connection/tenant on the WordPress SP URL when it's known, as that allows the identity provider to be involved each time authentication is required, without offering the user the Lock experience to select a connection when there's only one relevant connection.

Do you have another option?

**Comment by glena** [comment]
I can add a filter for you to override the connections by code, would that work?

**Comment by waded** [comment]
@glena If I understand correctly, the filter would allow users of the plugin to customize how the plugin infers connection from URL (a ?connection parameter or whatever makes most sense), and the plugin can manage the intersection of a connection being specified with the existing auto_login/auto_login_method settings. If so, that would work for us.

**Comment by glena** [comment]
kind of, the filter will give you the connection configured and you will be able to change it. Then whatever you return from the filter will be used to build the url where the user is redirected intead of `manage the intersection of a connection being specified`.

Basically, you will be able to override the connection name

**Comment by waded** [comment]
@glena I think that would work well. Is this something you/Auth0 already had in mind and want to deliver and have us test, or do you want us (on our own schedule) to try to provide a PR?

**Comment by glena** [comment]
This should do the trick https://github.com/auth0/wp-auth0#customize-autologin-connection
