### ISSUE TITLE
Spam Protection

### ISSUE THREAD

**Issue by draoZA** [auth0/wp-auth0#301]
Hi,
would be a nice feature if there is some kind of spam protection. as soon as I enable user registrations, I get spammed with new bot accounts. Typically I would you a plugin leveraging reCaptcha to prevent this. But this wouldn't work in combination with lock?

Rgds
Lars

**Comment by glena** [comment]
To make recaptcha work with lock, there is work needed on lock and the auth0 server side of thing so it is not that trivial.

I have to say it is in the backlog but wont be ready in the short term.
