### ISSUE TITLE
Make state work after SSO login

### ISSUE THREAD

**Issue by jlyon** [auth0/wp-auth0#302]
The docs on https://auth0.com/docs/sso/regular-web-apps-sso recommend using the state querystring param to pass the redirect destinatiion after a success SSO login.

Example url:
```
https://xxx.auth0.com/authorize?client_id=xxx&redirect_uri=http://localhost:8080/index.php?auth0=1&response_type=code&state=http://localhost:8080/wp-admin/edit.php?post_type=page
```

It looks like most of this logic is already in `redirect_login()`, but it needs to be slightly re-worked.

**Comment by joshcanhelp** [comment]
Several changes to the login flow should correct this in 3.6.0. If you're still having issues after the release, post your reproducing steps and I'll gladly take a look 👍
