### ISSUE TITLE
"https://" prefix not used properly during Quick Setup, breaks plugin installation

### ISSUE THREAD

**Issue by Kirill-TechHub** [auth0/wp-auth0#304]
I am using Wordpress Version 4.7.3, trying to install the official Auth0 plugin on it for the first time. 

The Wordpress plugin sends an incorrect URL of the site in the client_id parameter when using the Quick Setup wizard. My site is using SSL, but the URL sent by the Quick Setup wizard began with the "http://" protocol instead of "https://", which resulted in an Auth0 error page saying something about an unsupported URL (sorry, I do not remember the exact message). 

I tracked this down to the built-in WP function home_url(), which sometimes returned the URL incorrectly (not sure why, apparently it happens to sites behind load balancers). 

I fixed this by specifically forcing the URL to be constructed with "https://" if is_ssl() returns true. For example, all instances of "home_url()" in the plugin became "home_url(null, is_ssl()?'https':null)". All "get_bloginfo('url')" instances had to be replaced with "home_url(null, is_ssl()?'https':null)" too. 

It's kind of a crude fix, but it works. Maybe you can come up with a cleaner solution in the plugin.

**Comment by joshcanhelp** [comment]
PR #360 switched out `home_url()` for `site_url()` in a number of cases but I don't know if that will address this particular issue. If your home_url and site_url are both set to SSL, then those two functions should not be returning anything besides the SSL version. I'm not sure what more the plugin could do than rely on WordPress to generate the correct protocol.
