### ISSUE TITLE
Outdated instructions about Mgmt API token generator

### ISSUE THREAD

**Issue by Annyv2** [auth0/wp-auth0#307]
The instructions about how to generate an API token redirect to https://auth0.com/docs/api/management/v2 but there's no token generator there anymore. 

![image](https://cloud.githubusercontent.com/assets/5016479/24958970/7af3a48a-1f91-11e7-8ec5-78aa913ac0b8.png)

**Comment by joshcanhelp** [comment]
Thanks @Annyv2 !
