### ISSUE TITLE
French translation  : html characters

### ISSUE THREAD

**Issue by gatelli** [auth0/wp-auth0#309]
1/ the welcome text in french is "Bienvenue USERNAME&nbsp;!" with the &nbsp; character 
2/ the sentence below the login popup "Login with Wordpress username" is not translated.

**Comment by joshcanhelp** [comment]
@gatelli - I know this is a really old issue but the translation is being added in the next release. If you're still having an issue here, can you clarify #1 above? I'm not sure what the welcome text you're referring to is. 

Thank you!

**Comment by joshcanhelp** [comment]
@gatelli - found the one you were talking about, both are merged into the `dev` branch and being tested for release so I'll close this one.
