### ISSUE TITLE
Session_start warnings

### ISSUE THREAD

**Issue by thanhvuong** [auth0/wp-auth0#31]
( ! ) Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /home/thanh/dev/site/local_dev_wp/wp-content/plugins/auth0/WP_Auth0.php on line 569

( ! ) Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/thanh/dev/site/local_dev_wp/wp-content/plugins/auth0/WP_Auth0.php:569) in /home/thanh/dev/site/local_dev_wp/wp-content/plugins/auth0/WP_Auth0.php on line 569

**Comment by glena** [comment]
Hi @thanhvuong, are you still experimenting this issues with the last releases?

**Comment by glena** [comment]
It should be fixed. Feel free to open a new one if you experience this issue again.
