### ISSUE TITLE
400 error during Setup Wizard after reinstalling plugin (re-using same tenant)

### ISSUE THREAD

**Issue by rdowinton** [auth0/wp-auth0#314]
If you install the plugin and connect it with a particular tenant, and then reinstall it, the following error occurs during the Setup Wizard using the default settings:

```
WP_Auth0_Api_Client::create_user    N/A    {"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type string but found type null' on property connection (The connection the user belongs to).","errorCode":"invalid_body"}
```

This seems to be caused by the `Users Migration` option being disabled after reinstalling (it's usually enabled by default). If you enable it, you get an error:

`There was an error enabling your custom database. Check how to do it manually HERE.`

However, if you try it again, you can now go through the Setup WIzard successfully. You don't need to update the connection manually in the Auth0 dashboard as described in the `Users Migration` option either.

I'm not sure why the migration is disabled by default during subsequent installs, but it would be good to make the cause of this problem more clear to users.

**Comment by joshcanhelp** [comment]
Backlogging internally with #408 for a future release.
