### ISSUE TITLE
Resetting password via WordPress (not Auth0) doesn't apply changes

### ISSUE THREAD

**Issue by rdowinton** [auth0/wp-auth0#315]
If you reset your password via the original WordPress login instead of through Lock, you can set your password via the link you receive, but the changes aren't applied on the Auth0 side.

**Comment by joshcanhelp** [comment]
Release 3.5.0 (#373) should take care of this for non-implicit users. We do still have a UX issue, though, where passwords that don't conform to the password policy in place on the connection will not be saved. There's not any indication of this as all. I'll create a new issue for that, though.
