### ISSUE TITLE
Unable to save migration IPs whitelist

### ISSUE THREAD

**Issue by rdowinton** [auth0/wp-auth0#320]
Steps to reproduce:

1. Go into the Advanced settings of the plugin.
2. Input any value (including the latest whitelist from the Custom database tab in your database # settings in Auth0, that should be valid) into the Migration IPs whitelist.
3. Click Save Changes.
4. You'll get a message indicating the settings were saved, but the IPs whitelist remains empty.

Looking at [the code](https://github.com/auth0/wp-auth0/blob/51aaaecaff9b178ac523f284b98c231a0ee7f748/lib/admin/WP_Auth0_Admin_Advanced.php#L459), this appear to be because `$old_options` are being used instead of `$input`. Judging by the commit history it has always been this way.

**Comment by cocojoe** [comment]
Feel free to write a PR for these kind of issues 😄
