### ISSUE TITLE
Uninstall doesn't remove all Auth0 database plugin entries

### ISSUE THREAD

**Issue by cocojoe** [auth0/wp-auth0#322]
Uninstalled plugin, noticed a few DB entries are not removed.

<img width="930" alt="screen shot 2017-06-22 at 22 52 13" src="https://user-images.githubusercontent.com/928115/27457787-e286fa2c-579d-11e7-8239-177d131f7278.png">

**Comment by joshcanhelp** [comment]
Also reported here, 4th bullet down:

https://wordpress.org/support/topic/auth0-great-idea-plagued-by-plugin-problems/ 

Here are the options that aren't being removed:

![screenshot 2018-01-29 09 45 24](https://user-images.githubusercontent.com/855223/35525444-56f76778-04d9-11e8-9941-6480be36849d.png)

Nothing that would prevent a re-install but the error log persists, which might be confusing. 

Simple fix, assigned for next minor release.
