### ISSUE TITLE
Use WordPress built in filter for redirection after login

### ISSUE THREAD

**Issue by delmicio** [auth0/wp-auth0#330]
I've tried two different plugins to redirect based on users roles, but none is working.
I'm setting to empty Auth0 redirect url but it seems that keeps putting my domain as default.

https://github.com/marcelotorres/redirect-after-login
This plugin uses a wordpress filter to redirect.

`add_filter("login_redirect", "redirect_after_login_per_role", 10, 3);``

**Comment by talamihg** [comment]
Whatever happened to this issue? I am also having this problem and would like to use WordPress default functionality, 'login_redirect' filter and hook.
