### ISSUE TITLE
SSO disabled, Single Logout enabled causes users to get logged out automatically a few seconds after logging in

### ISSUE THREAD

**Issue by idpaterson** [auth0/wp-auth0#336]
Customers have reported an inability to log in to WooCommerce, getting stuck in a loop where after logging in their My Account page is displayed briefly before being redirected back to the log in page. We were able to duplicate this behavior with both the Auth0 *Sign in as user* feature and the WordPress *User Switching* plugin.

I disabled the Single Logout feature and now the user remains logged in as expected. We have not used SSO for quite some time since this plugin is incompatible with SSO for non-WordPress users. 

I cannot verify whether the combination of SSO off and Single Logout on is exactly the cause of this problem but the code suggests that it may be. If Single Logout is only meant to work when SSO is enabled it might be beneficial to prevent selection of the former when the latter is disabled.

The behavior described above may be caused by [auth0-singlelogout-handler.php](https://github.com/auth0/wp-auth0/blob/c71fbcf1cd6a1cb4234d183d11430a224f943c66/templates/auth0-singlelogout-handler.php) which after the DOM loads redirects to the logout page apparently if there is no SSO data.

**Comment by joshcanhelp** [comment]
Fixed in #466, merged into `dev` and ready for release 👍
