### ISSUE TITLE
Remove connections interface

### ISSUE THREAD

**Issue by cocojoe** [auth0/wp-auth0#338]
WIP to discuss removing the connections interface as greater functionality is provided in the Auth0 dashboard and does not make much sense to replicate it to a lesser degree.

There are also related fields and features that should be removed during this process, the aim is to list them here and create an action list from this.

I think the connections tab in `Settings` should link to Auth0 dashboard. During the Setup process it should not be displayed at all and this step skipped.  I have tried this and it worked just fine on a clean install.

**Comment by joshcanhelp** [comment]
@cocojoe - Looks like this was removed already. Can you confirm and close if so?

**Comment by cocojoe** [comment]
Confirmed as of 3.4.0
