### ISSUE TITLE
Usage with headless Wordpress

### ISSUE THREAD

**Issue by jeroneemou** [auth0/wp-auth0#341]
When using Wordpress as headless CMS with different rendering app. You have to use different site address in settings like:
<img width="600" alt="screen shot 2017-08-23 at 09 43 14" src="https://user-images.githubusercontent.com/2467722/29604361-893d333a-87e7-11e7-9c24-e16bfef73202.png">

What this causes is when Auth0 plugin tries to callback with `https://mypage.com/index.php?auth0=1` it will end up on totally different site. 

Solution is to replace usage of `home_url()` with original WP instance url leading to https://cms.mypage.com/index.php?auth0=1`.
And I think I have found the place `WP_Auth0_Lock10_Options::get_code_callback_url()`.

Also might be worth it to focus on usage of `home_url` in general, because afaik `site_url` is better way to go?
Found good answer: https://wordpress.stackexchange.com/a/50605

Cheers

**Comment by jeroneemou** [comment]
Any feedback?!

**Comment by joshcanhelp** [comment]
@jeroneemou - Apologies for the delay here! I'm going to respond in your pull request. In short: you're right and we'll get it in there ASAP.

**Comment by joshcanhelp** [comment]
Thanks @jeroneemou!
