### ISSUE TITLE
Cannot update username for users

### ISSUE THREAD

**Issue by RoopaJain** [auth0/wp-auth0#343]
Error Response Code: 400
Error Response Messages: Cannot update username for users without an username already set.

Im not able to update the username, for bulk imported users in Auth0. 
Steps:
       1. created users by using bulk import API.
       2. For these users, I can update other user-profile attributes (like email, password etc..) .
       3.But, When I tried updating username attribute for that particular user. It throws 400 error with above said messge.
              
ThankYou

**Comment by gliderjockey** [comment]
I'm getting this error as well. Any update? Thanks.

**Comment by rothfels** [comment]
Same here. This seems like the right API to backfill data on a user profile if you initially only require email/password on signup but later require username.

**Comment by rothfels** [comment]
There's a discussion opened here, I think Auth0 prefers that forum to GH issues: https://community.auth0.com/questions/9713/cannot-update-username-for-users-without-an-userna

**Comment by joshcanhelp** [comment]
Backlogging this internally for a future release.
