### ISSUE TITLE
Provide Resend verification email only for DB connections

### ISSUE THREAD

**Issue by nicosabena** [auth0/wp-auth0#345]
AD/LDAP connections (and maybe others) can have unverified email addresses, but the verify email action only works for DB connections. So the [link to **Resend verification email**](https://github.com/auth0/wp-auth0/blob/7f6c43dad23e3703d63555febbc309c49a53c4b8/templates/verify-email.php) should only be shown to users coming from a DB connection. 

API v1's `send_verification_email` does not check that, but the link sent by email will cause an error when the user tries to use it.

**Comment by joshcanhelp** [comment]
@nicosabena - I'll suppress that link on our end. It sounds like that should be added to the job API request, if possible, like "email verification not possible" ... which it actually looks like it does already:

https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

I'll get this into the next release.

**Comment by joshcanhelp** [comment]
Fixed in #447 and merged into `dev`
