### ISSUE TITLE
Enhancement: Hook to allow authenticated user to map to existing WP user w/o storing any additional info

### ISSUE THREAD

**Issue by waded** [auth0/wp-auth0#347]
In our CMS scenario it is not desirable to store any information about users in the WP database. It is sufficient to know the user is authenticated by the trusted Auth0 account/connection; we don't need to retain any information at WP beyond that.

So, for our usage, we'd like to see a provided hook to completely circumvent creation/modification of user information in the WP database... rather, given the incoming userinfo, the hook implementation chooses an existing WP user, or denies access by choosing no existing WP user, and that's it. 

For example, an implementation of the hook might map an incoming role claim in the userinfo to an existing WP user representing that role. A different implementation might map the incoming email claim to an existing WP user with that email, denying authorization to any user that cannot be found.

On first glance it appears auth0_get_wp_user_handler explained in README.md can serve this purpose... but it does not circumvent updating the WP user. The user's name, email, etc. become updated in WP based on the userinfo, and email address field may collide.

If there IS some way to do this with existing hooks, it may be a helpful scenario to explain in README.

Please let us know how we can help!

**Comment by joshcanhelp** [comment]
@waded - Thanks for this request and apologies for the delayed response. 

We definitely want clear and useful actions/filters everywhere we can to make extending this plugin as simple as possible. That said, I want to avoid adding anything that's too much of an edge case so we don't create extra work documenting, testing, etc. and anything that requires re-thinking the login process too much. 

So, let me quickly point you to a few places in the code where user data is created/changed and maybe you can put together a pull request with the actions/filters that would be helpful. 

If the user exists, this is where their meta data is modified during login:

https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_LoginManager.php#L457

https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_LoginManager.php#L464

I could see a simple filter here like `auth0_login_should_update_user` or thereabouts, just a boolean return maybe?

The part where users are created might be a little harder to get right but it's here:

https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_LoginManager.php#L472

Maybe another filter for `auth0_login_should_create`, boolean also, which would skip user creation and run whatever other processes needed?

Let me know if you need any help with the PR process in general. We're just starting work on the next minor release so if this is low impact, we'll try to include it. 

Thanks!
