### ISSUE TITLE
API token expires causing update_user to fail

### ISSUE THREAD

**Issue by rdowinton** [auth0/wp-auth0#348]
The management API token seems to expire some time after installing the plugin. 

The result is that if a user updates their email address in their profile, it changes on the WordPress side but not the Auth0 side. They can still login via Auth0 with their old email address, and this then reverts the email address in WordPress.

Side note: this is also incorrectly logged as `update_users` instead of `update_user`.

**Comment by joshcanhelp** [comment]
@rdowinton - Release 3.5.0 (#373) should take care of this for non-implicit users. Please test and close this if we're good to go here. Thanks!
