### ISSUE TITLE
Add fallback URL to log in with WP credentials even after disabling WP login

### ISSUE THREAD

**Issue by rolodato** [auth0/wp-auth0#35]
The "disable WordPress login" option should only be cosmetic, and a fallback URL should be provided to always be able to log in with WordPress credentials. As an example, Zendesk does this when enabling SSO by sending a fallback URL by email to prevent locking oneself out from their account.

Manually deleting stuff through FTP or SSH is not fun :)

**Comment by glena** [comment]
Right now it is using this url ```.../wp-login.php?wle``` to access to the WP login. This URL is available only when the WP login is enabled. Do you want to remove this restriction or do you prefer to create a new URL for this (maybe .../wp-login.php?wp-login)

**Comment by rolodato** [comment]
Yes, I think removing the restriction will be fine. Changing the URL would
just break the existing one :)

**Comment by glena** [comment]
ready on PR #36

**Comment by glena** [comment]
The URL to access the WP login is ```/wp-login.php?wle```
