### ISSUE TITLE
redirect_to - state not being decoded because of base64 padding in URI

### ISSUE THREAD

**Issue by renrizzolo** [auth0/wp-auth0#359]
Hi, I'm having a problem where redirect urls are not working.

Sometimes base64_encode uses (one or more) = signs at the end to pad the string if it isn't a multiple of 4.

in the `auth0-login-form[-lock10]` template, the base64 string of the state is taken from window.location.hash, which is encdoded, i.e the = sign becomes %3D

In this case, WP_Auth0_LoginManager - `$stateFromGet = json_decode( base64_decode( $state ) );` can't be decoded. So the redirect_url can't be taken from the state, and will default to the domain root.

My fix is just adding `decodeURIComponent` to the post function:
```
post('<?php echo home_url( '/index.php?auth0=implicit' ); ?>', {
            token:data.id_token,
            state:decodeURIComponent(data.state)
          }, 'POST');
        }
``` 

Not sure if there's a better way to get around it?

**Comment by joshcanhelp** [comment]
@renrizzolo - Thanks for the report on this. I see what you're saying here and see the same URL encoding on my end as well. That said, the redirect still seems to work fine for me, even without using `decodeURIComponent` so I want to clarify what problem you're having. 

First, it looks like you've got "Auth0 Implicit flow" turned on and "Login redirection URL" set as something other than your `home_url()`, correct?

When you go to wp-login.php with the above settings and log in, you're not going to the URL you indicated in the setting above, but to your home URL, is that right? 

Thank you!

**Comment by renrizzolo** [comment]
@joshcanhelp I have Implicit flow on, but my redirect url is the default (home url). 
If I set a different url for "Login redirection URL", it does take me there after login.

Without decoding, site.com/some-page-with-login takes me to the home url (or the url set in "Login redirection URL", rather than site.com/some-page-with-login.

I am printing out the state in the `get_state_obj()` function and can see the redirect_to is site.com/some-page-with-login.

To be honest the redirects were working fine a couple of months ago. I'm not sure what might have changed. (I've tried with a clean theme and previous versions of the plugin with the same results).

Ok so following where that js post function leads: `WP_Auth0_LoginManager.php implicit_login()`.
`stateFromGet = json_decode( base64_decode( $_POST['state'] ) );` returns nothing. 

I tried erroring out just `base64_decode( $_POST['state'] )`, which gives me the json string **with a 7 on the end**. So that is why json_decode is failing on the state and coming up empty. Can't say I understand why that's happening.

I've tried various things like doing a jquery ajax post with headers set to `'Content-Type' : 'application/x-www-form-urlencoded; charset=UTF-8'`, but the $_POST is still not being urldecoded. I'm pretty sure $_POST, $_GET and $_REQUEST super globals should be automatically urldecoded by php.

However, the ajax post above does return the html of the correct redirect_to url. Not sure what the make of that.

----
Does it make more sense to do `$stateFromGet = json_decode( base64_decode( urldecode( $_POST['state'] ) ) );` rather than decoding on the client side?

**Comment by joshcanhelp** [comment]
@renrizzolo - Thanks again! 

So, let me confirm again here. You've got a shortcode `[auth0]` on a page like site.com/some-page-with-login and you want folks to end up on that same page when they login, correct?

Testing that on my end, if I leave the `redirect_to` attribute off of the shortcode, it will what I described above. If I try sending it to another page, though, I get sent to home_url, so that definitely needs to be addressed.

Give that a try and let me know if it works. I'll leave this issue open to take a look at the malfunctioning `redirect_to`.

**Comment by renrizzolo** [comment]
@joshcanhelp 
Aha! 
I'm using WP Job Manager, and this specific problem is when a user presses Post a Listing, and isn't logged in, it shows a sign in page. 
So what I was doing was filtering the output of that sign in page, hiding the sign in button and adding `do_shortcode(["auth0"]);`. Had completely forgot about that and the fact you can add the redirect_to parameter to the shortcode.

So adding redirect_to wherever I'm using the shortcode works without my fix.

Thanks!

**Comment by joshcanhelp** [comment]
@renrizzolo - Thanks for checking back in with that! I'm going to just double-check the redirect attribute on my end (didn't seem to be working when I tested quickly) and makes sure.

**Comment by joshcanhelp** [comment]
Just tested out the `redirect_to` shortcode attribute and it works fine.
