### ISSUE TITLE
Cant login with Auth0

### ISSUE THREAD

**Issue by jsargent7089** [auth0/wp-auth0#369]
Login Error
There was a problem with your log in This account does not have an email associated, as required by your site administrator.

Error log

{"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
--

01/23/2018 17:30:07 | WP_Auth0_Api_Client::search_connection | N/A | {"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
-- | -- | -- | --
01/23/2018 17:30:06 | WP_Auth0_Api_Client::delete_rule | N/A | {"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
01/23/2018 17:28:38 | WP_Auth0_Api_Client::search_connection | N/A | {"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
01/18/2018 04:14:25 | init_auth0_oauth/token | invalid_grant | Invalid authorization code
01/16/2018 23:57:51 | init_auth0_oauth/token | invalid_grant | Invalid authorization code
01/14/2018 23:16:01 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:14:06 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:13:27 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:13:20 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:13:15 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:13:13 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:13:09 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:13:00 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:12:58 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:12:56 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:12:55 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:12:52 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:12:50 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:12:48 | implicit_login | 0 | Wrong number of segments
01/14/2018 23:12:15 | init_auth0_oauth/token | invalid_grant | Invalid authorization code

**Comment by jsargent7089** [comment]
Error Log From Auth0




Success Exchange | Authorization Code for Access Token | 6 minutes ago |   | Website
  | Success cross origin authentication | jsargent | 6 minutes ago | Username-Password-Authentication |  
  | Success Exchange | Authorization Code for Access Token | 9 minutes ago |   | Website
  | Success cross origin authentication | jsargent | 9 minutes ago | Username-Password-Authentication |  
  | Success Exchange | Authorization Code for Access Token | 13 minutes ago |   | Website
  | Success cross origin authentication | jsargent | 13 minutes ago | Username-Password-Authentication

**Comment by joshcanhelp** [comment]
@jsargent7089 - Sorry for the trouble here and thanks for the detailed report. 

A few questions for you:

* Are you using the Implicit Flow (wp-admin > Auth0 > Settings > Advanced)? If so, why? Just curious what your use case is here. 
* Did you sign up for Auth0 in the last 2 months or before that?

One thing to try is to [generate a new token](https://auth0.com/docs/api/management/v2/tokens#get-a-token-manually) and save that in **wp-admin > Auth0 > Settings > Basic > API token**. Adjust the token expiration date up a bit, maybe 1209600 (2 weeks), so it doesn't expire right away. We're addressing the API access process in the release we're working on now to avoid this work-around. 

Thank you!

**Comment by jsargent7089** [comment]
i Fixed that now got another issue  After I login I get redirected to my home page and when try to the admin page it wants me to login again. 

Error Log
01/23/2018 21:00:55 | WP_Auth0_Api_Client::create_rule Account-Linking-Do-Not-Rename-Dozecloud-LLC | N/A | {"statusCode":409,"error":"Conflict","message":"A rule with the same name already exists","errorCode":"rule_conflict"}
-- | -- | -- | --
01/23/2018 21:00:09 | WP_Auth0_Api_Client::create_rule Account-Linking-Do-Not-Rename-Dozecloud-LLC | N/A | {"statusCode":409,"error":"Conflict","message":"A rule with the same name already exists","errorCode":"rule_conflict"}

**Comment by cocojoe** [comment]
@jsargent7089 Presume you have this option in the plugin under advanced enabled `Link users with same email` ?

@joshcanhelp looking at the first log it looks like it tried to delete the rule but failed as token had expired, once a new token was supplied it tried to re create the rule but of course the old rule was never deleted.

https://manage.auth0.com/#/rules

**Comment by jsargent7089** [comment]
I remove the plugin and reinstall it and now i get

01/23/2018 22:55:37 | redirect_login/decode | N/A | Algorithm not allowed
-- | -- | -- | --
01/23/2018 22:54:10 | redirect_login/decode | N/A | Algorithm not allowed

**Comment by jsargent7089** [comment]
I uninstalled the auth0 plugin and fixed the token issue. Now I'm back to original issue and I can't turn on link users with the same email address. I get this error There was an error creating the Auth0 rule. You can do it manually from your Auth0 dashboard.

There was a problem with your log in This account does not have an email associated, as required by your site administrator.

01/23/2018 23:05:23 	WP_Auth0_Api_Client::create_rule Account-Linking-Do-Not-Rename-Dozecloud-LLC 	N/A 	{"statusCode":409,"error":"Conflict","message":"A rule with the same name already exists","errorCode":"rule_conflict"}
01/23/2018 23:02:38 	redirect_login/decode 	N/A 	Algorithm not allowed
01/23/2018 22:55:37 	redirect_login/decode 	N/A 	Algorithm not allowed
01/23/2018 22:54:10 	redirect_login/decode 	N/A 	Algorithm not allowed
01/23/2018 22:51:52 	WP_Auth0_Api_Client::search_connection 	http_request_failed 	cURL error 6: Could not resolve host: https
01/23/2018 22:51:52 	WP_Auth0_Api_Client::create_rule Account-Linking-Do-Not-Rename-Dozecloud-LLC 	http_request_failed 	cURL error 6: Could not resolve host: https
01/23/2018 22:51:24 	WP_Auth0_Api_Client::search_connection 	http_request_failed 	cURL error 6: Could not resolve host: https
01/23/2018 22:46:42 	WP_Auth0_Api_Client::create_rule Account-Linking-Do-Not-Rename-Dozecloud-LLC 	N/A 	{"statusCode":409,"error":"Conflict","message":"A rule with the same name already exists","errorCode":"rule_conflict"}
01/23/2018 21:27:58 	init_auth0_oauth/token 	invalid_request 	Missing required parameter: code
01/23/2018 21:00:55 	WP_Auth0_Api_Client::create_rule Account-Linking-Do-Not-Rename-Dozecloud-LLC 	N/A 	{"statusCode":409,"error":"Conflict","message":"A rule with the same name already exists","errorCode":"rule_conflict"}
01/23/2018 21:00:09 	WP_Auth0_Api_Client::create_rule Account-Linking-Do-Not-Rename-Dozecloud-LLC 	N/A 	{"statusCode":409,"error":"Conflict","message":"A rule with the same name already exists","errorCode":"rule_conflict"}
01/23/2018 20:51:51 	WP_Auth0_Admin_Basic::delete_cache_transient 	N/A 	deleting cache transient
01/23/2018 20:48:39 	WP_Auth0_Admin_Basic::delete_cache_transient 	N/A 	deleting cache transient
01/23/2018 17:39:39 	WP_Auth0_Api_Client::create_rule Disable-Social-Signup-Do-Not-Rename-Dozecloud LLC 	N/A 	{"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
01/23/2018 17:39:39 	WP_Auth0_Api_Client::search_connection 	N/A 	{"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
01/23/2018 17:30:07 	WP_Auth0_Api_Client::search_connection 	N/A 	{"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
01/23/2018 17:30:06 	WP_Auth0_Api_Client::delete_rule 	N/A 	{"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
01/23/2018 17:28:38 	WP_Auth0_Api_Client::search_connection 	N/A 	{"statusCode":401,"error":"Unauthorized","message":"Expired token received for JSON Web Token validation","attributes":{"error":"Expired token received for JSON Web Token validation"}}
01/18/2018 04:14:25 	init_auth0_oauth/token 	invalid_grant 	Invalid authorization code
01/16/2018 23:57:51 	init_auth0_oauth/token 	invalid_grant 	Invalid authorization code

**Comment by jsargent7089** [comment]
UPDATE if I have Auth0 Implicit flow turn on it works. If it's off can't login with auth0 plugin

**Comment by joshcanhelp** [comment]
@jsargent7089 - The login issue will be fixed with the next release, coming out here in a day or so once we've finished testing. Known critical issue that surfaced, just want to make sure the release is as solid as possible. 

For the rule, you can go to your Auth0 dashboard and delete that manually, then try to re-create. Though I would recommend a clean install once the next release is out.

**Comment by joshcanhelp** [comment]
@jsargent7089 - Release (3.5.0) is live and should fix the issues you've got here. 

If you see a red banner after updating, there will be instructions for completing the update in your Auth0 dashboard. Easiest thing to do is to create a new API token and save it under **wp-admin > Auth0 > Settings > Basic > API token**:

https://auth0.com/docs/api/management/v2/tokens#get-a-token-manually

You can also go to your **Auth0 Dashboard > APIs > Auth0 Management API > Non-Interactive Clients** tab and authorize the WordPress client you’re using.

I'll leave this open for a few days, let me know how it turns out.

**Comment by jsargent7089** [comment]
Everything has been fixed do to the update. Thank you for all help

**Comment by joshcanhelp** [comment]
Great to hear and happy to help!
