### ISSUE TITLE
add_menu_page/admin_menu conflicts with other plugins. 

### ISSUE THREAD

**Issue by mikemcguire** [auth0/wp-auth0#37]
I was having issues where the menu page would not be linked inside of the admin navigation. In particular I found this issue was happening when ACF Pro was activated http://www.advancedcustomfields.com/ I tried to track down where the conflict was happening and found that if I prevented ACF from generating it's  menu page the auth0 menu page link appeared.

Considering that ACF is one of the most popular plugins for wordpress I thought it would reasonable that both plugins should work together.

When comparing the method that each plugin creates it's admin page, I found that both plugins were in fact using the correct action "admin-menu" to hook into, but ACF has set it's priority and accepted arguments whereas wp-auth0 used the defaults. 

Here is ACF's action
```php
add_action('admin_menu', array($this,'admin_menu'), 99, 0);
```
And now wp-auth0's
```php
add_action( 'admin_menu', array(__CLASS__, 'init_menu') );
```

If I add a priority to wp-auth0 of 99+ the conflict resolves itself. Or if I remove the priority argument from ACF the conflict resolves itself. I am not positive what is best practice here, to use the defaults or set a custom priority. I will post a duplicate issue one the ACF plugin github, so that hopefully these types of conflicts can be avoided.

**Comment by woloski** [comment]
thx @mikemcguire, we'll take a look

**Comment by glena** [comment]
I set up a priority with decimals hoping it wont get overridden by other plugin. 
It should be ready in the next release.
Thanks @mikemcguire
