### ISSUE TITLE
[Security] [URGENT] XSS injection error page

### ISSUE THREAD

**Issue by S0c5** [auth0/wp-auth0#381]
## XSS injection

There is a security issue with the error handler page that allows to attackers Inject malicious code.

### replication
```
  http://localhost/index.php?auth0=1&error=invalid_request&error_description=<h1>bug</h1>
```

**Comment by joshcanhelp** [comment]
Thanks for the report, @S0c5, just pushed a fix for review.

**Comment by joshcanhelp** [comment]
#383 approved and merged, ready for next release 👍
