### ISSUE TITLE
[ASK for help] Failed cross origin authentication	

### ISSUE THREAD

**Issue by S0c5** [auth0/wp-auth0#386]
#  Failed cross origin authentication	

## description

Hello guy!, when I'm trying to login in with auth0 using the defaults settings created by the wizard application and after did the sign up  WordPress sends me  this error, please

* could you clarify this one? 
* what did I do bad? 
## How to replicate? 

Please use a default and blank account for auth0 and clean WordPress installation with auth0 plugin, setup the wizard plugin and after that will appear the error. 

##  Error 

```JSON
{"auth0":"1","error":"invalid_request","error_description":"No verifier returned from client.","state":"HIDDEN_STATE"} 

```

## What did I do for figure out the error? 

I follow the back trace of the error until the rediect() function

### Test server

you could quickly test the bug. 

https://wps.pokemapa.xyz/wp-admin

* username: admin2
* password: admin

**Comment by joshcanhelp** [comment]
Hi @S0c5,

Thanks for the detailed report here and apologies for the trouble on this. 

Unfortunately, your replication steps aren't going to work on our end since that's the very least we test before new versions get released. I've walked through a new installation 3 times already today and many more before the last release. Not to say this is not a problem but I'm wondering if it's a config issue on your end. 

So, a few things:

* Are you on the latest version of the plugin (3.5.1)? Latest version of WordPress? Tried deactivating other plugins first?
* Sounds like you're using the default settings but, just to make sure ... anything changed after you installed? 
* Your title is "Failed cross origin authentication" but the error you pasted here is different. Can you clarify? 
* Can you walk through your Auth0 configuration and make sure it matches here:
https://auth0.com/docs/cms/wordpress/configuration

Thanks!

**Comment by S0c5** [comment]
Hi @joshcanhelp,

Answers:

1) yes I'm using the 3.5.1 version of the plugin.
2) Yeah, I didn't do any other change into auth0 configurations.
3) Yeah,  I figure out that error name into the dashboard auth0 in logs section:
 

**Dashboard**:

Type | Failed cross origin authentication
Description  | No verifier returned from client.

 **response server***
```json
{"auth0":"1","error":"invalid_request","error_description":"No verifier returned from client.","state":"HIDDEN_STATE"} 
```
4) yes I walked around the guide and I did all of those steps, but the error continue appearing. 



I tried to do this configuration all day, for that reason I created a project for deploy  as fastest as possible  a clean WordPress for try to do every thing good. if you want to use it check it https://github.com/S0c5/letsencrypt-nginx-wordpress 


Thanks in advance, for the support.

**Comment by joshcanhelp** [comment]
Thanks for that, two more for you ... 

1. The error that you're posting here is from the Auth0 dashboard log, correct? Is there anything relevant in your wp-admin > Auth0 > Error Log?
2. Do you happen to be using incognito mode in Safari? Or another browser?

**Comment by S0c5** [comment]
1. Yes i found it at auth0 dashboard but the wordpress app send me a error page with the error description, but nothing relevant in wp-admin -> auth0 -> error log  for thar reason I found the #381. 
2. Yes, i tried at least all of my ideas that could causing the bug, I will try a old release for test it tomorrow.

**Comment by joshcanhelp** [comment]
1. So the "Error" header above with the JSON block is from your wp-admin? Can you tell me what was under **Section** for that error? That will tell me where this is failing. 
2. I'm not following your answer. Is this error happening in Safari on incognito mode? If so, have you tried with any other browsers? The error message is similar to another one we've seen with this browser and mode.

Happy to help!

**Comment by S0c5** [comment]
Hi @joshcanhelp,

1. that error is from auth0 server.
2. I verified with mozilla Firefox and works every thing good, but with chromium not. why has this plugin changed the behavior with other browser?

**Comment by luisrudge** [comment]
@S0c5 does your chromium setup allows for third party cookies?

**Comment by S0c5** [comment]
@luisrudge Thanks luis!, that fix the issue. !

**Comment by luisrudge** [comment]
no problem! We mention this in the docs [here](https://auth0.com/docs/cross-origin-authentication#limitations-of-cross-origin-authentication). It's a common issue and might go unnoticed until you hit the issue itself. I'm glad it's fixed!

**Comment by cocojoe** [comment]
@joshcanhelp maybe worth a little section in troubleshooting ?
