### ISSUE TITLE
Logout does not work when Wordpress is locked down (private site)

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/wp-auth0#39]
When using a plugin like "Authenticator" we can lock down a Wordpress site (all content needs authentication). Now in that case the Logout does not work as expected. It will clear the Wordpress cookie but it does not logout from Auth0 or the IdP. As a result the following happens:
1. Logout (clear WP cookie)
2. Go to homepage. **Not authenticated**
3. Go to Auth0. **Auth cookie present, we have SSO**
4. Back to WP, user is authenticated.

Note: this only happens when "Auto Login (no widget)" is enabled and a connection is specified (like "google-oauth2")

**Comment by dleeward** [comment]
Even when not using this plugin, I'm unable to logout of WordPress when the SSO option is enabled.

**Comment by joshcanhelp** [comment]
This is ancient but I'll test this out with the upcoming changes to SSO/SLO.

Ref #398

**Comment by joshcanhelp** [comment]
Fixed in #453 and merged into `dev`
