### ISSUE TITLE
sign in throws "mail required" exception even though it is set and verified

### ISSUE THREAD

**Issue by dennis82m** [auth0/wp-auth0#395]
Updated wp-auth0 today. When trying to log in a user, which has verified mail (double checked in Auth0 Dashboard) the plugin throws the "There was a problem with your log in. This account does not have an email associated, as required by your site administrator." exception. 

Disabling the "Require verified mail" setting in Wordpress Dashboard gives another strange behavior when trying to log in. A new Wordpress user is created with the mail address change_me@.....de whereas ... is the unique_id of the user instead of the mail address set up in Auth0 Dashboard. 

Since the error is thrown in WP_Auth0_loginManager.php line 413 I changed the code to print out $userinfo which printed

`stdClass Object ( [statusCode] => 403 [error] => Forbidden [message] => User to be acted on does not match subject in bearer token. [errorCode] => unowned_resource )`

Whats wrong here?

**Comment by joshcanhelp** [comment]
@dennis82m - Sorry for the trouble here. This isn't related to having a verified email, that error is saying that there is no email for the user provided in the response from Auth0. 

Can you check your error log in wp-admin and Auth0 and see if there's anything relevant there?

**Comment by joshcanhelp** [comment]
@dennis82m - I'm going to close this one out since I haven't heard back. One good thing to check is that your Client setup in the Auth0 dashboard matches what's is required:

https://auth0.com/docs/cms/wordpress/configuration#client-setup
