### ISSUE TITLE
Auto-create users option

### ISSUE THREAD

**Issue by rickyrauch** [auth0/wp-auth0#4]

**Comment by glena** [comment]
@rickyrauch do you mean that if the user exists on auth0 but not in WP

**Comment by rickyrauch** [comment]
exactly

**Comment by glena** [comment]
related to #48

**Comment by cancan101** [comment]
Why was this closed?

**Comment by glena** [comment]
@cancan101 https://github.com/auth0/wp-auth0/commit/81401d24925b619199b8505171178633f4ad0d55

**Comment by glena** [comment]
can not be done because we cant restrict the registration with social networks

**Comment by cancan101** [comment]
So is there nothing that can be done to allow new Auth0 users by prevent users from registering with WP?

**Comment by glena** [comment]
not really. This would only works for registration with email and password. =(

**Comment by cancan101** [comment]
Why is that?

**Comment by cancan101** [comment]
Would you re-open this issue?  I really think there should still be an option to turn off signs ups with the WP system but still allowed Auth0 to add new users to the WP site.

**Comment by cancan101** [comment]
@glena Anything that can be done here? Take for example the WooCommerce integration. What I am trying to accomplish is that only users that have accounts on my main site can buy from the store.

**Comment by glena** [comment]
Only using user and password, there is no way to accoplish this using social networks so I can ad a feature that dont work in all scenarios.

**Comment by cancan101** [comment]
Sure, would you add that feature?

I am curious though why it won't work for non username/ password scenarios though.

**Comment by glena** [comment]
i cant know if it was a signup or a login

**Comment by cancan101** [comment]
Right, but isn't that exactly what we want? That we don't care if it is a sign up a or a registration, we just don't want WP's create user system to be turned on.

**Comment by glena** [comment]
you are misunderstanding the issue. If you want wordpress to create users automatically without worry if are new or ld users it already do this.

This issue target to avoid new users registration but let wp autoprovision old users.

**Comment by cancan101** [comment]
The issue I have in mine is #48. Perhaps there are two issues here?

**Comment by glena** [comment]
so I thought you were asking another thing. turn WP registration on and it is done!

summing up

registration on:
- if the user is already in auth0 and what to login it is ok
- if the user is completely new it is ok

registration off:
- only user in wp db will be able to access.

**Comment by cancan101** [comment]
Right.... but I don't want the user to be able to create a new username / account directly with WP. I want them to have an Auth0 account.
