### ISSUE TITLE
SSO does not work if Lock is used outside wp-login.php

### ISSUE THREAD

**Issue by thameera** [auth0/wp-auth0#407]
The code for [handling SSO](https://github.com/auth0/wp-auth0/blob/master/templates/auth0-sso-handler-lock10.php) is only run if in `wp-login.php` and not if Lock is used elsewhere (eg: using shortcode).

**Comment by joshcanhelp** [comment]
Basically this:

https://github.com/auth0/wp-auth0/blob/master/templates/auth0-sso-handler-lock10.php

… needs to run on any page that has Lock on it. Currently called from here:

https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_LoginManager.php#L34

Hooked to `login_message` so it does not output anywhere other than /wp-login.php

**Comment by joshcanhelp** [comment]
Discussion here:

https://community.auth0.com/t/lock-wordpress-plugin-ver-3-5-2-sso-logging-in-doesnt-work-after-upgrade/10839

I removed the labels as I don't think we have a great solution for this yet. Simply loading the `checkSession()` call on every page load is just not sustainable.
