### ISSUE TITLE
Enhancement: Allow WordPress plugin to work in enterprise environment without internet access

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/wp-auth0#42]
A prospective customer with an internal wordpress site with no internet access asked what deployment options of Auth0 they could use.  Would be nice if the wordpress plugin allowed them to use cloud-based Auth0 by not requiring internet access from the plugin to Auth0, e.g. by routing all traffic through redirects through user browser. (It sounds like today, the direct connection from plugin to Auth0 is required to get a token after authentication, so perhaps this could be done by implementing an option to use token flow instead of code flow).

**Comment by glena** [comment]
@yvonnewilson I am not sure about this, isn't it enough to change the lock url and the domain to the intranet endpoint?

**Comment by yvonnewilson** [comment]
@glena Sorry, I don't know enough to answer that question authoritatively - can you check with someone else in dev team?

**Comment by glena** [comment]
Added support for implicit flow.
