### ISSUE TITLE
JWT token iat bug ?

### ISSUE THREAD

**Issue by danyell-hubrix** [auth0/wp-auth0#438]
I haven't thoroughly read the code so I'm not 100% sure about this problem.

WordPress 4.9.5, attempting sign-up using Twitter, I see many lines like this in my log:

`[19-Apr-2018 14:48:12 UTC] Cannot handle token prior to (iat) 2018-04-19T14:56:28+0000`

Anyone know how to fix this?

**Comment by joshcanhelp** [comment]
@danyell-hubrix - Happy to investigate but going to consolidate to a single thread for this:

https://community.auth0.com/t/wp-auth0-wordpress-plugin-jwt-token-problems/11019
