### ISSUE TITLE
Ability to Redirect to WP Site with JWT in Querystring

### ISSUE THREAD

**Issue by cancan101** [auth0/wp-auth0#46]
I have two sites: `www.site.com` and `shop.site.com`. I am using Wordpress on the shopping site (specifically WooCommerce). I currently use Auth0 to authenticate on the main site. I have added the Auth0 WP plugin on the shopping site. 

I would like to require users to use the same account on both sites. Further I would like to avoid even having the user enter his email/password again on the shopping site if he is directed there from the main site. Is there a way that when I link the user from the main site to the shopping site I can do so along with the jwt which can then be used by the auth0 plugin on the WP site to login the user?

Something like `shop.site.com/login?jwt=XXXXXXX`?

**Comment by cancan101** [comment]
Shopify offers something similar: https://docs.shopify.com/api/uiintegrations/multipass

**Comment by glena** [comment]
@cancan101 I think that the better way to do this is using SS0 and loging the user in automatically.

https://auth0.com/docs/sso/single-sign-on

So after the user logs in your WP site, he will not need to login is WooCommerce
