### ISSUE TITLE
Expose a configurable toggle that allows Users to state if federated logout should be used

### ISSUE THREAD

**Issue by moolbits** [auth0/wp-auth0#471]
There's currently no way for Users to have SSO enabled without then triggering a full federated logout.  

The problem is that when 3rd party identity providers are facilitating the connection, like Google and Facebook, the User is redirected back to Google or Facebook respectively, and there is currently no way to change this behavior in the settings for the plugin.

It would be of great value in cases where a federated logout is not a requirement to have a non-federated option, when it comes to leveraging SSO enabled, and Social Connections in particular.

As of right now, according to Enterprise Support, the only way to have SSO enabled without then triggering a full federated logout is to edit the plugin directly:

"...use a modified version of the Wordpress Auth0 plugin where you would remove the federated option from https://github.com/auth0/wp-auth0/blob/9713e6a7cdf4c3446632be5338426dfba102bf3a/lib/WP_Auth0_LoginManager.php#L99 "

This approach is less than ideal, not only because editing Wordpress Plugins directly is bad practice, but also because doing so in this way would supply non-federated logouts for all logout methods, including Username and Password.

Suggesting an enhancement that would expose a configurable toggle that would allow Users to state if a federated logout should be used or not for Social Connections when SSO is enabled. It would be really nice if federated logouts could be toggled non-federated, for each Social Connection individually.

**Comment by joshcanhelp** [comment]
@moolbits - Thanks so much for the thorough report here! This was an issue identified earlier and is fixed in a release coming out tomorrow (#453). The fix was to just remove `federated` because it's far more likely that a site owner needs a non-federated logout. I am tracking an issue internally to include a filter to adjust that, if needed. 

Let me know if you have any questions or any issues after tomorrow's update!
