### ISSUE TITLE
Error: Could not create user. The registration process is not available.

### ISSUE THREAD

**Issue by cancan101** [auth0/wp-auth0#48]
I am getting the following error after I login:
```
Error: Could not create user. The registration process is not available.
```

This seems to be caused by this: https://github.com/auth0/wp-auth0/blob/fed6a4916de0e74d365653f3a6e4a6cb0e78c6d6/lib/WP_Auth0_Options.php#L9 which means that you need to turn on WP user creation to have newly visiting Auth0 users work. This seems wrong.

**Comment by glena** [comment]
@cancan101 if you turn the WP "Anyone can register" off, the signup is disabled on lock, why does it seem wrong to you?

![image](https://cloud.githubusercontent.com/assets/5647310/7454873/3af0c704-f24e-11e4-9719-337a8a7a6cfb.png)

**Comment by cancan101** [comment]
Presumably the user has already registered, just not with the WP site. Unchecking this means that the WP will not allow an already registered user to "login for the first time" to the WP site.

**Comment by glena** [comment]
oh, ok. thanks
