### ISSUE TITLE
TypeError: jQuery(...).tab is not a function

### ISSUE THREAD

**Issue by talamihg** [auth0/wp-auth0#484]
`TypeError: jQuery(...).tab is not a function admin.php:689:5`

When in `/wp-admin` > `Auth0` > `Import-Export settings` clicking on the Export Settings tab causes this JS error and the page does not appear.

Running wp-auth0 v3.6.1

**Comment by talamihg** [comment]
Thanks for the quick response. Can confirm this hotfix works.

**Comment by joshcanhelp** [comment]
Absolutely. We'll have a fix out for this ASAP

**Comment by joshcanhelp** [comment]
Fixed in #486, now merged into `dev`.

For anyone that doesn't want to (or can't) implement the hotfix above, just open the JS console in your browser and run the following:

```js
jQuery('#export').show();
```

That will make the **Export** button appear and work normally.
