### ISSUE TITLE
wp-login.php sending connection to Auth0 even though 'auto_login' => 0,

### ISSUE THREAD

**Issue by cancan101** [auth0/wp-auth0#49]
Even though I am using the following settings:
```
'auto_login' => 0,
'auto_login_method' => '',
```
When I try to login from the wp-login.php page the `connection` field is being set to just one value so that login is failing because not all of the connections are being considered.

**Comment by glena** [comment]
Hi @cancan101 can you explain a little further?

**Comment by cancan101** [comment]
It may be related to this: https://ask.auth0.com/t/lock-does-not-work-with-app-with-multiple-connections/905

**Comment by glena** [comment]
so, yo have multiple connections active on your app? 
Why do you need more that one connection active?

**Comment by cancan101** [comment]
Even if there should be only one database connection active, there is currently know way of specifying / setting that to the Lock.

**Comment by glena** [comment]
Ready for V.Next, will be released next week
