### ISSUE TITLE
`auth0_state` cookie and Pantheon

### ISSUE THREAD

**Issue by jessCmi** [auth0/wp-auth0#494]
We have a client who is on Pantheon and we are having issues with the latest version of the plugin and the "Invalid state" error. Looking at this troubleshooting guide I have a pretty good idea what the issue is (https://github.com/joshcanhelp/troubleshooting-invalid-state-wp/) based on step three of the plugin's new process.
The problem is that Pantheon Wordpress cookies have to have `STYXKEY_` at the beginning of their name or they are unreadable. As such, I believe that there is a change the `auth0_state` cookie is not being seen by our site. 
Is there a way for us to override the cookie name to `STYXKEY_auth0_state` perhaps or maybe a new setting field can be added where the cookie name is set?

**Comment by joshcanhelp** [comment]
Hi @jessCmi,

Happy to help. There is not currently a way to adjust that cookie name but it would be easy to add a filter to handle that. I'm working on a patch release now and I'll get this change into that cycle. Should have that out tomorrow or Monday at the latest. 

Are you able to test it out on a test/staging install?

Thanks for the report!

**Comment by joshcanhelp** [comment]
@jessCmi 

This was a simple fix so I put that through and it's now available in the [`dev`](https://github.com/auth0/wp-auth0/tree/dev) branch. If you can pull that down and follow the sample in the PR (#495), you should have what you need. 

Let me know if that works as soon as you're able. Thank you!

**Comment by jessCmi** [comment]
Thank you so much! This was the issue, and your fix will solve it.

**Comment by joshcanhelp** [comment]
@jessCmi - Great to hear! If you're able to test ahead of the release, that would be helpful. Otherwise, look for the new version tomorrow at the earliest, Monday at the latest.

**Comment by ShayMe21** [comment]
More details about the cookie naming requirements in Pantheon: https://pantheon.io/docs/cookies

Quick fix to this issue for me was downloading Code Snippets plugin and adding a new snippet with the code @joshcanhelp included in the PR https://github.com/auth0/wp-auth0/pull/495

No more "Invalid State" errors!
