### ISSUE TITLE
Single sign on shows the login username/password fields briefly before automatically signing in

### ISSUE THREAD

**Issue by ghills** [auth0/wp-auth0#508]
Steps:
- Plugin configured in Wordpress with SSO enabled.
- Logged into auth0 account from the same tenant (different application) using the hosted login page.
- Link is clicked that goes to a Wordpress page that requires login and automatically redirects to the login page.

Expected behavior:
- User is taken to the login page.
- Lock widget is loaded and has the "spinner" animation.
- User is authenticated and redirected to the originally requested page (via redirect URL)

Actual behavior:
- User is taken to the login page.
- Lock widget is loaded and shows "spinner" briefly.
- **Spinner animation is removed and the username/password fields are displayed in the lock widget.**
- The page continues working and after a few more seconds redirects the user to the originally requested page.

As you can see, while the SSO works there is some confusion as it looks like it is requiring the user to enter credentials before it completes the SSO. This is mostly a cosmetic thing but may confuse users depending on how long it sits on the page with the login fields present.

**Comment by joshcanhelp** [comment]
@ghills - Thank you for the report here and detailed repro steps. This is on our radar for the next release. That delay is dependent, in part, on your network speed so a slower speed will take longer to make the necessary SSO call. We'll change that to make the Lock init depend on that check. 

Thanks again!

**Comment by ghills** [comment]
Great! Thank you for the quick response.
