### ISSUE TITLE
Configuring auth0 OIDC URL parameters

### ISSUE THREAD

**Issue by nodomain** [auth0/wp-auth0#521]
In order to configure our main tenant's login window we are obliged to use OIDC URL parameters.
When using mod_openidc for Apache, I do that by configuring:

`OIDCAuthRequestParams connection=main-tenant-oidc&display=sup`

How can I inject the `display=sup` parameter into the Auth0 request?
Tried some ways without success.

Thanks.

**Comment by joshcanhelp** [comment]
@nodomain - Happy to help. 

> the Auth0 request?

Which Auth0 request? Can you walk me through what you're trying to do and where you want to add that?

**Comment by nodomain** [comment]
Ok perhaps I was not clear enough. 🙈  

I have some Auth0 Integrations with the Apache module mod_openidc. There I can configure the request params for the Auth0 request using the parameter `OIDCAuthRequestParams` as described here: https://github.com/zmartzone/mod_auth_openidc/wiki#13-how-can-i-add-custom-parameters-to-the-authorization-request
Now I want to use the "native" Wordpress Auth0 plugin instead of having an Apache in front of it doing the authorization. How can I add these custom parameters to the authorization request with the Auth0 Wordpress module? Goal would be to add "display=sup" to the authorization request in order for the custom configured login form from our main tenant to display the needed "Register account" tab.

**Comment by joshcanhelp** [comment]
@nodomain - Thanks for the clarification. One more question for you ... are you using the Universal Login Page? The plugin does not, by default, use that but can be configured to do so.

**Comment by nodomain** [comment]
In our scenario we use a custom hosted login page in the main tenant of our company. My Wordpress instance is configured in a sub Auth0 tenant, hence I need to use `main-tenant-oidc` in the "Auto Login Method" attribute.
Even if that does not answer your question directly, I hope to shed some light on it :)

**Comment by joshcanhelp** [comment]
@nodomain - Thanks for that, I see what you're trying to do now. 

At the moment, there is no way to change that but I think it's a good candidate for a filter to add URL parameters as needed. We just put out a release today but I can add this to the next patch release if that works for you.

**Comment by nodomain** [comment]
Sounds awesome :)
