### ISSUE TITLE
Wordpress Login - Sorry, that email address is already used! [error code: unknown]

### ISSUE THREAD

**Issue by itjunkii83** [auth0/wp-auth0#524]
When I try and login to my wordpress it says:

"There was a problem with your log in: Sorry, that email address is already used! [error code: unknown]"

However if I login with a Wordpress user not in auth0 it creates the user in Auth0 and everything looks normal on that end although I get the above error. If I try and login with a user already in Auth0 it records it as a successful login in Auth0 Dashboard however I always get this error mentioned above and asked to login again.

The same configuration works perfectly on my local machine when logging in.

Even though the Require Verified Email is off If I go into Auth0 and verify the email manually it allows my staging server to login. My local still works either way regardless of if I verify in Auth0 or not.

In case it helps anyone else adding this filter fixed the issue.

```
function auth0_theme_hook_auth0_get_wp_user( $user, $userinfo ) {
	$found_user = get_user_by( 'email', $userinfo->email );
	$user       = $found_user instanceof WP_User ? $found_user : null;
	return $found_user;
}
add_filter( 'auth0_get_wp_user', 'auth0_theme_hook_auth0_get_wp_user', 1, 2 );
```

**Comment by nmoinvaz** [comment]
Do you have the "Link Users with Same E-mail" option turned on in the settings?

**Comment by itjunkii83** [comment]
Hey @nmoinvaz that setting is not turned off on our install

**Comment by joshcanhelp** [comment]
@itjunkii83 - Apologies for the delay, I didn't see a notification for this. 

I'm sorry but I'm not totally following your steps here. The error message you mention is a core WP error message passed through to the plugin when you're trying to register a new user that has an email address of an existing user. 

If you can write out a step-by-step reproduction here (URL you're on, where the error is appearing, etc), that would be helpful. 

Thanks!
