### ISSUE TITLE
Ability to manually link account in user profile

### ISSUE THREAD

**Issue by nmoinvaz** [auth0/wp-auth0#529]
This is for a feature request to be able to manually link a Wordpress to a user in Auth0. I would imagine when you go into the User's profile in Wordpress, it would have an Auth0 section that would allow you to enter in the user's auth0 id - this would create the wp_auth0_id user meta value. 

The use case where this would be of value is you need to manually link the accounts as in the case where you have _Link Users with Same E-mail_ turned off due to _Require Verification E-mail_ not working because of using a custom DB. So in that instance I would need a way to manually assign accounts to a particular Auth0 id. 

Thanks!

**Comment by joshcanhelp** [comment]
Backlogged internally for a future release.
