### ISSUE TITLE
Why is Client Secret Needed

### ISSUE THREAD

**Issue by cancan101** [auth0/wp-auth0#53]
The lock should be able to function with a redirect without needing the client secret at all.

**Comment by rolodato** [comment]
Lock does not need the client secret, nor can it use it in any way. The client secret in this plugin is used to make Auth0 API calls such as sending verification emails or exchanging OAuth codes for tokens.

**Comment by cancan101** [comment]
@rolodato 
Why is that needed by the WP plugin and not any other webpage using the Lock?

**Comment by glena** [comment]
@cancan101 I think @rolodato was clear. It is needed to make api requests from the backend. Lock doesnt use the secret for ovbious security reasons, but is always needed in the backend.
