### ISSUE TITLE
Add authorization token to header for external request

### ISSUE THREAD

**Issue by avanderpluijm** [auth0/wp-auth0#534]
Hello, 

What do I need to do to create a authenticated request to an external service? 
I am using `wp_remote_get(url,args);` to make this request, but it needs an 'Authorization Bearer xxxx'  header. 

Is there a way to get this token from this module? Something like get_token() 

(also posted this question at [auth community forum](https://community.auth0.com/t/how-to-add-authorization-header-in-wordpress-to-external-api-request/15248))

**Comment by joshcanhelp** [comment]
Thanks @avanderpluijm, I'll answer this question over there to keep responses in one place.
