### ISSUE TITLE
No verifier returned from client in IE v11 though custom domain & callback-cross-auth implemented

### ISSUE THREAD

**Issue by chauhanvishaal** [auth0/wp-auth0#535]
Hi,

I am fighting this error since a while now. 
I have implemented custom domain and callback-cross-auth.html pages.
Do not have cookies blocked in IE v11 even then cant get rid of the problem.
Below are the options I pass to Auth0Lock before calling 
this.lock.show({  allowSignUp: false });

These options work in IE if I set redirect: false but with that MFA authentication doesnt work which is why I am now using default redirect: true which has problems with IE. 

Please help..

```
oprtions = {
            configurationBaseUrl: 'https://cdn.eu.auth0.com',
            auth: {
                redirectUrl: window.location.origin,
                autoParseHash: true,
                responseType: 'token id_token',
                params: {
                    scope: 'openid email profile name picture user_metadata app_metadata user_id',
                    state: JSON.stringify({

                    })
                }
            },
            allowSignUp: false,
            allowForgotPassword: true,
            theme:  {
                logo: this.logo,
                primaryColor: '#0a355c'
            },
            avatar: null,
            closable: true,
            rememberLastLogin: false,
            container: "login-container",
            languageDictionary: {
                success: {
                    logIn: ''
                }
            },
        }; 
```

**Comment by joshcanhelp** [comment]
@chauhanvishaal - Sorry for the trouble here. 

> I have implemented custom domain and callback-cross-auth.html pages

If you have the former setup, you should not need the latter. Do you have your custom domain added in the Custom Domain field in the WP plugin settings? Just need the domain, not `https://` there. The `configurationBaseUrl` should be added automatically based on your tenant domain (that also needs to be in the plugin settings).

**Comment by joshcanhelp** [comment]
Also ... I'm not sure where all that JSON is coming from or going, all of that is generated automatically in the plugin based on your settings.

**Comment by chauhanvishaal** [comment]
Thanks for your reply Josh. 
My issue apparently seems to be only in my local environment. Later in the day I thought of checking the same build on a proper integration environment, which seemed to work.  
So I will close the issue, though my local env still doesnt work. I have even tried following below steps at the end of this link: https://auth0.com/docs/custom-domains

Go to Internet Options > Security.
Select the Local Intranet Zone tab and go to Sites > Advanced. Add your domain.
Return to the Security tab, and make sure the proper zone has been selected.
Click Custom Level and look for Access data sources across domains under the Miscellaneous section. Check the radio button next to Enable..
