### ISSUE TITLE
Plugin tries to create a user if they log in a different way

### ISSUE THREAD

**Issue by stoicbuddha** [auth0/wp-auth0#539]
Looks like this is related to [#524](https://github.com/auth0/wp-auth0/issues/524).

What we've run into is: 
Step 1: a user initially logs in via Google when they don't have a WP user.  The plugin creates a WP user (as expected).
Step 2: They log out at some point.
Step 3: They try to log in via email/pw.

Expected result: normal login.

Actual result: **Sorry, that email address is already used! [error code: unknown]**

I'm not sure why it tries to create a user, but it ends up throwing the error because it finds user meta set by auth0 already for the googleauth2 login (checked on this line [here](https://github.com/auth0/wp-auth0/blob/master/lib/WP_Auth0_UsersRepo.php#L114)).

My current "fix" for the client that ran into this was to comment out the error and just return the ID for that user as the function would if a new user was actually created.  Not sure if it's the best way, but it's **a** way.

**Comment by joshcanhelp** [comment]
@stoicbuddha - thanks for the report here. 

If you login with Google using a certain email address, that user account is tied to a specific Auth0 user created for that connection. If you then try to create a new user with a different connection, like a database in your case, but using the same email address, then that's a different Auth0 user with a different user ID. The plugin searches for the email address, finds one, sees if it's associated with an Auth0 user ID, sees that it is, then compares that to the incoming user ID. Those are different so it's rejecting the WordPress registration. 

What that linked issue is talking about is a setting that sets a Rule in Auth0 to combine users with the same email address, creating a single user with a single user ID. Right now, that's the only way to handle the same user coming in on different connections. We're working through a way to do that on the WordPress side (handle 2 separate Auth0 users with the same email address) but we don't have a timeframe for that currently. 

If you're able to skip the error then you now have a single WordPress user with the user ID for the Google account only and no connection with the database connection user. I'm not entirely sure what that would do down the road but I wouldn't recommend it.

**Comment by stoicbuddha** [comment]
Hey @joshcanhelp 

The problem is that it shouldn't be trying to create a user at all; it does this whether you try to "Log In" or "Sign Up". It's calling the "Create" functionality for reasons I haven't had a chance to look at, but it's the logic that's calling said functionality that breaks everything.

I don't have the functionality to combine users switched on at the moment because it requires users to have verified emails and the client doesn't wish to do that at this time.  Is that why it's trying to create them?  If so, would there be any way around that? I understand that this is probably not a common use case, so it would make sense if there isn't.

It seems to be creating users (when it truly needs to) just fine, and seems to sign users up well enough, so I'm not sure of any long-term effects since I haven't seen short-term damage.  That said, if this is an issue caused by their particular needs, I can let them know (although there should be some kind of warning about this somewhere I feel).
