### ISSUE TITLE
Keep getting logged out once SSO is turned on

### ISSUE THREAD

**Issue by leokoo** [auth0/wp-auth0#541]
I was logging in fine until I enabled the SSO feature. Right now, the only way in is by disabling the plugin :( Otherwise, I'll be logged in and then out.

Any thoughts on this?

**Comment by joshcanhelp** [comment]
Sorry for the trouble @leokoo ... so you're saying you get immediately logged out when you log in with SSO? Sounds like you haveSingle Logout (SLO) turned on as well and it's not working properly. Can you turn off SLO and see if that stops happening? 

For more context ... SLO checks Auth0 for a session and automatically logs you out of there isn't one. If you can login just fine with Auth0, I don't know why SLO wouldn't work but it's worth a check.

**Comment by joshcanhelp** [comment]
Yes, that's a plugin setting. You can adjust like so, run somewhere in the same WP environment:

```php
WP_Auth0_Options::Instance()->set( 'singlelogout', null );
```

That said, have you tried logging in again after you were logged out? I would guess so but just wanted to check.

**Comment by joshcanhelp** [comment]
@leokoo - Just circling back to this before we release the latest version. I'm not seeing any issues with how SLO is implemented in the plugin. I'm wondering if maybe you were using a social connection without generating your own keys (using the default development keys)? If so, that check will always an error and log users out. If this is the case, either generate your own keys there or try a regular user and password. 

I should mention ... the SLO feature will be removed in the next major release as it causes a lot of calls to our authentication server, depending on your traffic. 

Thank you!

**Comment by joshcanhelp** [comment]
Going to close this for now. Please let me know if there are any other questions here.
