### ISSUE TITLE
Better documentation of User Migration endpoints with manual setup

### ISSUE THREAD

**Issue by briansrepo** [auth0/wp-auth0#542]
I kept getting oauth errors when I tried to run the setup wizard on a stand-alone install of Wordpress, so I decided to set it up manually. It all went pretty smoothly until I turned on the Custom Database option. I found zero documentation about the two endpoints the User Migration option activates. I got stuck on that for a long time until I found [this post](https://community.auth0.com/t/i-cannot-make-wordpress-work-with-custom-database-migration/8366/4) which explained everything. I thought it was so bizarre that I had to copy NodeJS code out of a PHP file buried in the codebase in order to get it working. A short explanation that this option activates those two endpoints would have been incredibly helpful. A link to the NodeJS scripts would have been even better.

After figuring that out, it worked like a charm. But it got me wondering how anyone else ever gets it working when it was so difficult to find documentation about the most important link in the chain. Is that normally handled by the setup wizard behind the scenes? Either way, I think it would be a good idea to put a little explanation next to that field, or a little question mark people can click for an explanation. Otherwise it's worked great, definitely made integration a lot smoother.

**Comment by joshcanhelp** [comment]
@briansrepo - Sorry for the trouble there and I totally agree. The user migration feature is nice in many cases but if the automatic setup doesn't work then it is definitely a pain to get it setup correctly. I will add this to our backlog to get a proper documentation page created for this. It will still be copy/pasting NodeJS code but it will be in a better format with more clear instructions.
