### ISSUE TITLE
"search_engine=v2 is not available for your tenant because it is deprecated" error

### ISSUE THREAD

**Issue by mufid** [auth0/wp-auth0#562]
### Description

I've configured WP-Auth0. But then after trying to login, it says:

    There was a problem with your log in:
    {\"statusCode\":400,\"error\":\"Bad Request\",
    \"message\":\"The User Search Engine v2 
    (search_engine=v2) is not available for your tenant 
    because it is deprecated. Please use the 
    User Search Engine v3 instead (search_engine=v3).
    For guidance on how to upgrade from v2 to v3, see
    https://auth0.com/docs/users/search/v3#migrate-from-search-engine-v2-to-v3\",
    \"errorCode\":\"operation_not_supported\"}
    [error code: access_denied]

### Prerequisites

* [x] Did you check the [documentation](https://auth0.com/docs/cms/wordpress/)? Yes, it only says API for migration for standard web app, but says nothing about this wordpress plugin
* [x] Did you check the [Auth0 Community](https://community.auth0.com/tags/wordpress)? Yes. Found [this](https://community.auth0.com/t/extra-validation-username-field-in-sign-up-form-login-by-auth0-wordpress-plugin/12654) link, it says something about user API, but not sure if this is relevant
* [x] Did you check the [WP.org Support Forum](https://wordpress.org/support/plugin/auth0)? Yes
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/wp-auth0/issues) or [PRs](https://github.com/auth0/wp-auth0/pulls) in this repo? No duplicate

### Environment

Please provide the following:

* WP-Auth0 version: 3.7.0 
* WordPress version: 4.9.8
* PHP version: PHP 5.6.33-3+ubuntu16.04.1+deb.sury.org+1 (cli)
* Browser version, if applicable: Firefox 62.0.3 (64-bit)

### Reproduction

1. Create new tenant with Auth0
1. Implement Wordpress by creating new Application, as in Auth0 official guide
1. Trying logging in with Auth0

Expectation: can login as usual
Actual: It shows `search_engine=v2 is not available for your tenant because it is deprecated`

**Comment by cocojoe** [comment]
Thanks for the feedback, we will look into this.

**Comment by joshcanhelp** [comment]
@mufid  - Thank you for the report here and apologies for the trouble. The fix here is:

1. Go to your [Auth0 dashboard > Rules](https://manage.auth0.com/#/rules)
2. Edit the **Account-Linking-Do-Not-Rename** Rule:

![screenshot 2018-10-08 09 02 13](https://user-images.githubusercontent.com/855223/46620191-e8116180-cad8-11e8-9348-6079913cadb1.png)

3. On or around line 26, change `v2` to `v3`

I'll put out a patch release to address other new installs.

**Comment by joshcanhelp** [comment]
Releasing the patch on WP.org now.
