### ISSUE TITLE
Access Token is null in auth0_user_login action

### ISSUE THREAD

**Issue by ucu13** [auth0/wp-auth0#581]
Hey,

I'm trying to get the access token in "the auth0_user_login" action after a user login, but both $access_token and $refresh_token are null. Probally i need to some additional settings in order to get access_token.

From what i see in the code, is possible that auth0 to not return the access_token.
What are that situations?

I'm using Passwordless authentification with SSO and Implicit Login Flow enabled.

Thank you.

**Comment by joshcanhelp** [comment]
Hi @ucu13,

Implicit Flow does not use an access token, only an ID token so it makes sense that this is null. The access token is typically just used to get userinfo and, with the ID token, you already have that. 

What are you using the access token for? And why is implicit flow turned on?

**Comment by ucu13** [comment]
Thank you,
If i disable implicit login flow I receive also the access token. Really I don't know why was enabled.

I don't know the details where the access token will be used in this case, A team that develop a 3thParty application made the request to my client.

**Comment by joshcanhelp** [comment]
Implicit flow is typically only used if your server can't make an HTTP call to Auth0. If the login process works without that on, then I would keep it there. 

I didn't answer about the refresh token ... the `auth0_auth_scope` filter can be used to add `offline_access` to the scopes, which will return a refresh token:

https://auth0.com/docs/cms/wordpress/extending#auth0_auth_scope

Hope that helps! Going to close this now but please feel free to reply if you have any more questions on this.
