### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by toddheslin** [auth0/wp-auth0#591]
There is an option missing from the documentation: **Token Endpoint Authentication Method**

![image](https://user-images.githubusercontent.com/1883112/48750038-58a2c500-ecb8-11e8-9253-41b7cd7473f5.png)

This needs to be set to basic such that the value in here is simply the `access_token` returned from the `/oauth/token` request:
![image](https://user-images.githubusercontent.com/1883112/48750081-7bcd7480-ecb8-11e8-8142-c6aa909a2d82.png)

**Comment by toddheslin** [comment]
Should also be noted that 'Client Credentials' dropped off after I changed from POST to Basic.
![image](https://user-images.githubusercontent.com/1883112/48750460-24300880-ecba-11e8-8adc-05a3bae62e3f.png)

Might be worth testing and/or documenting.

**Comment by joshcanhelp** [comment]
@toddheslin - Actually, that should be set to the Web App default of "Post," which is why it's not called out specifically. The API token field is more or less a temporary access token for the Management API to allow certain changes to happen. The client credentials grant that gets an access token automatically for Management API changes does not save a token there.

**Comment by toddheslin** [comment]
Hmmm I wonder if this is because I didn't go through the wizard setup? I actually used the API to generate the original token (using postman actually) and then pasted it into that wordpress API Token box. I'm struggling to remember but I'm thinking it was the first request that would have failed if I didn't choose `Basic`.

Oh well, close the issue and if anyone comes across a similar issue they can chime in and we can see if it warrants a bit more explanation :-)

btw great community management! I see you've been active across the issues and wordpress comments. Must be a tough role playing whack-a-mole with such a wide variety of implementations. 👍

**Comment by joshcanhelp** [comment]
The setup wizard is the preferred way to do it as it takes care of all of the different details. That said, we're working on a way to have that be a little more interactive and less of a black box.

> btw great community management!

Thank you! It's a lot of fun and pretty much every issue either leads to a fix/improvement or better documentation so it's all part of the process 😄
