### ISSUE TITLE
State shouldn't be required

### ISSUE THREAD

**Issue by MarkPfennig** [auth0/wp-auth0#66]
$state = $wp_query->query_vars['state'];
    ...
    if ($stateFromGet->interim) {

Lines 344 & 392

This assumes state is present, and assumes that it's a json_encoded object that always has an interim property. Due to this it throws PHP notices which if displayed prevent auth0 from redirecting.

State isn't always present, like when doing sso via /authorize.

Just use `isset` checks and it'll fix the problem :)

Thanks

**Comment by glena** [comment]
Sure, I will make a release fixing that by today

**Comment by glena** [comment]
This is fixes on the version 1.2.4 of the plugin. Will be ready to update in a minutes.
