### ISSUE TITLE
Hardwired redirect url after login

### ISSUE THREAD

**Issue by jakuub** [auth0/wp-auth0#71]
In the file https://github.com/auth0/wp-auth0/blob/master/templates/auth0-login-form.php#L122 there is hardwired place of wordpress `index.php`. 
Our issue is, that we have wordpress in the subdirectory of the webserver, to be precise on `/articles/` , so we need the path `/articles/index.php` there. Maybe the best solution will be to prefix `index.php` by wordpress site url `<?php echo get_site_url(); ?>`. 

The related support issue on wordpress.org is https://wordpress.org/support/topic/hardwired-redirect-url-after-login

**Comment by glena** [comment]
ready in next release

**Comment by jakuub** [comment]
Thank you :+1:
