### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by dobesv** [auth0/wp-auth0#75]
Currently it seems like Auth0 calculates the WPA0_PLUGIN_URL too soon in the process, so the URL of the CSS files doesn't get https:// on a secure site.

Calculating this value on demand fixes the problem, e.g.:

        wp_enqueue_style( 'auth0-widget', trailingslashit(plugin_dir_url(__FILE__) ) . 'assets/css/main.css' );

**Comment by glena** [comment]
Targeted for the next release (PR #78). Thanks
