### ISSUE TITLE
pt-BR language is not being installed

### ISSUE THREAD

**Issue by rafaels-dev** [auth0/wp-auth0#760]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I've installed Auth0 3.11.1 plugin in my Wordpress 5.2.5. My tenant is configured with pt-BR language. My wordpress is configured to require only confirmed e-mails.

Sign-up and Login steps is in brazilian portuguese, but after register, the message "This site requires a verified email address." appears in english.

I looked for this string in plugin files and folders, and I can see just these files:

```
root@app-websites-b:/data/wp/bb-atend/wp-content/plugins/auth0/languages# ls -ll
total 232
-rw-r--r-- 1 www-data www-data  63979 Jan  6 17:12 wp-auth0-es_ES.mo
-rw-r--r-- 1 www-data www-data 104845 Jan  6 17:12 wp-auth0-es_ES.po
-rw-r--r-- 1 www-data www-data  65176 Jan  6 17:12 wp-auth0.pot
```
I think another languages is not being installed when plugin is activated.
The i18n worked fine after I copied languages folder from GitHub.

**Comment by joshcanhelp** [comment]
@rafaels-dev - Apologies for the confusion. The language files are in the `master` branch to be released with v4.0.0 (we're still a couple of weeks out from that). They can be copied into the current version, as you saw, but they will be missing some of the strings present in the current version.

**Comment by rafaels-dev** [comment]
Hi @joshcanhelp. Could you include these files in version '3.11.2', please? I can see a branch called _3.11.2-dev_ in development.
Today, I've 11 tenants (and growing) and it's hard to copy for each instance, because they're running using _docker_ containers.

**Comment by joshcanhelp** [comment]
The problem is that this translation file does not include a number of strings used in v3.x. We've removed a number of places where strings are output so you would be missing translations.

**Comment by rafaels-dev** [comment]
Could I translate the file for v3.x and sent a PR?

**Comment by joshcanhelp** [comment]
If you can do it in the next hour :) we have to release ASAP to account for SameSite changes - #758

**Comment by rafaels-dev** [comment]
Next hour it's very hard to me, sorry. Go ahead with your release. I can make a PR for next versions, if it's applicable in your oppinion.
