### ISSUE TITLE
Custom settings are not saved due to newly introduced settings validation

### ISSUE THREAD

**Issue by nturbanov** [auth0/wp-auth0#782]
### Description

Custom settings fields (options) created using the `auth0_settings_fields` filter [created as described in the documentation](https://auth0.com/docs/cms/wordpress/extending#auth0_settings_fields) are not saved in the database upon saving changes in the Auth0 Settings.

I've tracked down the issue to the [new validation done to settings where non-default option keys are unset](https://github.com/auth0/wp-auth0/blob/10b1fc92d4c13164114609ba9384394d36a70771/lib/admin/WP_Auth0_Admin.php#L98).

```
// Remove unknown keys.
$option_keys = $this->a0_options->get_defaults( true );
foreach ( $input as $key => $val ) {
    if ( ! in_array( $key, $option_keys ) ) {
        unset( $input[ $key ] );
    }
}
```

There's currently no filter for the validation done here so the only way around this at the moment is to disable this validation.

### Reproduction

Create a custom settings via the `auth0_settings_fields` filter [as described here](https://auth0.com/docs/cms/wordpress/extending#auth0_settings_fields).

Go the Auth0 Settings in WP admin, input something in the custom field and Save Changes. Notice changes to the custom settings are not saved, instead the field is empty. Verify this by checking the value on the option `wp_auth0_settings` in the database.

To fix, comment out lines [99](https://github.com/auth0/wp-auth0/blob/10b1fc92d4c13164114609ba9384394d36a70771/lib/admin/WP_Auth0_Admin.php#L99) to [104](https://github.com/auth0/wp-auth0/blob/10b1fc92d4c13164114609ba9384394d36a70771/lib/admin/WP_Auth0_Admin.php#L104) in [lib/admin/WP_Auth0_Admin.php](https://github.com/auth0/wp-auth0/blob/master/lib/admin/WP_Auth0_Admin.php).

Update setting again in WP admin and verify the custom setting is saved.

### Environment

- v 4.0.0-beta

**Comment by joshcanhelp** [comment]
@nturbanov - Apologies for the trouble and I appreciate the detailed report here. We'll look into a fix right away.
