### ISSUE TITLE
Current custom autoloader is very slow

### ISSUE THREAD

**Issue by szepeviktor** [auth0/wp-auth0#783]
### Description

The current autoloader is brute-forcing its way through PHP files.

### Suggestion

As Composer autoloader is already included
@joshcanhelp please consider using it for loading all our classes with `"classmap"`

May I send a PR?

**Comment by joshcanhelp** [comment]
As long as it's not a breaking change, that would be great!

**Comment by szepeviktor** [comment]
@joshcanhelp Done in 16 lines.
