### ISSUE TITLE
Basic trio of tests

### ISSUE THREAD

**Issue by szepeviktor** [auth0/wp-auth0#786]
Please introduce my basic trio as authentication is a delicate matter.

1. syntax check `vendor/bin/parallel-lint --exclude vendor/ .`
1. coding standard ✔️ 
1. static analysis, see #785

These should be part of every CI.

**Comment by joshcanhelp** [comment]
@szepeviktor - Are we OK to close this now?

**Comment by szepeviktor** [comment]
If you are not wiling to start using PHPStan, add it to CI, and fix some more problems.

**Comment by szepeviktor** [comment]
```
viktor@mail:~/src/wp-auth0$ vendor/bin/phpstan analyze -l 2
Note: Using configuration file /home/viktor/src/wp-auth0/phpstan.neon.dist.
 55/55 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ --------------------------------------
  Line   lib/WP_Auth0_LoginManager.php
 ------ --------------------------------------
  274    Variable $user might not be defined.
 ------ --------------------------------------

 ------ -------------------------------------------------------
  Line   lib/WP_Auth0_Nonce_Handler.php
 ------ -------------------------------------------------------
  83     Unsafe usage of new static().
         💡 Consider making the class or the constructor final.
 ------ -------------------------------------------------------

 ------ ---------------------------------------
  Line   lib/WP_Auth0_WooCommerceOverrides.php
 ------ ---------------------------------------
  40     Function wc_get_page_id not found.
 ------ ---------------------------------------

 ------ -------------------------------------------------
  Line   lib/api/WP_Auth0_Api_Client_Credentials.php
 ------ -------------------------------------------------
  84     Access to an undefined property object::$scope.
 ------ -------------------------------------------------

 ------ -------------------------------------------------------------
  Line   lib/initial-setup/WP_Auth0_InitialSetup_Consent.php
 ------ -------------------------------------------------------------
  112    Cannot access property $client_id on array|object|true.
  113    Cannot access property $client_secret on array|object|true.
  115    Cannot access property $client_id on array|object|true.
 ------ -------------------------------------------------------------
```

**Comment by joshcanhelp** [comment]
I am willing to accept more PRs 😄 I wasn't sure if #785 was the extent of what you wanted to do or if there was more.

**Comment by szepeviktor** [comment]
That PR was a bunch of fixes on Level 2, no integration.

**Comment by szepeviktor** [comment]
- Variable $user need cleaner, testable logic
- WP_Auth0_Nonce_Handler needs to be final to be safe
- wc_get_page_id could be added as a stub
- making an object from JSON data could be replaces with an array output, stray objects are dangerous and not testable

**Comment by szepeviktor** [comment]
e.g. in WP_Auth0_Api_Client::create_client we may go two ways.

- WordPress says: failure is `false`
- PHP says: base value is `null`
- Modern OOP says: you need to throw and catch an exception!

**Comment by joshcanhelp** [comment]
> Variable $user need cleaner, testable logic

I'm open to suggestions. That entire method could use a better approach and I'm wary about changing logic just to pass a code style test. Feels like there are better places to focus effort. 

> WP_Auth0_Nonce_Handler needs to be final to be safe

That's extended by `WP_Auth0_State_Handler` (which is final)

> wc_get_page_id could be added as a stub

Or a guard on that method like `!function_exists('wc_get_page_id')`

> making an object from JSON data could be replaced with array output, stray objects are dangerous and not testable

All of the stuff in `WP_Auth0_Api_Client_Credentials->handle_response()` is internal so switching to an array is fine. It should return string or null so that wouldn't be breaking.

> WP_Auth0_Api_Client::create_client we may go two ways

Everything in that class should eventually move to how it's being done in, say, `WP_Auth0_Api_Change_Email`. I would not spend any time refactoring methods in that class. 

A lot of our error handling is legacy/inconsistent, no arguments there! Keep in mind, though, that the developer interaction with this plugin is far less often calling these class methods directly. Also, WordPress is far from modern OOP or modern PHP at all so there is some leeway there.

**Comment by szepeviktor** [comment]
> I'm wary about changing logic just to pass a code style test.

Excuse me!! PHPStan is a static analysis tool that has way more eyes than we humans do.

Wait for Level MAX.

**Comment by szepeviktor** [comment]
> Keep in mind, though, that the developer interaction with this plugin is far less often calling these class methods

I tell you my secret. Everything I do to this plugin is to make testable with PHPStan, so my inner QA engineer can live with it.

**Comment by szepeviktor** [comment]
### Conclusion

Many of the WordPress-realted abnormalities could be solved by installing 840 lines of code: https://github.com/thephpleague/container

(or [another container](https://rawgit.com/kocsismate/php-di-container-benchmarks/master/var/benchmark.html))

**Comment by joshcanhelp** [comment]
I'm open to seeing PRs that address this but refactoring code, particularly code that is not tested and has been around for a while, is not without risk. I understand that you want to improve the code base and I really appreciate that. We have to weigh the benefit of that improvement with the risk of making changes.

**Comment by szepeviktor** [comment]
Introducing a DI container could reduce our code as all lines dealing with instantiation could be simply removed.

**Comment by joshcanhelp** [comment]
Could you help me understand exactly what that means, in this context? Would we need breaking changes? Would the DX change? What are the main benefits we would get out of introducing that?

**Comment by szepeviktor** [comment]
things like

https://github.com/auth0/wp-auth0/blob/709ec491069d307b6f80c8268aacd7c3115c9dbf/lib/WP_Auth0_Options.php#L45-L53

could vanish right away

**Comment by joshcanhelp** [comment]
Sounds like a solid improvement. Happy to take a look at a PR. I would start small, though, so the review burden isn't too high. 

Appreciate your work here in advance!
