### ISSUE TITLE
Using custom redirect_to parmater

### ISSUE THREAD

**Issue by GuyAvraham** [auth0/wp-auth0#796]
On WP Admin panel - Auth0 settings:
![image](https://user-images.githubusercontent.com/4614438/82910342-3788f780-9f73-11ea-8e0b-0c687ebdf136.png)

The redirect_to dosent work well. 
Looks like my redirect after login always arrive to the setting above, 
even if i try:
https://mysite/wp-admin?redirect_to=mysite/somePath
Update: 
It works with 
https://mysite/wp-admin?redirect_to=/onlyRelativePath

**Comment by joshcanhelp** [comment]
@GuyAvraham - I'm guessing you solved your issue. Is there anything we can do here to avoid this issue in the future?

**Comment by GuyAvraham** [comment]
@joshcanhelp Thanks for looking up to improve. 
Maybe if we look at the image I pasted - a clear example of using the relative path will reduce the place for mistake.
