### ISSUE TITLE
Wordpress tries to auto login even when "Auto Login (no widget)" is unchecked

### ISSUE THREAD

**Issue by singularityjay** [auth0/wp-auth0#80]
Given the "Single Sign On (SSO)" is checked in the Auth0 settings and "Auto Login (no widget)" is unchecked.

To reproduce this issue:
1. Login via wordpress auth0 widget.
2. Logout (it only logs out of Wordpress not Auth0).
3. Go to http://[domain.com]/wp-login.php

The application now results in error:
Type: Failed Login
Description: http://[domain.com]/wp-login.php is not in the list of authorized callback URLs: http://[domain.com]/index.php?auth0=1. Please go to 'https://manage.auth0.com/#/applications/raFDFlsRPwMTbHT6Jyg7ZARG4QJVvkz6/settings' and make sure you are sending the same callback url from your application.
Connection: Username-Password-Authentication

**Comment by glena** [comment]
This is probably related to your change with the redirect to.

remove this lines in the logout action and tell me if it is still happening

```
        if (isset($_REQUEST['redirect_to']))
            $redirect_to = $_REQUEST['redirect_to'];
        else
            $redirect_to = home_url();
```

**Comment by glena** [comment]
I cant replicate this. 

Do you have a public url where I can check the issue?

The only way, this could happen is of you have enabled the Implicit Flow, in this case, you need to add this url as a valid callback (seems to be missing from the docs, I am adding this).
