### ISSUE TITLE
4.1.1  Email init error

### ISSUE THREAD

**Issue by tonygil** [auth0/wp-auth0#807]
Hi Guys
Had a problem with update  4.1.0 to 4.1.1
It broke the site.
Had to rollback to 4.1.0
[10:27] Gilpin, Tony
    
Fatal error: Uncaught Error: Call to a member function set_account_name() on bool in /var/www/html/wp-content/themes/Divi/core/components/api/email/init.php:26 Stack trace: #0 /var/www/html/wp-content/themes/Divi/core/components/api/email/init.php(6): et_core_api_email_fetch_all_lists() #1 /var/www/html/wp-content/themes/Divi/core/functions.php(338): et_core_api_email_init() #2 /var/www/html/wp-content/themes/Divi/core/functions.php(75): et_core_initialize_component_group('api_email', '/var/www/html/w...') #3 [internal function]: et_core_autoloader('ET_Core_API_Ema...') #4 /var/www/html/wp-content/plugins/bloom/bloom.php(191): spl_autoload_call('ET_Core_API_Ema...') #5 /var/www/html/wp-content/plugins/bloom/bloom.php(167): ET_Bloom->maybe_load_core() #6 /var/www/html/wp-content/plugins/bloom/bloom.php(5349): ET_Bloom->__construct() #7 /var/www/html/wp-includes/class-wp-hook.php(287): et_bloom_init_plugin('') #8 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #9 /var/www/html/wp-includ in /var/www/html/wp-content/themes/Divi/core/components/api/email/init.php on line 26

**Comment by evansims** [comment]
Hi Tony 👋  I'm not familiar with the theme you're running there, but looking at the error, it appears to be doing some custom email registration process? Did you see this error when a specific action was done on the site, or was it on page load? Also can you tell me what WP and PHP versions? Thanks.

**Comment by fuadhn** [comment]
Fatal error: Uncaught Error: Call to a member function set_account_name() on bool

I have same error on my website. Can you help me please

**Comment by evansims** [comment]
Hi @fuadhn, I can help. Please create a new issue and describe your issue in detail. I'll need to know your WordPress and PHP versions, what version of the plugin you're using, if you're using some sort of custom theme, and under what conditions you see the error happening. Thanks!
