### ISSUE TITLE
Extra Settings for Universal Login

### ISSUE THREAD

**Issue by a7i** [auth0/wp-auth0#809]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Currently the **Extra Settings** option is only allowed for the Embedded configuration (i.e. Lock). I would like to provide additional parameters to the /authorize URL for the Custom Login page. However, this setting is not available for Custom Login today.

### Describe the ideal solution

> A clear and concise description of what you want to happen.

It would be ideal to have a setting that allows for providing additional parameters to the authorize URL (e.g. audience, lang, theme, etc.) which can be used in the Custom Login Page.

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

There is currently no workaround for this issue.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by evansims** [comment]
Hey @a7i 👋 Thanks for the suggestion. This is an interesting idea, I'll explore this and see if it's viable here.

**Comment by evansims** [comment]
Hey again @a7i 👋 Sorry for the delay. I've researched this request and have created a backlog internally for this work, slated for the next major release of the WP plugin. It will require some foundational work to support within the plugin to implement in a satisfactory way.

For the moment, I'd recommend creating your own filter to customize the plugin, allowing you to add parameters to the /authorize request to meet your needs. You can see an [example hook here](https://github.com/auth0/wp-auth0/blob/master/examples/auth0_authorize_url_params.php)
