### ISSUE TITLE
Add filter(s) to allow storing Auth0 user data somewhere other than in usermeta

### ISSUE THREAD

**Issue by tharsheblows** [auth0/wp-auth0#811]
### Describe the problem you'd like to have solved

It would be useful for sites with large numbers of users to be able to avoid the `get_users` call in `WP_Auth0_UsersRepo->find_auth0_user()` as it searches over unindexed meta values in the usermeta table. 

Ideally, there would also be filters in `WP_Auth0_UsersRepo->get_meta()`, `WP_Auth0_UsersRepo->update_meta()` and `WP_Auth0_UsersRepo->delete_meta()` to keep all of the data together. 

### Describe the ideal solution

Adding filters which short circuit the functions if a value is returned. Eg for `find_auth0_user`:
`$check = apply_filters( 'find_auth0_user', null, $id );
if( ! empty( $check ) ){
return $check;
} 
...`

and similar ones for the meta wrappers in the same class. These could be used to put the Auth0 user data in a custom table with an index on the user Auth0 id.

## Alternatives and current work-arounds

Currently it's straightforward to work around the meta data requests with WordPress filters but the `get_users()` method is a bit trickier and to filter you'd need to dig further into user query which would get ugly. (I have not done this but there is no easily accessible filter.)

### Additional information, if any

I think the meta data methods / wrappers for eg `get_${object}_metadata` should have their own filter as it reminds future developers that some people might be using other sources of data. (Eg if this plugin ever went to custom tables, filters on getting the metadata would break whereas if there were a filter used as a short circuit check that someone was using, it wouldn't matter.)

**Comment by evansims** [comment]
Hey @tharsheblows 👋 Thanks for your suggestion! That sounds like a reasonable request to me. I'm a bit tight on bandwidth at the moment but I'll try to get to this as soon as I'm able to, or if anyone would like to contribute a PR that would be most welcome too.

**Comment by tharsheblows** [comment]
@evansims Awesome, thank you. I'm happy to contribute a PR and will do that soon. I'm having trouble with phpunit here but think that this is a known issue: [Uncaught Exception: Serialization of 'Closure' is not allowed when run PHPUnit in plugin development](https://core.trac.wordpress.org/ticket/50482#comment:13)

Is that it ok to submit a PR without tests? I don't want to submit tests that fail because I've written them wrong and haven't been able to test them to find out! 😁

**Comment by evansims** [comment]
@tharsheblows A PR on that would be very much appreciated! Sure, feel free to submit without tests if need be. I'll take a look once the PR is up and see what can be done about them. 👍 Thanks in advance for your help

**Comment by tharsheblows** [comment]
@evansims The tests almost work, some of them need `@preserveGlobalState disabled` in addition to `@runInSeparateProcess` (thus far -- I'm one class in `TestConstantSettings` -- it's `new WP_Auth0_Options()` causing the issue). I'm going to go ahead and "fix" (in quotes because I'm not entirely sure) those so I can test for myself and see what happens. 

But I'm nearly done for the day and will do this when I get back to it anyway because I'm curious, no need to reply right away even if it's not the best idea 😊

**Comment by tharsheblows** [comment]
I'm sorry for the off-topicness of this but there's a fix here: https://core.trac.wordpress.org/attachment/ticket/50482/50482.diff -- for me, applying to my WP test install makes everything work again. (The `post-format` theme registration was the culprit 😊). So I will add tests and see if it all works then do a PR soon.

**Comment by evansims** [comment]
No apologies necessary, I appreciate you working on this! Looking forward to it! 👍

**Comment by evansims** [comment]
Thanks for your help on this, @tharsheblows! This has been merged and will be part of the next release
