### ISSUE TITLE
Can't validate session because of string|array|object conversion

### ISSUE THREAD

**Issue by bruno-barros** [auth0/wp-auth0#818]
### Describe the problem

I'm integrating on a staging environment. Everything seems to be configured, but at the end of process I get "Ivalid ID token".
The problem happens after auttentication during the redirection process inside WP.

### What was the expected behavior?

After log user in, redirect to my home page.

### Reproduction

Debugging the Auth0 plugin I resolved the problem type casting the return of `$verifiedToken->getClaim` method. Only this action gets the job done.
See the changes I made:

    // auth0/lib/WP_Auth0_UsersRepo.php
    $current_auth0_id = (string) self::get_meta( $user_id, 'auth0_id' );

    // auth0/lib/token-verifier/WP_Auth0_IdTokenVerifier.php
    $tokenIss = (string) $verifiedToken->getClaim( 'iss', false );
    $tokenSub = (string) $verifiedToken->getClaim( 'sub', false );
    $tokenAud = (string) $verifiedToken->getClaim( 'aud', false );
    $tokenExp = (int) $verifiedToken->getClaim( 'exp', false );
    $tokenIat = (int) $verifiedToken->getClaim( 'iat', false );
    $tokenNonce = (string) $verifiedToken->getClaim( 'nonce', false );

The plugin do validations with the result, but getClaim returns a object.

### Environment

WP: 5.6
PHP: 7.3.26
Login via Auth0: 4.1.1

**Comment by evansims** [comment]
Hey, @bruno-barros! Thanks for raising this 👋 

That's a strange one! I'm not sure why you'd be hitting type errors there; those should be the expected types already being returned in any cases I can really think of. This is more or less the same verification flow copied over from our main PHP SDK. I've not seen this one reported before. I cannot reproduce this using the same WP version and PHP runtime on my end, so I'm scratching my head on this one.

I'm glad these changes fixed things for you, at any rate! One word of caution, there are some cases in which `aud` could potentially be an array, so you might want to reconsider that particular tweak.
