### ISSUE TITLE
Publish to packagist 🙏

### ISSUE THREAD

**Issue by roborourke** [auth0/wp-auth0#823]
### Describe the problem you'd like to have solved

Hey, I was wondering if you would consider publishing this plugin to packagist.org too? Great to see it you have it set up for wpackagist but I have a use-case where that isn't an option.

If I wanted to have this plugin as a dependency of another package then I _have_ to get it from packagist.org as dependencies can't specify custom repositories in their `composer.json`.

### Describe the ideal solution

It looks like there's no extra build step beyond installing composer dependencies which wouldn't be needed for a packagist install.

From what I can tell the line that includes the `vendor/autoload.php` just needs to wrapped in a file exists check eg:

```
if ( is_readable( __DIR__ . '/vendor/autoload.php' ) ) {
    require_once __DIR__ . '/vendor/autoload.php';
}
```

If you approve of the idea and it doesn't require any further complex build processes (thinking client side assets) then I'm happy to make the PR for the above change.

**Comment by evansims** [comment]
Hey, @roborourke 👋 Thanks for the suggestion! That request makes perfect sense to me. If you'd like to put a PR together for that it'd be greatly appreciated!

**Comment by evansims** [comment]
Merged, thanks!
