### ISSUE TITLE
Signup support in New Universal Login Experience

### ISSUE THREAD

**Issue by yaymalaga** [auth0/wp-auth0#826]
### Describe the problem you'd like to have solved

I enabled the signup in WP and even though the signup link becomes `/wp-login.php?action=register` I am still redirected to Auth0's login page. 

### Describe the ideal solution

I should be redirected to Auth's signup page instead.

## Alternatives and current work-arounds

A filter can be created to read the `action` parameter and then inject `screen_hint=signup`:

```php
function add_signup( $auth_url, $auth_params ) {
	if ( isset( $_GET['action'] ) && 'register' === $_GET['action'] ) {
		$auth_url .= '&screen_hint=signup';
    }

	return $auth_url;
}
add_filter( 'auth0_authorize_url', 'add_signup', 10, 2 );
```

**Comment by evansims** [comment]
👋  Hey @yaymalaga and thanks for raising this. Have a few big items on my plate this week I'm working on, but I'll look into this as soon as possible and get back to you.

**Comment by evansims** [comment]
Hey, @yaymalaga 👋 Sorry for the delay. I've created a backlog ticket for this work, as there's a number of improvements we'd like to slate around support for the new Universal Login experience in the next major release of the plugin. In the meantime, the workaround you mentioned is the best way to go about this, so thank you for sharing it!
