### ISSUE TITLE
Auto redirect on preview post pages

### ISSUE THREAD

**Issue by barclayadam** [auth0/wp-auth0#83]
We have enabled auto-redirect for our installation (i.e. going to /admin will not request login credentials just send us round to WAAD for authentication).

Is it possible to intercept requests to preview a post and automatically log in? At the moment I just hit the homepage and a 404 request. Hitting http://blog.timestamphq.com/?p=4581&preview=true  when not logged in ends up at http://blog.timestamphq.com/?p=4581 and a 404 page.

**Comment by glena** [comment]
This a WordPress behaviour. If you are not logged in, a preview url `http://vagrantpress.dev/?p=19&preview=true` gets redirected to the post url `http://vagrantpress.dev/?p=19` without showing the login form.

About intercepting the request, I prefer to maintain the WP behaviour in this cases (I think this is more consistent for crawlers, etc);
