### ISSUE TITLE
JWT Access Token - Custom Audience

### ISSUE THREAD

**Issue by the133448** [auth0/wp-auth0#830]
We have noticed that the Access Token being generated is not in the form of a JWT Token, it is a much shorter Opaque token, which whilst able to access the `userinfo` endpoint, is not able to access a custom API we have added to Auth0.

To fix this I believe we need to adjust the audience field that this plugin is creating, in particular [here](https://github.com/auth0/wp-auth0/blob/b5528166700686862a649616eaea359616b052fc/lib/WP_Auth0_Api_Client.php#L64) . If we add our custom API here, then I believe Auth0 would return a access token in the form of a JWT token, but still have access to the user management API in the audience field. 

Is our thinking correct? If so, is it possible to make the [audience here](https://github.com/auth0/wp-auth0/blob/b5528166700686862a649616eaea359616b052fc/lib/WP_Auth0_Api_Client.php#L64) configurable? 

Or is there already a configurable to add a custom Audience to ensure we get back a JWT Token

**Comment by the133448** [comment]
Update, I have discovered in Auth0 Tenant Settings > API Authorization Settings, there is the ability to declare a Default Audience which correctly returns the JWT token.

So, perhaps let me update this feature request to make it configurable to request multiple audiences?

**Comment by evansims** [comment]
Hey @the133448 👋 Thanks for reporting this; I'm out on holiday this week but I'll take a look at this as soon as I can when I return. (Sorry not to have anything to report yet, just didn't want to leave you hanging.)

**Comment by cocojoe** [comment]
@the133448 is this still something you need advice on? Thanks

**Comment by evansims** [comment]
Going to close this for now as it's gone stale; let us know if this is still an issue for you, and we can re-open.

**Comment by the133448** [comment]
Hi @evansims , we ran into this again, we have multiple applications now so ideally we don't want to use the Default Audience under the tenant settings as this impacts our other applications.

**Comment by the133448** [comment]
HI @evansims would you be able to reopen this?

**Comment by evansims** [comment]
Hi @the133448 👋 Thanks for the update. Support for multiple audiences is on our radar for the next major release, but we don't currently havec an timetable for this that I can offer/
