### ISSUE TITLE
WordPress function get_avatar_url() returns the default WP user avatar and not the auth0 avatar

### ISSUE THREAD

**Issue by Simon-ProjectPartners** [auth0/wp-auth0#837]
### Describe the problem

Native WordPress functions that get the user avatar, such as `get_avatar_url()` don't return the auth0 avatar.

### What was the expected behavior?

`get_avatar_url()` should return the auth0 avatar.

### Reproduction

Call `<img src="<?php echo get_avatar_url(); ?> >` in any WP template file. 

Install WP Auth0.

Create new user.

Log in with e.g Azure AD.

Auth0 avatars can be seen on the "Users" admin page of the WordPress dashboard, but `get_avatar_url()` still shows the default WP user avatar.

### Environment

- **Version of this library used:** Latest
- **Which framework are you using, if applicable:** `_s` WordPress theme
- **Other modules/plugins/libraries that might be involved:** -
- **Any other relevant information you think would be useful:** -

**Comment by evansims** [comment]
Hi @Simon-ProjectPartners 👋 Have you enabled the Auth0 configuration option to override avatars?

**Comment by Simon-ProjectPartners** [comment]
Hi @evansims 👋

Thanks for getting back to me. Yes, I did.

Ohh I see, will try my luck with `get_avatar()`. Thanks!
