### ISSUE TITLE
Error on Activation

### ISSUE THREAD

**Issue by Krammig** [auth0/wp-auth0#838]
Hope the following is helpful as I am curious to try this plugin. 

IIS Windows 7 
PHP 7.3.1.0
FastCGI

`Fatal error: Uncaught Error: Class 'WP_Auth0_Options' not found in G:\RainbowWeb\test\httpdocs\wp-content\plugins\wp-auth0-master\WP_Auth0.php:83 Stack trace: #0 G:\RainbowWeb\test\httpdocs\wp-includes\class-wp-hook.php(303): wp_auth0_activation_hook('') #1 G:\RainbowWeb\test\httpdocs\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) #2 G:\RainbowWeb\test\httpdocs\wp-includes\plugin.php(470): WP_Hook->do_action(Array) #3 G:\RainbowWeb\test\httpdocs\wp-admin\plugins.php(193): do_action('activate_wp-aut...') #4 {main} thrown in G:\RainbowWeb\test\httpdocs\wp-content\plugins\wp-auth0-master\WP_Auth0.php on line 83
`

**Comment by evansims** [comment]
Hi @Krammig 👋 We've never tested the plugin under IIS, but I don't expect there would be any particular issues with that.

- Are you running 4.3.1? 
- Did you install manually, or from the WordPress plugin dashboard?
- Can you show me what your directory structure for the plugin looks like?

It sounds like, for whatever reason, your WordPress is not importing all the required plugin files properly.

**Comment by evansims** [comment]
Closing for now, but let me know if this is still an issue for you and we can dignose it further.

**Comment by lukemalcolm** [comment]
I hit the same issue with release 4.4.0 running on PHP 7.3 (linux/apache). I had to do two things to make this work.

In composer.json change the PHP requirement from 7.4 to 7.3.

` "require": {
    "php": "^7.3 || ^8.0",
`
    
Then I had to call `composer2 install`.
