### ISSUE TITLE
Use custom domain for Auth0 API if present

### ISSUE THREAD

**Issue by edmundcwm** [auth0/wp-auth0#840]
### Describe the problem you'd like to have solved
Currently the `WP_Auth0_Api_Abstract` class sets the `$domain` property to the [domain field in the settings page](https://github.com/auth0/wp-auth0/blob/master/lib/api/WP_Auth0_Api_Abstract.php#L116) by using `$this->options->get( 'domain' );`. 

If we want to use a **custom domain**, we'd need to use `$this->options->get_auth_domain()` as the 2nd parameter when instantiating an instance of the abstract class i.e., ` new WP_Auth0_Api_Refresh_Access_Token( $auth0_options, $auth0_options->get_auth_domain() );`

In the abstract class, can we set `this->domain` to `$this->options->get_auth_domain()` instead? This will enable the use of a custom domain if one exists and fallback to the main domain if there isn't any.

### Describe the ideal solution
In the `WP_Auth0_Api_Abstract` class, set `this->domain` to `$this->options->get_auth_domain()` which allows the use of custom domain if it exists or fallback to using the main domain.

**Comment by evansims** [comment]
Hi @edmundcwm, thanks for your request! Let me investigate if this is something we can slip in to a new release short term

**Comment by evansims** [comment]
Hey again @edmundcwm! Sorry for the delay 👋 Thanks for your suggestion, and I entirely agree this is how this should be getting handled automatically by the class. Unfortunately, we can't introduce this change as a simple merge as it would be considered a breaking change on the behavior, but I've backlogged this for us to implement in the next major update to the library.

P.S. Although I'm closing your ticket, I assure you were are not dismissing the suggestion; we just have a policy of not leaving feature request tickets open once they are backlogged internally.
