### ISSUE TITLE
Does not handle last names with spaces

### ISSUE THREAD

**Issue by BetterAutomations** [auth0/wp-auth0#841]
### Describe the problem
> My first name is 'Christopher' and last name is 'de Vidal' but upon login to Wordpress with Google authentication it registered my first name as 'Christopher de' and last name as 'Vidal'.

### What was the expected behavior?
> First name should have been 'Christopher' and last name 'de Vidal'

### Reproduction
> Create or modify a Google account so that the person's last name has a space. You can use my last name.
> Screenshot: https://i.imgur.com/OOVtLro.png

### Environment
- **Version of this library used:** WordPress plugin 4.3.1
- **Which framework are you using, if applicable:** WordPress 5.8.2
- **Other modules/plugins/libraries that might be involved:** N/A
- **Any other relevant information you think would be useful:** N/A

**Comment by evansims** [comment]
Hi @BetterAutomations 👋 At the moment, we don't have a solution that will handle situations like this automatically for you. As, often, individuals may have first names with spaces as well, there's no one-size-fits-all solution we can offer. Our current method addresses most names, but when situations like this arise, you will need to manually update users to fix those on a case-by-case basis.
