### ISSUE TITLE
composer.json requires PHP 7.4 but readme.txt says 7.3

### ISSUE THREAD

**Issue by lukemalcolm** [auth0/wp-auth0#844]
The readme.txt file calls out for:

_Requires PHP: 7.3_

In composer.json it asks for 7.4 and composer blocks on installation on PHP 7.3

` "require": {
    "php": "^7.4 || ^8.0",
`

EDIT: This is in 4.4.0

**Comment by evansims** [comment]
Hi @lukemalcolm thanks for the heads-up, I've updated the readme.txt file and will cut a bugfix release upping that. As a policy Auth0 only supports PHP runtimes [that are supported by PHP itself](https://www.php.net/supported-versions.php), and 7.3 was deprecated last December. Sorry for the confusion!
