### ISSUE TITLE
Auth0 documentation ("Integrate with WordPress") should be updated after removal of Implicit Flow login

### ISSUE THREAD

**Issue by jcerjak** [auth0/wp-auth0#845]
### Describe the problem

In #735 (which was released in 4.0.0) the implicit login flow was removed. However the Auth0 documentation still mentions that it is supported: https://auth0.com/docs/customize/integrations/cms/wordpress-plugin/integrate-with-wordpress

> The actual login process differs whether you are using the Authorization Code Flow or the Implicit Flow ("Implicit Login Flow" on the Advanced tab of the plugin settings is turned off for the former, on for the latter)

I cannot see the "Implicit Login Flow" option either in the Advanced tab in version 4.3.1.

### What was the expected behavior?

Documentation is updated after changing plugin behavior.

### Reproduction

See "Describe the problem" section.

### Environment

- **Version of this library used:** 4.3.1
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by evansims** [comment]
Thanks @jcerjak, I'll raise this with our documentation team.
