### ISSUE TITLE
4.4.0 not on public WP repo

### ISSUE THREAD

**Issue by blakmarkit** [auth0/wp-auth0#850]
Thanks, @jcerjak. I'm not sure why I didn't populate up to WP.org, but I'll manually push a release to it this week.

_Originally posted by @evansims in https://github.com/auth0/wp-auth0/issues/846#issuecomment-1098053786_

There is a closed issue with the above comment that seems to indicate that the latest version here has been released on the WP plugin repo, but that doesn't appear to have happened yet. The last release is 4.3.1 from a year ago.

**Comment by evansims** [comment]
Hey @blakmarkit 👋 Thanks for creating this issue. It's definitely on my radar, but I'm holding off until I wrap up the next release of the plugin to push an update, as that has taken priority. In the meantime you should be able to manually update using a downloaded ZIP from the GitHub repo. Thanks.
