### ISSUE TITLE
Integration with "members" plugin

### ISSUE THREAD

**Issue by JUVOJustin** [auth0/wp-auth0#856]
### Describe the problem you'd like to have solved
Add a little integration with the [wordpress members plugin](https://wordpress.org/plugins/members/) which allows make the site only accessible after a user logged in. When enabling the "private site" feature in members alongside using auth0 an endless redirect loop occurs.  I have already created an [issue at the members repository](https://github.com/caseproof/members/issues/83). I am not sure if you or them want to add third party integrations. If not, it is probably nice to have the workaround documented here too. I would love to see this baked in, since other plugins will create similar issues e.g. buddyboss.

### Describe the ideal solution
For v4 i created the following code which hooks into members. What i dont know is if the url parameters are future-proof for version 5.
```php
add_filter('members_is_private_page', function(bool $is_private) {

    // Check if installed. Different constants for v4 and v5 of auth0 wordpress plugin
    if (!defined('WP_AUTH0_VERSION') && !defined('WPA0_VERSION')) {
        return $is_private;
    }

    // Check for url parameters
    if (
        empty($_GET['auth0']) || $_GET['auth0'] != "1"
        || empty($_GET['code'])
        || empty($_GET['state'])
    ) {
        return $is_private;
    }

    return false;
});
```

**Comment by evansims** [comment]
Hey @JUVOJustin! 👋 Thanks for your suggestion, and offering the snippet and advice for others seeking similar integrations! Adding integration support around this specific use case isn't planned right now, but I'll backlog researching this for future consideration. 👍
