### ISSUE TITLE
Priority of the wp_auth0_process_auth_callback

### ISSUE THREAD

**Issue by korobochkin** [auth0/wp-auth0#858]
### Describe the problem you'd like to have solved

This topic seems related only for 4.* versions.

I noticed that the `wp_auth0_process_auth_callback` is attached to WordPress by the `template_redirect` event (action). **Is there any reason for so late invocation?** The `template_redirect` fires after WordPress loads posts from `wp_posts` table (+ post meta).

```php
// In the 4.4.0
add_action( 'template_redirect', 'wp_auth0_process_auth_callback', 1 );
```

### Describe the ideal solution

I tried to use `wp_loaded` event instead of `template_redirect` locally. Works well for my test setup and there are no signs that the code may fail. All required classes and objects on the WordPress side are loaded. However, I'm _not 100% sure_ that all the other parts of the plugin will work perfectly.

```php
add_action('plugins_loaded', function () {
  if (remove_action('template_redirect', 'wp_auth0_process_auth_callback', 1)) {
    add_action('wp_loaded', 'wp_auth0_process_auth_callback', 1);
  }
});
```

### Additional information, if any

Some users/developers may use the current logic of attaching the `wp_auth0_process_auth_callback`. Changing priority may break their code. Inside the `wp_auth0_process_auth_callback()` call you may find at least the following filters:
- `apply_filters( 'auth0_get_auto_login_connection', $this->a0_options->get( 'auto_login_method' ) )`
- `apply_filters( 'auth0_use_management_api_for_userinfo', true )`
- `apply_filters( 'auth0_get_wp_user', $user, $userinfo )`
- `apply_filters( 'wp_auth0_get_option', $value, $key )`

**Comment by evansims** [comment]
Hey @korobochkin 👋 Thanks for your question!

To be totally honest, I'm not certain what influenced the decision behind that action being invoked so late in the hooks lifecycle. 🤔 Much of V4's development was before my time with the company, I'm afraid. Sadly, as you noted, changing it would potentially introduce a breaking change for those relying on it.

Your workaround appears solid, though, and I would anticipate it working as you're expecting just fine.
