### ISSUE TITLE
redirect_to param in auth0 shortcode not working

### ISSUE THREAD

**Issue by maxi07** [auth0/wp-auth0#870]
### Describe the problem

The auth0 wordpress shortcode redirection param does not work for me.

### What was the expected behavior?

I added the redirect_to param into the shortcode to redirect the user to a specific site after successfull authenfication. But after signing in, i get redirected to the main page.

### Reproduction

The shortcode used is `[auth0 form_title="Please login on my WP blog" redirect_to="https://mycustomsite.com"]`. The formtitle is being changed, so the params seem to work in general.

### Environment

- **Version of this library used:** Login by Auth0 4.5.0
- **Wordpress:** 6.1.1

**Comment by evansims** [comment]
Hi @maxi07 👋 Thanks for reaching out! So, I've tested the shortcut with 4.5.0, but unfortunately I wasn't able to reproduce the issue you're seeing. In my test:

```markdown
[auth0 form_title="Please login on my WP blog" redirect_to="https://wordpress.test/homepage"]
```

Correctly redirects to the URL specified. Can you confirm you are assigning `redirect_to` to an absolute URL served by the same WordPress site, at the same domain?

**Comment by maxi07** [comment]
Hi @evansims, no the redirect_to currently points to an external site. Does the redirect param only only work with sites from the same domain?

**Comment by evansims** [comment]
Hi @maxi07 — that's correct, the parameter needs to point to a path on the same domain.

**Comment by maxi07** [comment]
Thanks, I couldn't find that information in the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin/configure-login-by-auth0#advanced).
