### ISSUE TITLE
Save Button Missing and WordPress Technical Issue Notice 

### ISSUE THREAD

**Issue by aleskozelsky** [auth0/wp-auth0#875]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have installed the plugin on a WP install. All works fine initially, but when I try to change any settings after the getting started, the Save button is missing and I get an email (even when just visiting the admin pages) 

Error Details
=============
An error of type E_ERROR was caused in line 128 of the file /var/www/laizy-24/wp-content/plugins/auth0/lib/WP_Auth0_Ip_Check.php. Error message: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /var/www/laizy-24/wp-content/plugins/auth0/lib/WP_Auth0_Ip_Check.php:128
Stack trace:
#0 /var/www/laizy-24/wp-content/plugins/auth0/lib/WP_Auth0_Ip_Check.php(128): implode()
#1 /var/www/laizy-24/wp-content/plugins/auth0/lib/WP_Auth0_Ip_Check.php(115): WP_Auth0_Ip_Check->get_ip_by_region()
#2 /var/www/laizy-24/wp-content/plugins/auth0/lib/admin/WP_Auth0_Admin_Advanced.php(355): WP_Auth0_Ip_Check->get_ips_by_domain()
#3 /var/www/laizy-24/wp-admin/includes/template.php(1785): WP_Auth0_Admin_Advanced->render_migration_ws_ips()
#4 /var/www/laizy-24/wp-admin/includes/template.php(1739): do_settings_fields()
#5 /var/www/laizy-24/wp-content/plugins/auth0/templates/settings.php(33): do_settings_sections()
#6 /var/www/laizy-24/wp-content/plugins/auth0/lib/admin/WP_Auth0_Admin.php(142): include('...')
#7 /var/www/laizy-24/wp-includes/class-wp-hook.php(308): WP_Auth0_Admin->render_settings_page()
#8 /var/www/laizy-24/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#9 /var/www/laizy-24/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /var/www/laizy-24/wp-admin/admin.php(259): do_action()
#11 {main}
  thrown

### Reproduction

1. Step 1 Install Auth0 Login WP plugin
2. Follow the steps (enter the Tenant + Client ID
3. Save 
4. Error appears, no "Save" button is visible

### wp-auth0 version

3.0.0

### WordPress version

6.2.x

### PHP version

8.02x

**Comment by evansims** [comment]
Hey @aleskozelsky 👋 Sorry to hear you're hitting an issue there.

Can you share what you have set your domain to, minus your account name? I'm curious about the tenant region portion of the URI, in particular.

**Comment by aleskozelsky** [comment]
Hi Evansims, 

Thanks for looking after this! 

Tenant Name laizy31
Region UK-1

**Comment by evansims** [comment]
Thanks, @aleskozelsky — can you tell me what your tenant domain is (as in, how the `domain` field is formatted when you examine [one of your applications' details.](https://manage.auth0.com/#/applications))

**Comment by aleskozelsky** [comment]
I hope that you are after the "laizy31.uk.auth0.com" field?

**Comment by evansims** [comment]
Closing as the version of the plugin in question is deprecated.
