### ISSUE TITLE
Missing User Agent

### ISSUE THREAD

**Issue by metinucar** [auth0/wp-auth0#876]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We're doing user migrations in login and have both Auth0 plugin and database configured properly. This has been working fine but recently our hosting platform, WP Engine, implemented a security feature that blocks requests that do not contain User Agent information.

Apparently the endpoint `/index.php?a0_action=migration-ws-get-user` doesn't contain User Agent details at user creation and gets blocked. This results in users not being able to create account on our website.

WP Engine has implemented a temporary fix for 90 days and force us to make sure the request contains User Agent. So, I'm turning to you to see what you can do on plugin and Auth0 end to provide what they need in order to have a stable connection.

Thank you

### Reproduction

1. User clicks on login link on our website and then taken to the Universal Login page hosted on Auth0
2. User enters email and password to create an account
3. User receives something went wrong error message

### wp-auth0 version

4.5.0

### WordPress version

6.2.2

### PHP version

7.4

**Comment by evansims** [comment]
Hey @metinucar 👋 Thanks for your feature request. Give me a bit to review this and see what we can do to improve things for you here.

**Comment by BryanSaxon** [comment]
Having this issue as well. @metinucar, how did you modify your script to send a valid user agent? Passing through the headers isn't working for us.

**Comment by metinucar** [comment]
@BryanSaxon We couldn't do anything on our end. We asked our hosting provider to relax their rules about User Agents temporarily for 90 days. Waiting @evansims and the team to come up with a permanent solution.

**Comment by metinucar** [comment]
@evansims Thank you for looking into this. Is there any update?

**Comment by evansims** [comment]
Hi @metinucar, with v4 of the plugin exiting support, I'm afraid we won't be making any additional changes to that release at this time. v5 is currently available from the GitHub repository and will be offered as a direct upgrade from v4 on the Marketplace in the next few weeks.

**Comment by monjohn** [comment]
I don't see it added to the Marketplace yet. Any update?
