### ISSUE TITLE
not compaitable on woocommerce

### ISSUE THREAD

**Issue by itsmemidhuz123** [auth0/wp-auth0#879]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Sir, we have. woocommece website and tried using the plugin. It works perfectly on wordpress login but doesn't works on woocommerce. How do we able to use it for woocommere to be compatible, so when we visit example.com/my-account the auth0 login page needs to be appeared

help on this please

### Reproduction

visiting to website 
visiting woocommerce login

### wp-auth0 version

latest

### WordPress version

latest

### PHP version

8.2

**Comment by itsmemidhuz123** [comment]
I just found one solution to redirect through cloudflare but it may take some additional time to redirect 

Is there any solution plugin that can replace the woocommerce login page to auth0 login automatically

Also is it possible to redirect the user back to the same page where they came from

Best, Midhun

**Comment by evansims** [comment]
Hi @itsmemidhuz123, we do not currently support WooCommerce, although it is in our radar for eventual support. I'm afraid I don't have enough familiarity with the platform to offer guidance on this front, but you might reach out to the [Auth0 Community and ask there.](https://community.auth0.com)
