### ISSUE TITLE
PSR CacheItemItemface is incompatible with WpObjectCacheItem Error

### ISSUE THREAD

**Issue by u382514** [auth0/wp-auth0#880]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Receiving the following error when trying to login and redirecting back: 
```
Fatal error: Declaration of Auth0\WordPress\Cache\WpObjectCacheItem::expiresAt(?DateTimeInterface $expiration) must be compatible with Psr\Cache\CacheItemInterface::expiresAt(?DateTimeInterface $expiration): static in /var/www/html/web/app/plugins/wordpress/vendor/auth0/wordpress/src/Cache/WpObjectCacheItem.php on line 45
```

The function in the PSR CacheItemInterface.php file is showing static like this: 
```
public function expiresAt(?\DateTimeInterface $expiration): static;
```

while the function in the WpObjectCacheItem.php file under Auth0 does not: 
```
public function expiresAt(?\DateTimeInterface $expiration)
    {
        if ($expiration instanceof DateTimeInterface) {
            $this->expires = $expiration->getTimestamp();
            return $this;
        }

        $this->expires = $expiration;
        return $this;
    }
```

If I add the ':static' to the Auth0 function, it works. 

### Reproduction

1. Install fresh Bedrock
2. Run ```composer require symfony/http-client nyholm/psr7 auth0/wordpress:^5.0``` on the root
3. Go into Auth0's wpAuth0.php and change the '// load dependencies' line to the correct vendor/autoload.php. This is because it is weirdly hardcoded instead of discovering the location. Will bring up in separate issue. 
4. Do all the Auth0 configs necessary. 
5. Try signing in. 

### Additional context

The composer require after running the composer command: 
```
{
    "require": {
        "symfony/http-client": "^6.0",
        "nyholm/psr7": "^1.8",
        "auth0/wordpress": "^5.0"
    }
}
```

### wp-auth0 version

5.1

### WordPress version

Latest Bedrock

### PHP version

8.2.8

**Comment by evansims** [comment]
Hi @u382514 👋 Thanks for raising this, I'll check into it and get back to you

**Comment by evansims** [comment]
Hi @u382514, as you noticed, v3 of the PSR-6 interface implemented a breaking change requiring return value types, but the plugin was designed to target v1 || v2. I'll look into updating this soon if it can be done in a way that doesn't break v1 and v2 compatibility. Otherwise, we will need to restrict version support to those previous versions.

**Comment by evansims** [comment]
Hey @u382514 👋 Thanks for your patience while we investigated this. I can confirm a fix has been committed and will ship as part of our next release.
