### ISSUE TITLE
The nonce validation stoped to work

### ISSUE THREAD

**Issue by bruno-barros** [auth0/wp-auth0#884]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I was using the version 3. Then I updated to the version 5.1 and the PHP to 8.0.
I'm on WP 6.4.

The authentication with Auth0 is working, but the nonce validation just stoped to work. I tested disabling the Auth plugin and the problem has gone.

I trie to do any action on admin panel and the nonce do not validate. I tried different configuration options, but nothing works.
Maybe I'm missing somethng here.

### Reproduction

1. Activate Auth0
2. Login in and visit any admi page
3. Try to update anything
4. Got error message "nonce expired", "link is not valid", etc.

### wp-auth0 version

5.1

### WordPress version

6.4

### PHP version

8.0

**Comment by evansims** [comment]
Hi @bruno-barros 👋 Do you have any other plugins enabled, aside from Auth0?

**Comment by bruno-barros** [comment]
Many more. A disabled the WP-Rocket (cache) and Wordfence (security) and the problem persists, but there are many others. I'll try to disable all of then but Auth0 to revalidate.

**Comment by bruno-barros** [comment]
Hi. I disabled every plugin but Auth0.
I loggued in with Auth0.
When the heartbeat try to validate any request:
```
interval: 60
_nonce: cb3c6a7ad0
action: heartbeat
screen_id: toplevel_page_auth0
has_focus: true
```
It returns:
```
heartbeat_nonce: "fd21dfbefb",
nonces_expired: true,
rest_nonce: "c8458e437e",
```

So, I disable the Auth0 plugin too and the problem validating nonces was gone. I did it without logout and login again.

Can you give some hint to where to look at? In some way the Auth0 plugin is interfering on nonces validation.

**Comment by bruno-barros** [comment]
I deactivated the option "rolling sessions" and seems to get the job done.

**Comment by evansims** [comment]
> In some way the Auth0 plugin is interfering on nonces validation.

The plugin doesn't intercept any nonce validation logic

> I deactivated the option "rolling sessions" and seems to get the job done.

Great! Glad you found a workaround 👍
