### ISSUE TITLE
Too many redirects when trying to log in

### ISSUE THREAD

**Issue by acaselli** [auth0/wp-auth0#888]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, I am having this problem since I have updated the plugin to the latest version. In the documentation you say "Allowed Callback URLs should include the URL to your WordPress site's wp-login.php" but I have always set it up to "/index.php?auth0=1". Has anything changed? If I set the Callback URL to /wp-login.php I get a mismatch Call URL error. And if I change it to "/index.php?auth0=1", I get a too many redirects error. I have deactivated all custom code and plugins but I am still unable to log in.

### Reproduction

1. In the auth0 application set Allowed Callback URLs to sitename.com/index.php?auth0=1
2. Log in to the site
3. After successfully entering the credentials, I get the message too many redirects
4. I have inspected the flow via the network tab of dev tools and I can see the URL is built like this:: https://sitename.com/wp-login.php?redirect_to=https%3A%2F%2Fsitename.com%2Fwp-login.php%3Fredirect_to%3Dhttps%253A%252F%252Fsitename.com%252Fwp-login.php%253Fredirect_to%253Dhttps%25253A%25252F%25252Fsitename.com%25252Fwp-login.php%25253Fredirect_to%25253Dhttps%2525253A%2525252F%2525252Fsitename.com%2525252Fwp-login.php%2525253Fredirect_to%2525253Dhttps%252525253A%252525252F%252525252Fsitename.com%252525252Findex.php%252525253Fauth0%252525253D1%2525252526code%252525253D5SOMECODEHERE%2525252526state%252525253LONGCODE%25252525253D%25252526reauth%2525253D1%252526reauth%25253D1%2526reauth%253D1%26reauth%3D1&reauth=1

### wp-auth0 version

4.6.0

### WordPress version

6.4.3

### PHP version

8.0

**Comment by evansims** [comment]
Hi @acaselli, thanks for raising this. v4 is no longer supported and will not receive changes beyond critical bug fixes. Please see https://github.com/auth0/wordpress?tab=readme-ov-file#support-policy. v5 is available here from the GitHub repository and will be rolled out to the WordPress marketplace in the near future.

**Comment by acaselli** [comment]
Hi @evansims, thank you for your prompt response and for the guidance regarding the plugin version. I understand that version 5 of the Auth0 WordPress plugin will soon be available on the WordPress marketplace. Could you please clarify what "in the near future" typically implies for your rollout schedules? Are we looking at a timeframe of a few weeks, or could it extend to a few months? Any specific timelines would help us plan our update strategies more effectively.

Appreciate your support and looking forward to your reply.
