### ISSUE TITLE
When activating Auth0 Plugin on Wordpress 6.5.3 I get a "You are not allowed to perform this action message"

### ISSUE THREAD

**Issue by leafwire** [auth0/wp-auth0#889]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I installed on my dev site the plugin while still on 6.4.2 - everything was great and the wizard showed up - we connected everything great. After testing, this week decided to do everything for prod. We have 6.4.3 version of wordpress. When we try to activate the plugin we are told that we are not allowed to perform this action. When we go back to the site - Autho plugin is installed but the wizard no longer shows up. 

### Reproduction

1. Add Auth0 plugin from WordPress library
2. Hit Activate
3. Taken to error page with message along the lines of "You do not have permission to perform this action..."
4. Go back
5. See auth0 plugin is installed
6. No more wizard popup
Wordpress version: 6.4.3. We deactivated ALL OTHER plugins to eliminate conflict.

### wp-auth0 version

4.6

### WordPress version

6.4.3

### PHP version

8.2.9

**Comment by evansims** [comment]
Hi @leafwire, thanks for raising this. v4 is no longer supported and will not receive changes beyond critical bug fixes. Please see https://github.com/auth0/wordpress?tab=readme-ov-file#support-policy. v5 is available here from the GitHub repository and will be rolled out to the WordPress marketplace in the near future.
