### ISSUE TITLE
Add filter for auto_login_params

### ISSUE THREAD

**Issue by steveerdelyi** [auth0/wp-auth0#890]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

There is currently no way to programmatically set the auto_login_params value (only configurable via Auth0 Settings > Features > Auto Login Parameters. Without a filter to programmatically set this value, I can only forward people to either the sign up page or the log in page, but not either or, depending on the current login flow.

### Describe the ideal solution

I was able to add a filter this on my local version of the plugin by editing line 456 of the file:
`/wp-content/plugins/auth0/lib/WP_Auth0_LoginManager.php`

By changing: `$customParams = trim( $opts->get( 'auto_login_params' ) ?? '' );` to:
`$customParams = trim( apply_filters( 'auth0_auto_login_params', null ) ?? $opts->get( 'auto_login_params' ) ?? '' );`

This allows me to then programmatically configure the auto_login_params value.

### Alternatives and current workarounds

The only way to set this value that I'm aware of is located in: Auth0 Settings > Features > Auto Login Parameters. The issue with this is it can only be set once and not changed based on the current flow the user is in.

**Comment by evansims** [comment]
Hi @steveerdelyi, Thanks for raising this. v4 is no longer supported and will not receive changes beyond critical bug fixes. Please see https://github.com/auth0/wordpress?tab=readme-ov-file#support-policy. v5 is available here from the GitHub repository and will be rolled out to the WordPress marketplace in the near future.
