### ISSUE TITLE
Add support for using a link to trigger sending password reset emails for a logged in User

### ISSUE THREAD

**Issue by jackton1** [auth0/wp-auth0#899]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'm using the UserWP plugin that manages a user account this includes a form that allows a user to change their existing password which only works on the WordPress side of things.

### Describe the ideal solution

Two possible options would be helpful:
- The ability to generate a link that the user can click which would send them a reset email.
- The second option would be the ability to call Auth0 passing the form values which would reset the user's password

The 1st option seems relatively straightforward and one that would be helpful for me in the short term

### Alternatives and current workarounds

Right now I'm planning to just log the user out and force them to the login form as a last resort

**Comment by evansims** [comment]
Hi @jackton1, thanks for your feature suggestion. I've backlogged this request, and we'll consider it for future development.
