### ISSUE TITLE
 WordPress, missing scope 

### ISSUE THREAD

**Issue by edent** [auth0/wp-auth0#906]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The WordPress social connection has stopped working due to a missing scope parameter.

When I try to log in, I get directed to `https://public-api.wordpress.com/oauth2/authorize?login_hint=&prompt=login&response_type=code&redirect_uri=https%3A%2F%2Fexample.eu.auth0.com%2Flogin%2Fcallback&scope=profile&state=123&client_id=456`

That shows the error:
```
Invalid request, please go back and try again.
Error Code: invalid_request
Error Message: Invalid "scope". See https://developer.wordpress.com/docs/oauth2/#token-scope.
```

If I manually add `&scope=auth` to the URl, it allows me to log in.

Note: This was previously working - but something at Auth0’s end has broken in the last few weeks. I have not changed anything in either Auth0 or my WordPress app.

Please can someone from Auth0 fix their built in social connection for WordPress as per [OAuth2 Authentication – WordPress.com Developer Resources 1](https://developer.wordpress.com/docs/oauth2/#token-scope)

### Reproduction

1. Add WordPress to Auth0's allowed social logins
2. Watch it break

### Additional context

I asked this a couple of weeks ago but got no response https://community.auth0.com/t/wordpress-missing-scope/135045/1

### wp-auth0 version

?

### WordPress version

6.5

### PHP version

8.3

**Comment by evansims** [comment]
Hi @edent, thanks for raising this. I have raised your concern internally with our product team, as has the Community team. It is being looked at.

(Closing, as this is an API endpoint issue rather than an SDK issue, but thank you for bringing it to our attention.)
