### ISSUE TITLE
API Encoding issue in 4.6.1

### ISSUE THREAD

**Issue by tstrimple** [auth0/wp-auth0#909]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After upgrading from 4.6.0 to 4.6.1 our custom database integration started failing. When investigating the problem, we found that the /index.php?a0_action=migration-ws-login endpoint was returning invalid JSON. It appears that the results are being htmlspecialchars encoded before being returned. 

Results from 4.6.1:
![bad](https://github.com/auth0/wordpress/assets/1328749/16561cab-fa44-4d5b-af6c-3fd448a3d91f)

Results from 4.6.0
![good](https://github.com/auth0/wordpress/assets/1328749/5523238f-f03d-44fb-9528-5832e9c9f2ad)

### Reproduction

Install version 4.6.1 of the 'Login by Auth0' plugin and make a call to the migration-ws-login endpoint. 

### wp-auth0 version

4.6.1

### WordPress version

6.5.5

### PHP version

8.0.30

**Comment by evansims** [comment]
Thanks for the heads up; it looks like some of the additional HTML sanitizations we added in the patch release are being mistakenly applied to the JSON payload. Let me see if I can track it down

**Comment by evansims** [comment]
Hi @tstrimple 👋 I've just released 4.6.2, which should resolve the issue for you. It may take a few minutes before the Marketplace shows the update. Please let me know if you continue encountering problems. Thanks!
