### ISSUE TITLE
Show widget in signup mode

### ISSUE THREAD

**Issue by louffoster** [auth0/wp-auth0#91]
Add a config to the shortcode that will present the widget in Sign Up view instead of Log In

**Comment by Buooy** [comment]
Wondering if there is a way to do this as well

**Comment by glena** [comment]
Yes, you can set this `{"mode":"signup" }` in the `Extra configuration:` setting:

<img width="465" alt="screen shot 2015-10-13 at 11 07 53" src="https://cloud.githubusercontent.com/assets/5647310/10457019/b495587e-719a-11e5-92aa-e5f694a489ac.png">

and Lock will look like this:

<img width="306" alt="screen shot 2015-10-13 at 11 08 33" src="https://cloud.githubusercontent.com/assets/5647310/10457039/ce8a683c-719a-11e5-9cb1-761940ee85e6.png">

**Comment by glena** [comment]
I would keep this to be handled by extra conf as recommended since with the adition of passwordless it could end up being messy. 
I would add this to the troubleshooting doc tho (https://auth0.com/docs/cms/wordpress/troubleshoot)
