### ISSUE TITLE
Add redirect param to auth0 shortcode config

### ISSUE THREAD

**Issue by louffoster** [auth0/wp-auth0#92]
Add a parameter to the shortcode so the user can specify a landing page after auto-login happens. This is useful for a site where a user can navigate to a point without being authenticated. With current behavior, the newly signed up and authenticated user is redirected to the home of the site, and must navigate back to where they were

**Comment by glena** [comment]
done with check redirections in shortcode and widget #139 (for V.Next, will be released next week)
