### ISSUE TITLE
Auth0 Plugin causes Elementor Page Builder to stop working

### ISSUE THREAD

**Issue by jcoggon** [auth0/wp-auth0#921]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I try to activate the Elementor Page Builder - it will just keep on loading and eventually suggest enabling Safe Mode.
![2024-12-02 11_51_24-](https://github.com/user-attachments/assets/4df3af1a-55b1-47b4-8053-e314c504ca3e)

### Reproduction

Step 1. Enable Auth0 WordPress Plugin
Step 2. Edit any page with Elementor

### Additional context

Elementor | Version 3.25.10 by Elementor.com
Elementor Pro | Version 3.25.4 by Elementor.com

### wp-auth0 version

5.2.1

### WordPress version

6.7.1

### PHP version

8.3.14

**Comment by kishore7snehil** [comment]
@jcoggon As of now, the `auth0` plugin doesn't support integration with any other third party plugin. This can be the reason that the eliminator can be misbehaving with `auth0` enabled.
The plugin is built on top of [Auth0-PHP](https://github.com/auth0/auth0-PHP) — Auth0's full-featured PHP SDK for Authentication and Management APIs.If you're looking to build a more extensive integration, please create a solution using the [Auth0-PHP SDK](https://github.com/auth0/auth0-php) instead.
