### ISSUE TITLE
Doesn't Seem that Lock Config Accepts "dict" parameter

### ISSUE THREAD

**Issue by brad-decker** [auth0/wp-auth0#93]
When doing the following:

{"dict": {"signin": {"title": "login"}}}

in the extra options setting, this does not override the title i set elsewhere and i cannot use the "action" option to change the button login text.

**Comment by glena** [comment]
Check the `Translation` field.

https://auth0.com/docs/cms/wordpress/configuration

**Comment by brad-decker** [comment]
Thanks @glena  -> maybe might want to allow overriding of the dict option in the extra options field to allow global configuration json files to be used? We're in the middle of migrating from one environment to the next and we're taking Auth0/Lock with us. More of a nice to have than a required feature or bug. Thanks!

**Comment by glena** [comment]
Great. Will have in mind. It should use the dict attribute of the extra settings field if translation is kept empty tho.

Thanks for reporting :)
