### ISSUE TITLE
Update wording for quickstart

### ISSUE THREAD

**Issue by richsands** [auth0/wp-auth0#96]
New suggested copy for the quickstart page:

---

# Auth0 for WordPress - Quick Start Guide

This wizard will guide you through the initial setup of the Auth0 for WordPress plugin.

Auth0 for WordPress integrates with the Auth0 cloud-based authentication service, giving you and your users:
* A modern, easy to use login box with all the features users have come to expect.
* Easy integration with 30+ social identity providers, enterprise SSO, and secure user/password authentication.
* Better security including multifactor authentication, passwordless authentication, password policies, all battle-tested.
* Stats on your users - demographics, locations, history.
* Super easy install - 5 minutes to a better login experience for users and powerful analytics for site owners.
* Customization and easy to use rules that give developers great flexibility.

For more information about this plugin, please see the [documentation](https://auth0.com/docs/wordpress). For more about the Auth0 service, please visit [auth0.com](http:auth0.com).

---
__IMPORTANT:__ This plugin replaces the standard WordPress login flow. Before you configure it, please be sure that is what what you're expecting! By default, the plugin will show a link to the old login page.

---

Because Auth0 is a cloud service, you'll need an account at Auth0 where you'll access many of its advanced features and set things up. If you already have an Auth0 account, your WordPress installation will be one of the applications authorized in your account. If you don't have an Auth0 account, this wizard will create one for you and add your site to it all from within WordPress.

Once set up, most of what you'll need to do can be handled from the plugin's settings page. The plugin calls the Auth0 APIs in order to configure account settings. If your site is behind a firewall that restricts access, you will need to whitelist https requests to *.auth0.com. 
If this isn't possible or desirable, or if you don't want to grant administrator privileges to one of the accounts managed by Auth0, then you can still manage your account manually using the [Auth0 Dashboard](https://manage.auth0.com).

->Click here to start<-

**Comment by glena** [comment]
Done, I think it would need some design, there is a lot of text now.
I will close this and create a specific issue for that.
