### ISSUE TITLE
"This user does not have enough scopes..." error is confusing.

### ISSUE THREAD

**Issue by richsands** [auth0/wp-auth0#98]
Suggested new wording:

---

The current user is not authorized to manage the Auth0 account. You must be both a WordPress site administrator and a user known to Auth0 to control Auth0 from this settings page. Please see the [documentation](https://auth0.com/docs/wordpress) for more information.

---

![image](https://cloud.githubusercontent.com/assets/3476582/9591061/b8a40d8a-5006-11e5-9950-5342162136f3.png)

**Comment by glena** [comment]
done
