### ISSUE TITLE
Quick setup informational banner confusing

### ISSUE THREAD

**Issue by richsands** [auth0/wp-auth0#99]
Suggested new wording:

---

Auth0 for WordPress is not yet configured. Click [HERE](http://mysite.com/wp-admin/admin.php?page=wpa0-setup) to configure the Auth0 for WordPress plugin using the Quick Setup Wizard.

---

If the plugin is not set up yet, this banner should show up everywhere on the admin console of WordPress except for on the Quick Setup Wizard page itself (confusing to show this on the page it points to). After the plugin is configured, either manually or through the wizard, this banner should disappear.

![image](https://cloud.githubusercontent.com/assets/3476582/9591378/f019a99e-5008-11e5-9b17-3a35e332a641.png)

**Comment by glena** [comment]
done
